# Declare routers / services / middlewares
http:
  routers:
    ai-sparql-builder:
      rule: {{ printf "Host(`%s`) && PathPrefix(`/ai-sparql-builder-poc`)" .Values.global.apiHostDomain }}
      service: ai-sparql-builder
      entryPoints:
        - web-api
      middleWares:
        - path-ai-sparql-builder
        - host-ai-sparql-builder

  services:
    ai-sparql-builder:
      loadBalancer:
        servers:
          - url: {{ printf "http://%s"  (include "traefik-proxy.hostAISparqlBuilder" .) }}

  middlewares:
    path-ai-sparql-builder:
      replacePathRegex:
        regex: "^/ai-sparql-builder-poc/(.*)"
        replacement: "/$1"

    host-ai-sparql-builder:
      headers:
        customRequestHeaders:
          host: {{ include "traefik-proxy.hostAISparqlBuilder" . }}
