# Declare routers / services / middlewares
# note: requests to /apis/ will have the whole path forwarded to the host
http:
  routers:
    apicurio:
      rule: {{ printf "Host(`%s`) && PathPrefix(`/apis`)" .Values.global.apiHostDomain }}
      service: apicurio
      entryPoints:
        - web-api
      middleWares:
        - host-apicurio

  services:
    apicurio:
      loadBalancer:
        servers:
          - url: {{ printf "http://%s"  (include "traefik-proxy.hostApicurio" .) }}

  middlewares:
    host-apicurio:
      headers:
        customRequestHeaders:
          host: {{ include "traefik-proxy.hostApicurio" . }}
