# Declare routers / services / middlewares
http:
  routers:
    search:
      rule: {{ printf "Host(`%s`) && PathPrefix(`/catalogue`)" .Values.global.apiHostDomain }}
      service: catalogue
      entryPoints:
        - web-api
      middleWares:
        - path-catalogue
        - host-catalogue

  services:
    catalogue:
      loadBalancer:
        servers:
          - url: {{ printf "http://%s"  (include "traefik-proxy.hostCatalogue" .) }}

  middlewares:
    path-catalogue:
      replacePathRegex:
        regex: "^/catalogue/(.*)"
        replacement: "/$1"

    host-catalogue:
      headers:
        customRequestHeaders:
          host: {{ include "traefik-proxy.hostCatalogue" . }}
