http:
  routers:
    deletion-worker:
      rule: {{ printf "Host(`%s`) && PathPrefix(`/deletion-worker`)" .Values.global.apiHostDomain }}
      service: deletion-worker
      entryPoints:
        - web-api
      middleWares:
        - path-deletion-worker
        - host-deletion-worker

  services:
    deletion-worker:
      loadBalancer:
        servers:
          - url: {{ printf "http://%s" (include "traefik-proxy.hostDeletionWorker" .) }}

  middlewares:
    path-deletion-worker:
      replacePathRegex:
        regex: "^/deletion-worker/(.*)"
        replacement: "/$1"
    host-deletion-worker:
      headers:
        customRequestHeaders:
          host: {{ include "traefik-proxy.hostDeletionWorker" . }}