# Declare routers / services / middlewares
# note: requests to /notifications/ will have the whole path forwarded to the host
http:
  routers:
    notifications:
      rule: {{ printf "Host(`%s`) && PathPrefix(`/notifications`)" .Values.global.apiHostDomain }}
      service: notifications
      entryPoints:
        - web-api
      middleWares:
        - host-notifications

  services:
    notifications:
      loadBalancer:
        servers:
          - url: {{ printf "http://%s"  (include "traefik-proxy.hostNotifications" .) }}

  middlewares:
    host-notifications:
      headers:
        customRequestHeaders:
          host: {{ include "traefik-proxy.hostNotifications" . }}
