# Declare routers / services / middlewares
http:
  routers:
    paperback-writer:
      rule: {{ printf "Host(`%s`) && PathPrefix(`/paperback`)" .Values.global.apiHostDomain }}
      service: paperback-writer
      entryPoints:
        - web-api
      middleWares:
        - path-paperback-writer
        - host-paperback-writer

  services:
    paperback-writer:
      loadBalancer:
        servers:
          - url: {{ printf "http://%s"  (include "traefik-proxy.hostPaperbackWriter" .) }}

  middlewares:
    path-paperback-writer:
      replacePathRegex:
        regex: "^/paperback/(.*)"
        replacement: "/$1"

    host-paperback-writer:
      headers:
        customRequestHeaders:
          host: {{ include "traefik-proxy.hostPaperbackWriter" . }}
