# Declare routers / services / middlewares
http:
  routers:
    spatial:
      rule: {{ printf "Host(`%s`) && PathPrefix(`/spatial`)" .Values.global.apiHostDomain }}
      service: spatial
      entryPoints:
        - web-api
      middleWares:
        - path-spatial
        - host-spatial

  services:
    spatial:
      loadBalancer:
        servers:
          - url: {{ printf "http://%s"  (include "traefik-proxy.hostSpatial" .) }}

  middlewares:
    path-spatial:
      replacePathRegex:
        regex: "^/spatial/(.*)"
        replacement: "/$1"

    host-spatial:
      headers:
        customRequestHeaders:
          host: {{ include "traefik-proxy.hostSpatial" . }}
