# Declare routers / services / middlewares
# note: requests to /apis/ will have the whole path forwarded to the host
http:
  routers:
    the-management:
      rule: {{ printf "Host(`%s`) && PathPrefix(`/management`)" .Values.global.apiHostDomain }}
      service: the-management
      entryPoints:
        - web-api
      middleWares:
        - path-the-management
        - host-the-management

  services:
    the-management:
      loadBalancer:
        servers:
          - url: {{ printf "http://%s"  (include "traefik-proxy.hostTheManagement" .) }}

  middlewares:

    path-the-management:
      replacePathRegex:
        regex: "^/management/(.*)"
        replacement: "/$1"

    host-the-management:
      headers:
        customRequestHeaders:
          host: {{ include "traefik-proxy.hostTheManagement" . }}
