{{- /*
Copyright (C) 2025 Telicent Limited
*/}}

apiVersion: v1
kind: Service

metadata:
  name: {{ include "traefik-proxy.serviceName" . }}
  namespace: {{ include "traefik-proxy.namespace" . | quote }}
  labels:
    {{- include "traefik-proxy.labels" . | nindent 4 }}

spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "traefik-proxy.selectorLabels" . | nindent 4 }}
  ports:
  - name: http-web
    appProtocol: http
    protocol: TCP
    port: {{ .Values.service.web.port }}
    targetPort: http-web
  - name: http-api
    appProtocol: http
    protocol: TCP
    port: {{ .Values.service.api.port }}
    targetPort: http-api
