{{- /*
Copyright (C) 2026 Telicent Limited
*/}}

apiVersion: v1
kind: Service

metadata:
  name: {{ include "traefik-proxy.serviceName" . }}
  namespace: {{ include "traefik-proxy.namespace" . | quote }}
  labels:
    {{- include "traefik-proxy.labels" . | nindent 4 }}

spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "traefik-proxy.selectorLabels" . | nindent 4 }}
  ports:
  - name: http-app
    appProtocol: http
    protocol: TCP
    targetPort: http-app
    port: {{ .Values.service.app.port }}

  - name: http-api
    appProtocol: http
    protocol: TCP
    targetPort: http-api
    port: {{ .Values.service.api.port }}

  - name: http-auth
    appProtocol: http
    protocol: TCP
    targetPort: http-auth
    port: {{ .Values.service.auth.port }}
