apiVersion: v1
data:
  env-config.js: |
    const SHARED_DOMAIN = "https://{{ .Values.global.appHostDomain }}";
    window._env_ = window._env_ || {};
    window.featureFlags = window.featureFlags || {};
    window.featureFlags.FF_CATALOG_UPDATE = true;

    // General config
    window._env_.BETA = false;
    window._env_.APP_SWITCH_LIBRARY = [
        {
            id: "telicent-user-portal",
            name: "user portal",
            url: `${SHARED_DOMAIN}/user-portal`,
            icon: "/data-catalog/assets/icons/UserPortalLight.svg",
        },
        {
            id: "telicent-graph",
            name: "graph",
            url: `${SHARED_DOMAIN}/graph`,
            icon: "/data-catalog/assets/icons/GraphLight.svg",
        },
        {
            id: "telicent-search",
            name: "search",
            url: `${SHARED_DOMAIN}/search`,
            icon: "/data-catalog/assets/icons/SearchLight.svg",
        },
        // THIS is catalog
        // {
        //   id: "telicent-catalog",
        //   name: "catalog",
        //   url: `${SHARED_DOMAIN}/data-catalog`,
        //   icon: "./assets/icons/catalog.svg",
        // },
    ];


    // Apis
    window._env_.SIGN_OUT_URL = `${SHARED_DOMAIN}/oauth2/sign_out?rd=/oauth2/authorize`;
    window.USER_PORTAL_URL = `${SHARED_DOMAIN}/user-portal`;
    window._env_.ACCESS_API_URL = `${SHARED_DOMAIN}/api/access`;
    window._env_.TRIPLE_STORE_URL = `${SHARED_DOMAIN}/api/sparql`;
    window._env_.RDF_WRITE_API_URI = `${SHARED_DOMAIN}/api/paperback`;

    // Apps - include if deploying
    // window._env_.GEO_APP_URL;
    window._env_.GRAPH_APP_URL = `${SHARED_DOMAIN}/graph`;
    window._env_.ACCESS_APP_URL = `${SHARED_DOMAIN}/access`;
    // window._env_.PARALOG_APP_URL;
kind: ConfigMap
metadata:
  name: {{ include "data-catalog.fullname" . }}-config
  labels:
  {{- include "data-catalog.labels" . | nindent 4 }}
