{{- /*
Copyright (C) 2026 Telicent Limited
*/}}
{{- if not .Values.httpIngester.configMap.existingEnvConfigMap -}}
apiVersion: v1
kind: ConfigMap

metadata:
  name: {{ include "http-ingester.envConfigMapName" . }}
  namespace: {{ include "document-pipeline.namespace" . | quote }}
  labels:
    {{- include "http-ingester.labels" . | nindent 6 }}

data:
  KAFKA_CONFIG_FILE_PATH: "/app/config/kafka-auth/kafka-config.properties"
  BOOTSTRAP_SERVERS: {{ .Values.global.kafka.bootstrapServers | quote }}

  ROUTE_CONFIG_DIRECTORY: "/app/config/routes"
  
  JAVA_OPTIONS: {{ .Values.httpIngester.java.jvmOptions | quote }}
  JWKS_URL: {{ printf "%s%s%s" "https://" .Values.global.authHostDomain "/oauth2/jwks" | quote }}
  USERINFO_URL: {{ printf "http://%s%s" (include "document-pipeline.hostAuth" . ) "/userinfo" | quote }}
  {{- if .Values.metrics.enabled }}
  OTEL_METRICS_EXPORTER: "prometheus"
  OTEL_TRACES_EXPORTER: "none"
  OTEL_LOGS_EXPORTER: "none"
  {{- end }}
{{- end }}
