{{- /*
Copyright (C) 2025 Telicent Limited
*/}}

{{- if or (not .Values.existingCacertConfigmapName) (.Values.cacert) -}}
{{- if .Values.cacert -}}
apiVersion: v1
kind: ConfigMap

metadata:
  name: {{ include "http-ingester.fullname" . }}-cacert
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "http-ingester.labels" . | nindent 4 }}

data:
  ca.crt: {{- .Values.cacert | toYaml | indent 1 }}
{{- end -}}
{{- end -}}
