{{- if and (not .Values.httpIngester.existingConfigMapName) (.Values.enabled) -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "http-ingester.fullname" .}}
  labels:
    {{- include "http-ingester.labels" . | nindent 4 }}

data:
  {{- range .Values.httpIngester.configuration.routes }}
  {{ .name }}.yaml: |
    #
    # Copyright (C) 2022 Telicent Limited
    #

    # A unique name for the route
    name: {{ .name }}
    # The destination Kafka topic for the route
    topic: {{ .topic }}
    # NB - securityLabel treated as a byte[] sequence so serialized as Base64
    # In this test configuration the label is simply test=true
    securityLabel: {{ .securityLabel }}
    # The Namespace URI that will be used to assign a unique URI to a document
    # URIs are generated deterministically based on this and the ingested document content
    namespace: {{ .namespace }}
    # Headers to copy from the request and/or apply onto document ingest events
    headers:
      {{- toYaml .headers | nindent 4 }}
  {{- end }}
{{- end -}}