{{- /*
Copyright (C) 2025 Telicent Limited
*/}}
{{- if .Values.enabled -}}
apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ include "http-ingester.fullname" . }}
  namespace: {{ include "document-pipeline.namespace" . | quote }}
  labels:
    {{- include "http-ingester.labels" . | nindent 4 }}
  {{- with .Values.httpIngester.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}

spec:
  replicas: {{ .Values.httpIngester.replicas }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      {{- include "http-ingester.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
      {{- include "http-ingester.labels" . | nindent 8 }}
      {{- with .Values.httpIngester.podLabels }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      annotations:
        checksum/configEnv: {{ include (print $.Template.BasePath "/httpIngester/configmap-env.yaml") . | sha256sum }}
        checksum/configRoutes: {{ include (print $.Template.BasePath "/httpIngester/configmap-routes.yaml") . | sha256sum }}
      {{- with .Values.httpIngester.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}

    spec:
      serviceAccountName: {{ include "document-pipeline.serviceAccountName" . }}
      securityContext: {{ .Values.httpIngester.podSecurityContext | default .Values.podSecurityContext | toYaml | nindent 8 }}

      {{- $pullSecret := .Values.global.imagePullSecrets | default .Values.httpIngester.image.pullSecrets }}
      {{- with $pullSecret }}
      imagePullSecrets:
        {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- if .Values.httpIngester.initContainers }}
      initContainers:
      {{- with .Values.httpIngester.initContainers }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}
        image: {{ include "http-ingester.image" . }}
        imagePullPolicy: {{ .Values.httpIngester.image.pullPolicy }}
        resources: {{ .Values.httpIngester.resources | default .Values.resources | toYaml | nindent 10 }}
        securityContext: {{ .Values.httpIngester.containerSecurityContext | default .Values.containerSecurityContext | toYaml | nindent 10 }}


        {{- if .Values.httpIngester.extraEnvVars }}
        env:
        {{- range .Values.httpIngester.extraEnvVars }}
        - name: {{ .name }}
          value: {{ .value | quote }}
        {{- end }}
        {{- end }}
        envFrom:
        - configMapRef:
            name: {{ include "http-ingester.envConfigMapName" . }}

        ports:
        - name: http
          protocol: TCP
          containerPort: 15431

        readinessProbe:
          httpGet:
            path: /version-info
            port: 15431
        livenessProbe:
          httpGet:
            path: /healthz
            port: 15431

        volumeMounts:
        - name: routes-volume
          mountPath: /app/config/routes
        - name: kafka-auth-config
          mountPath: /app/config/kafka-auth
        {{- if .Values.global.truststore.existingSecret }}
        - name: java-truststore
          mountPath: {{ .Values.global.truststore.mountPath | default "/app/config/truststore" }}
        {{- end }}
        {{- with .Values.httpIngester.extraVolumeMounts }}
          {{- toYaml . | nindent 12 }}
        {{- end }}
      
      {{- with .Values.httpIngester.sidecars }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      - name: routes-volume
        configMap:
          name: {{ include "http-ingester.routesConfigMapName" . }}
      - name: kafka-auth-config
        secret:
        {{- if .Values.global.kafka.existingConfigSecretName }}
          secretName: {{ .Values.global.kafka.existingConfigSecretName }}
        {{- else }}
          secretName: {{ include "document-pipeline.fullname" . }}-kafka-config
        {{- end }}
      {{- if .Values.global.truststore.existingSecret }}
      - name: java-truststore
        secret:
          secretName: {{ .Values.global.truststore.existingSecret }}
      {{- end }}
      {{- with .Values.httpIngester.extraVolumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      
      {{- with .Values.httpIngester.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.httpIngester.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.httpIngester.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end -}}
