{{- if .Values.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "http-ingester.fullname" . }}
  labels:
    {{- include "http-ingester.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 15431
      targetPort: 15431
      protocol: TCP
      name: http
  selector:
    {{- include "http-ingester.selectorLabels" . | nindent 4 }}
{{- end -}}