{{- /*
Copyright (C) 2025 Telicent Limited
*/}}
{{- if .Values.global.istioVirtualServiceEnabled -}}

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService

metadata:
  name: {{ include "user-portal-ui.fullname" . }}
  labels:
  {{- include "user-portal-ui.labels" . | nindent 4 }}

spec:
  gateways:
  - {{ .Values.global.istioNamespace }}/{{ .Values.global.istioGatewayName }}
  hosts:
  - {{ .Values.global.appHostDomain }}
  http:
  - match:
    - uri:
        exact: /user-portal
    redirect:
      uri: /user-portal/
  - match:
    - uri:
        prefix: /user-portal/
    route:
    - destination:
        host: {{ include "user-portal-ui.fullname" . }}
        port:
          number: {{ .Values.service.port }}
{{- end }}
