apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "access-api.fullname" . }}
  labels:
  {{- include "access-api.labels" . | nindent 4 }}
spec:
  gateways:
  - {{ .Values.global.appsGateway }}
  hosts:
  - {{ .Values.global.appHostDomain }}
  http:
  - match:
    - uri:
        prefix: /api/access
    rewrite:
      uriRegexRewrite:
        match: ^/api/access(/|$)(.*)
        rewrite: /\2
    route:
    - destination:
        host: {{ include "access-api.serviceName" . }}
        port:
          number: {{ .Values.service.port }}
