{{- /*
Copyright (C) 2026 Telicent Limited
*/}}
{{- if not .Values.bootstrap.clients.existingConfigMap }}
apiVersion: v1
kind: ConfigMap

metadata:
  name: {{ include "auth.clientsConfigMapName" . }}
  namespace: {{ include "auth.namespace" . | quote }}
  labels:
    {{- include "auth.labels" . | nindent 4 }}

data:
  clients.yaml: |
    clients: 
      public:
        {{- if .Values.bootstrap.clients.public}}
        {{- toYaml .Values.bootstrap.clients.public | nindent 8 }}
        {{- end }}
        {{- if .Values.global.enterprise }}
        - client_id: telicent-admin-ui
          client_name: Telicent Admin UI Client
          refresh_token_ttl: {{.Values.idp.clientRefreshTokenTtl}}
          access_token_ttl: {{.Values.idp.clientAccessTokenTtl}}
          redirect_uris: 
            - https://{{.Values.global.appHostDomain}}/admin/callback
            - https://{{.Values.global.appHostDomain}}/admin/auth-redirect-uri
          post_logout_redirect_uris:
            - https://{{.Values.global.appHostDomain}}/admin
        - client_id: telicent-search-ui
          client_name: Telicent Search UI Client
          refresh_token_ttl: {{.Values.idp.clientRefreshTokenTtl}}
          access_token_ttl: {{.Values.idp.clientAccessTokenTtl}}
          redirect_uris: 
            - https://{{.Values.global.appHostDomain}}/search/callback
            - https://{{.Values.global.appHostDomain}}/search/auth-redirect-uri
          post_logout_redirect_uris:
            - https://{{.Values.global.appHostDomain}}/search
        - client_id: telicent-graph-ui
          client_name: Telicent Graph UI Client
          refresh_token_ttl: {{.Values.idp.clientRefreshTokenTtl}}
          access_token_ttl: {{.Values.idp.clientAccessTokenTtl}}
          redirect_uris: 
            - https://{{.Values.global.appHostDomain}}/graph/callback
            - https://{{.Values.global.appHostDomain}}/graph/auth-redirect-uri
          post_logout_redirect_uris:
            - https://{{.Values.global.appHostDomain}}/graph
        {{- end }}
        - client_id: telicent-query-ui
          client_name: Telicent Query UI Client
          refresh_token_ttl: {{.Values.idp.clientRefreshTokenTtl}}
          access_token_ttl: {{.Values.idp.clientAccessTokenTtl}}
          redirect_uris: 
            - https://{{.Values.global.appHostDomain}}/query/callback
            - https://{{.Values.global.appHostDomain}}/query/auth-redirect-uri
          post_logout_redirect_uris:
            - https://{{.Values.global.appHostDomain}}/query

      confidential:
        {{- if .Values.global.enterprise }}
        - client_id: registry-api
          client_name: "Apicurio Registry API"
          client_secret: {{ .Values.bootstrap.clients.apicurioClientSecret | required "bootstrap.clients.apicurioClientSecret is required when global.enterprise is true" }}
          client_authentication_method: client_secret_post
        {{- end }}
        {{- if .Values.bootstrap.clients.confidential }}
        {{- toYaml .Values.bootstrap.clients.confidential | nindent 8 }}
        {{- end }}
{{- end }}
