{{- /*
Copyright (C) 2025 Telicent Limited
*/}}
{{- if not .Values.groups.existingConfigMap }}
apiVersion: v1
kind: ConfigMap

metadata:
  name: {{ include "auth.groupsConfigMapName" . }}
  namespace: {{ include "auth.namespace" . | quote }}
  labels:
    {{- include "auth.labels" . | nindent 4 }}

data:
  groups.yml: |
    groups: 
      {{- toYaml .Values.groups | nindent 6 }}   
{{- end }}
