{{- /*
Copyright (C) 2025 Telicent Limited
*/}}
{{- if not .Values.configMap.existingEnvConfigMap -}}
apiVersion: v1
kind: ConfigMap

metadata:
  name: {{ include "auth.envConfigMapName" . }}
  namespace: {{ include "auth.namespace" . | quote }}
  labels:
    {{- include "auth.labels" . | nindent 4 }}

data:
  # Startup configuration to be loaded
  {{- if .Values.bootstrap.enabled }}
  APP_SEED_REGISTERED_CLIENT_DATA: "/app/config/startup/clients.yaml"
  APP_SEED_GROUPS_DATA: "/app/config/startup/groups.yaml"
  {{- end }}

  # PostgreSQL
  POSTGRES_URI: {{ .Values.postgresSql.uri | quote }}
  
  SUPER_USER_IDENTIFIER: {{ .Values.idp.superUserIdentifier | quote }}
  COOKIE_PARENT_DOMAIN: {{ .Values.idp.cookieParentDomain | quote }}
  COOKIE_SECURE: {{ .Values.idp.cookieSecure | quote  }}
  TOKEN_ISSUER_URL: {{ printf "%s%s" "https://" .Values.global.authHostDomain | quote }}

  JAVA_OPTS:  {{ .Values.java.jvmOptions | quote }}

  # IDP
  EXTERNAL_IDP_URL: {{ .Values.idp.issuerUrl | quote }}
  EXTERNAL_IDP_CLIENT_NAME: {{ .Values.idp.clientName | quote }}
  EXTERNAL_IDP_ID_CLAIM: {{ .Values.idp.emailClaim | quote }}
  EXTERNAL_IDP_AUTHORIZE_ENDPOINT:  {{ .Values.idp.authorizationPath | quote }}
  EXTERNAL_IDP_JWK_SET_ENDPOINT:  {{ .Values.idp.jwksPath | quote }}

  # Log levels
  LOGGING_LEVEL_API: {{ .Values.logs.api.level  }}
  LOGGING_LEVEL_SERVICE: {{ .Values.logs.service.level  }}
  LOGGING_LEVEL_REPO: {{ .Values.logs.repo.level  }}
  LOGGING_LEVEL_SECURITY: {{ .Values.logs.repo.level  }}
  LOGGING_LEVEL_OAUTH2: {{ .Values.logs.oauth2.level }}
  LOGGING_LEVEL_GENERAL: {{ .Values.logs.general.level  }}
  LOGGING_LEVEL_TRACE: {{ .Values.logs.trace.level }}
{{- end }}
