{{- /*
Copyright (C) 2026 Telicent Limited
*/}}
{{- if not .Values.bootstrap.clients.registry.existingSecret }}
apiVersion: v1
kind: Secret
type: Opaque

metadata:
  name: {{ include "auth.registryClientSecretName" . }}
  namespace: {{ include "auth.namespace" . | quote }}
  labels:
    {{- include "auth.labels" . | nindent 4 }}

data:
  client_secret: {{ .Values.bootstrap.clients.registry.clientSecret | b64enc | quote }}
{{- end }}