{{- /*
Copyright (C) 2025 Telicent Limited
*/}}

{{- if not .Values.postgresSecret.existingSecret }}
apiVersion: v1
kind: Secret

metadata:
  name: {{ include "auth.postgresSecretName" . }}
  labels:
    {{- include "auth.labels" . | nindent 4 }}

data:
  uri: {{ .Values.postgresSecret.uri | b64enc | quote }}
  username: {{ .Values.postgresSecret.username | b64enc | quote }}
  password: {{ .Values.postgresSecret.password | b64enc | quote }}
{{- end }}
