{{- /*
Copyright (C) 2025 Telicent Limited
*/}}

{{- if not .Values.externalIdp.existingSecret }}
apiVersion: v1
kind: Secret

metadata:
  name: {{ include "auth.externalIdpSecretName" . }}
  labels:
    {{- include "auth.labels" . | nindent 4 }}

data:
  APPS_CLIENT_ID: {{ .Values.externalIdp.clientId | b64enc | quote }}
  APPS_CLIENT_SECRET: {{ .Values.externalIdp.clientSecret | b64enc | quote }}
{{- end }}
