{{- /*
Copyright (C) 2025 Telicent Limited
*/}}
{{- if not .Values.idp.existingSecret }}
apiVersion: v1
kind: Secret
type: Opaque

metadata:
  name: {{ include "auth.idpSecretName" . }}
  namespace: {{ include "auth.namespace" . | quote }}
  labels:
    {{- include "auth.labels" . | nindent 4 }}

data:
  clientid: {{ .Values.idp.clientId | b64enc | quote }}
  clientsecret: {{ .Values.idp.clientSecret | b64enc | quote }}
{{- end }}
