{{- /*
Copyright (C) 2026 Telicent Limited
*/}}
{{- if not .Values.bootstrap.clients.registry.existingSecret }}
{{- $secretName := include "auth.registryClientSecretName" . }}
{{- $existingSecret := lookup "v1" "Secret" (include "auth.namespace" .) $secretName }}
{{- $clientSecret := .Values.bootstrap.clients.registry.clientSecret }}
{{- if and (not $clientSecret) $existingSecret }}
{{- $clientSecret = index $existingSecret.data "client_secret" | b64dec }}
{{- else if not $clientSecret }}
{{- $clientSecret = randAlphaNum 32 }}
{{- end }}
apiVersion: v1
kind: Secret
type: Opaque

metadata:
  name: {{ $secretName }}
  namespace: {{ include "auth.namespace" . | quote }}
  labels:
    {{- include "auth.labels" . | nindent 4 }}

data:
  client_secret: {{ $clientSecret | b64enc | quote }}
{{- end }}