{{- /*
Copyright (C) 2025 Telicent Limited
*/}}

{{- if not .Values.externalIdpSecret.existingSecret }}
apiVersion: v1
kind: Secret

metadata:
  name: {{ include "auth.externalIdpSecretName" . }}
  labels:
    {{- include "auth.labels" . | nindent 4 }}

data:
  url: {{ .Values.externalIdpSecret.externalIdpUrl | b64enc | quote }}
  clientId: {{ .Values.externalIdpSecret.externalIdpClientId | b64enc | quote }}
  clientSecret: {{ .Values.externalIdpSecret.externalIdpClientSecret | b64enc | quote }}
  clientName: {{ .Values.externalIdpSecret.externalIdpClientName | b64enc | quote }}
{{- end }}
