{{- /*
Copyright (C) 2025 Telicent Limited
*/}}
{{- if not .Values.postgresSql.existingSecret }}
apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth

metadata:
  name: {{ include "auth.postgresSqlSecretName" . }}
  namespace: {{ include "auth.namespace" . | quote }}
  labels:
    {{- include "auth.labels" . | nindent 4 }}

data:
  username: {{ .Values.postgresSql.username | b64enc | quote }}
  password: {{ .Values.postgresSql.password | b64enc | quote }}
{{- end -}}
