{{- /*
Copyright (C) 2026 Telicent Limited
*/}}
{{- if not .Values.forwardAuth.existingSecret }}
apiVersion: v1
kind: Secret
type: Opaque

metadata:
  name: {{ include "auth.forwardAuthSecretName" . }}
  namespace: {{ include "auth.namespace" . | quote }}
  labels:
    {{- include "auth.labels" . | nindent 4 }}

data:
  header: {{ .Values.forwardAuth.header | b64enc | quote }}
{{- end }}
