{{- /*
Copyright (C) 2025 Telicent Limited
*/}}

{{- if not .Values.forwardAuth.existingSecret }}
apiVersion: v1
kind: Secret

metadata:
  name: {{ include "auth.forwardAuthSecretName" . }}
  labels:
    {{- include "auth.labels" . | nindent 4 }}

data:
  FORWARD_AUTH_SECRET: {{ .Values.forwardAuth.secretValue | b64enc | quote }}
{{- end }}
