{{- /*
Copyright (C) 2025 Telicent Limited
*/}}

apiVersion: v1
kind: Service

metadata:
  name: {{ include "auth.serviceName" . }}
  namespace: {{ include "auth.namespace" . | quote }}
  labels:
    {{- include "auth.labels" . | nindent 4 }}

spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "auth.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      appProtocol: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: http
     
