{{- /*
Copyright (C) 2025 Telicent Limited
*/}}
{{- if and .Values.enabled .Values.global.enterprise (ne .Values.global.zeroTrust.mode "disabled") }}
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy

metadata:
  name: {{ include "ai-model-provider.fullname" . }}-ingress
  namespace: {{ include "ai-model-provider.namespace" . | quote }}
  labels:
    {{- include "ai-model-provider.labels" . | nindent 4 }}

spec:
  selector:
    matchLabels:
      {{- include "ai-model-provider.selectorLabels" . | nindent 6 }}
  action: ALLOW
  rules:
  - from:
    - source:
        principals:
          {{- include "ai-model-provider.ingressPrincipal" . | nindent 8 }}

{{- end }}
