{{- /*
Copyright (C) Telicent Limited
*/}}
{{- if .Values.enabled -}}
apiVersion: v1
kind: Service

metadata:
  name: {{ include "grpc-client.serviceName" . }}
  namespace: {{ include "grpc-client.namespace" . | quote }}
  labels:
    {{- include "grpc-client.labels" . | nindent 4 }}

spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "grpc-client.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      appProtocol: http
      protocol: TCP
      targetPort: http
      port: {{ .Values.service.port }}
{{- end }}
