{{- /*
Copyright (C) 2025 Telicent Limited
*/}}

{{- if not .Values.content-indexer.elasticSecret.existingSecret }}
apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth

metadata:
  name: {{ include "content-indexer.elasticSecretName" . }}
  labels:
    {{- include "document-pipeline.labels" . | nindent 4 }}

data:
  username: {{ .Values.content-indexer.elasticSecret.username | b64enc | quote }}
  password: {{ .Values.content-indexer.elasticSecret.password | b64enc | quote }}
{{- end }}
