{{- /*
Copyright (C) 2025 Telicent Limited
*/}}

{{- if not .Values.contentIndexer.elastic.existingSecret }}

apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth

metadata:
  name: {{ include "contentIndexer.elasticSecretName" . }}
  labels:
    {{- include "document-pipeline.labels" . | nindent 4 }}

data:
  username: {{ .Values.contentIndexer.elastic.username | b64enc | quote }}
  password: {{ .Values.contentIndexer.elastic.password | b64enc | quote }}
{{- end }}
