{{- /*
Copyright (C) 2025 Telicent Limited
*/}}

{{- if not .Values.contentIndexer.elasticSecrets.existingEnvironmentSecret }}
apiVersion: v1
kind: Secret

metadata:
  name: {{ include "content-indexer.fullname" . }}
  labels:
    {{- include "document-pipeline.labels" . | nindent 4 }}

type: Opaque
data:
  ELASTIC_USER: {{ .Values.contentIndexer.elasticSecrets.elasticUser | b64enc | quote }}
  ELASTIC_PASSWORD: {{ .Values.contentIndexer.elasticSecrets.elasticPassword | b64enc | quote }}
  TRUSTSTORE_PASS: {{ .Values.contentIndexer.elasticSecrets.truststorePass | b64enc | quote }}
{{- end }}