{{- /*
Copyright (C) 2026 Telicent Limited
*/}}
{{- if .Values.enabled -}}
apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ include "notifications.fullname" . }}
  namespace: {{ include "notifications.namespace" . | quote }}
  labels:
    {{- include "notifications.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}

spec:
  replicas: {{ .Values.replicas }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      {{- include "notifications.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
      {{- include "notifications.labels" . | nindent 8 }}
      {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      annotations:
        checksum/configEnv: {{ include (print $.Template.BasePath "/configmap-env.yaml") . | sha256sum }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}

    spec:
      serviceAccountName: {{ include "notifications.serviceAccountName" . }}
      securityContext: {{- toYaml .Values.podSecurityContext | nindent 8 }}

      {{- $pullSecret := .Values.global.imagePullSecrets | default .Values.image.pullSecrets }}
      {{- with $pullSecret }}
      imagePullSecrets:
        {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- if .Values.initContainers }}
      initContainers:
      {{- with .Values.initContainers }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}
        image: {{ include "notifications.image" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources: {{- toYaml .Values.resources | nindent 10 }}
        securityContext: {{- toYaml .Values.containerSecurityContext | nindent 10 }}

        env:
        - name: DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: {{ include "notifications.postgresSecretName" . }}
              key: username
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "notifications.postgresSecretName" . }}
              key: password

        {{- range .Values.extraEnvVars }}
        - name: {{ .name }}
          {{- if .valueFrom }}
          valueFrom:
            {{- toYaml .valueFrom | nindent 12 }}
          {{- else }}
          value: {{ .value | quote }}
          {{- end }}
        {{- end }}
        envFrom:
        - configMapRef:
             name: {{ include "notifications.envConfigMapName" . }}

        ports:
        - name: http
          protocol: TCP
          containerPort: 22222

        readinessProbe:
          httpGet:
            path: /healthz
            port: 22222
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 60
          timeoutSeconds: 10
        livenessProbe:
          httpGet:
            path: /version-info
            port: 22222
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 60
          timeoutSeconds: 5

        volumeMounts:
        - name: kafka-auth-config
          mountPath: /app/config/kafka-auth/
        {{- with .Values.extraVolumeMounts }}
          {{- toYaml . | nindent 12 }}
        {{- end }}

      {{- with .Values.sidecars }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      - name: kafka-auth-config
        secret:
        {{- if .Values.global.kafka.existingConfigSecretName }}
          secretName: {{ .Values.global.kafka.existingConfigSecretName }}
        {{- else }}
          secretName: {{ include "notifications.fullname" . }}-kafka-config
        {{- end }}
      {{- with .Values.extraVolumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
