{{- /*
Copyright (C) 2026 Telicent Limited
*/}}
{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount

metadata:
  name: {{ include "showcase-ui.serviceAccountName" . }}
  namespace: {{ include "showcase-ui.namespace" . | quote }}
  labels:
    {{- include "showcase-ui.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}

automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}
