apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: {{ include "query.fullname" . }}-ingress
  labels: 
    {{ include "query.labels" . | nindent 4 }}
spec:
  action: ALLOW
  rules:
    - from:
        - source:
            principals:
              - {{ include "query.ingressPrincipal" . }}
      to:
        - operation:
            methods:
              - GET
  selector:
    matchLabels:
    {{ include "query.selectorLabels" . | nindent 6 }}
