{{- /*
Copyright (C) 2025 Telicent Limited
*/}}

apiVersion: security.istio.io/v1
kind: AuthorizationPolicy

metadata:
  name: {{ include "query-ui.fullname" . }}-ingress
  labels: 
    {{ include "query-ui.labels" . | nindent 4 }}

spec:
  action: ALLOW
  rules:
    - from:
        - source:
            principals:
              - {{ include "query-ui.ingressPrincipal" . }}
      to:
        - operation:
            methods:
              - GET
  selector:
    matchLabels:
    {{ include "query-ui.selectorLabels" . | nindent 6 }}
