{{- /*
Copyright (C) 2025 Telicent Limited
*/}}

apiVersion: v1
kind: ConfigMap

metadata:
  name: {{ include "query.configMapName" . }}
  labels:
    {{- include "query.labels" . | nindent 4 }}

data:
  env-config.js: |
    const DOMAIN = "{{ .Values.global.appHostDomain }}"; 
    // Configure the Smart Cache Graph GraphQL API endpoint as used by the client browser.
    window.GRAPHQL_URL = `https://${DOMAIN}/api/graphql/knowledge/graphql`;
    // Configure the Smart Cache Graph SPARQL API endpoint as used by the client browser.
    window.SPARQL_URL = `https://${DOMAIN}/api/sparql/knowledge/sparql`;
    // Configure the Access API endpoint as used by the client browser.
    window.ACCESS_URL = `https://${DOMAIN}/api/access`;
    window.BETA = false;
