apiVersion: v1
kind: ConfigMap

metadata:
  name: {{ include "query.configMapName" . }}
  labels:
    app.kubernetes.io/name: {{ include "query.name" . }}
    helm.sh/chart: {{ include "query.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}

data:
  env-config.js: |
    const DOMAIN = "{{  coalesce ((.Values.global).appHostDomain) .Values.configuration.appHostDomain }}"; 
    // Configure the Smart Cache Graph GraphQL API endpoint as used by the client browser.
    window.GRAPHQL_URL = `${DOMAIN}/api/graphql/knowledge/graphql`;
    // Configure the Smart Cache Graph SPARQL API endpoint as used by the client browser.
    window.SPARQL_URL = `${DOMAIN}/api/sparql/knowledge/sparql`;
    // Configure the Access API endpoint as used by the client browser.
    window.ACCESS_URL = `${DOMAIN}/api/access`;
