{{- /*
Copyright (C) 2025 Telicent Limited
*/}}

apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ include "query.fullname" . }}
  labels:
    {{- include "query.labels" . | nindent 4 }}

spec:
  replicas: {{ .Values.replicas }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate

  selector:
    matchLabels:
    {{- include "query.selectorLabels" . | nindent 6 }}

  template:
    metadata:
      annotations:
        {{- range $key, $value := .Values.annotations }}
          {{ $key }}: {{ $value | quote }}
        {{- end }}
      labels:
        {{- include "query.labels" . | nindent 8 }}

    spec:
      serviceAccountName: {{ include "query.serviceAccountName" . }}
      securityContext: {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: query-ui
        image: {{ .Values.image.repository }}:{{ include "query.version" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources: {{- toYaml .Values.resources | nindent 10 }}
        securityContext: {{- toYaml .Values.containerSecurityContext | nindent 10 }}

        ports:
        - containerPort: 8080
          name: http
          protocol: TCP

        readinessProbe:
          httpGet:
            path: /query/health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 2
        livenessProbe:
          httpGet:
            path: /query/health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 2

        volumeMounts:
        - mountPath: /usr/local/nginx/html/env-config.js
          name: app-config-volume
          subPath: env-config.js

      volumes:
      - configMap:
          name: {{ include "query.configMapName" . }}
        name: app-config-volume

      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}  
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}     
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
