apiVersion: v1
kind: ServiceAccount

metadata:
  name: {{ include "query.fullname" . }}

  labels:
  {{- include "query.labels" . | nindent 4 }}

  annotations:
    {{- toYaml .Values.serviceAccount.annotations | nindent 4 }}
