{{- /*
Copyright (C) 2025 Telicent Limited
*/}}

apiVersion: v1
kind: ConfigMap

metadata:
  name: {{ include "admin-ui.configMapName" . }}
  namespace: {{ include "admin-ui.namespace" . | quote }}
  labels:
    {{- include "admin-ui.labels" . | nindent 4 }}

data:
  env-config.js: |
    window._env_ = window._env_ || {};
    
    window._env_.BETA = true;
    window._env_.APP_SWITCH_LIBRARY = [
      {
        id: "telicent-graph",
        name: "graph",
        url: "https://{{ .Values.global.appHostDomain }}/graph",
        icon: "/admin/assets/icons/graph.svg",
      },
      {
        id: "telicent-search",
        name: "search",
        url: "https://{{ .Values.global.appHostDomain }}/search",
        icon: "/admin/assets/icons/search.svg",
      },
      {
        id: "telicent-catalog",
        name: "catalog",
        url: "https://{{ .Values.global.appHostDomain }}/data-catalog",
        icon: "/admin/assets/icons/catalog.svg",
      },
    ];


    // Admin APi end-point
    window._env_.AUTH_API_URL = "https://{{ .Values.global.apiHostDomain }}/auth";

    // Apps
    window._env_.AUTH_V2_CONFIG = {
      authServerUrl: "https://{{ .Values.global.authHostDomain }}",
      clientId: "{{ .Values.oauth.clientId }}",
      scope: "{{ .Values.oauth.scopes }}",
      redirectUri: "https://{{ .Values.global.appHostDomain }}/admin/callback",
      popupRedirectUri: "https://{{ .Values.global.appHostDomain }}/admin/auth-redirect-uri",
      onLogout: () => {
        console.log("You are now logged out. Redirecting");
        window.location.href = "/admin";
      },
    };

    window.featureFlags = {
      FF_SKIP_AUTH: true,
      FF_AUTH_V2: true,
    }
