apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: {{ include "core-mesh.fullname" . }}-ingress-to-access-api
  labels:
  {{- include "core-mesh.labels" . | nindent 4 }}
spec:
  action: ALLOW
  rules:
  - from:
    - source:
        principals:
        - {{ include "core-mesh.ingressPrincipal" . }}
    to:
    - operation:
        methods:
        - GET
        - POST
        - DELETE
        - PUT
        - PATCH
    when:
    - key: request.auth.claims[groups]
      values:
      - tc_admin
  - from:
    - source:
        principals:
        - {{ include "core-mesh.ingressPrincipal" . }}
    to:
    - operation:
        methods:
        - GET
        paths:
        - /whoami
    when:
    - key: request.auth.claims[groups]
      values:
      - tc_read
  selector:
    matchLabels:
    {{- include "core-mesh.accessApiSelectors" . | nindent 6 }}
