apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: {{ include "core-mesh.fullname" . }}-ingress-to-graph-server
  labels:
  {{- include "core-mesh.labels" . | nindent 4 }}
spec:
  action: ALLOW
  rules:
    - from:
        - source:
            principals:
            - {{ include "core-mesh.ingressPrincipal" . }}
      to:
        - operation:
            methods:
              - GET
              - POST
            paths:
              - /knowledge/sparql
              - /knowledge/sparql/*
              - /knowledge/query
              - /knowledge/query/*
              - /ontology/sparql
              - /ontology/sparql/*
              - /ontology/query
              - /ontology/query/*
              - /catalog/sparql
              - /catalog/sparql/*
              - /catalog/query
              - /catalog/query/*
        - operation:
            methods:
              - POST
            paths:
              - /knowledge/graphql
              - /knowledge/graphql/*
              - /knowledge/shacl
              - /knowledge/shacl/*
      when:
        - key: request.auth.claims[groups]
          values:
            - tc_read
  selector:
    matchLabels:
    {{- include "core-mesh.graphServerSelectors" . | nindent 6 }}
