# Copyright (C) 2025 Telicent Limited
# Telicent IES Regions Ontology Adapter stand-alone chart

# @section Global Parameters
# @descStart
# Contains global parameters. Not explicitly used in this chart, added to maintain consistency across Telicent charts.
# These parameters can be referenced in sub-charts as `.Values.global.<parameter-name>`.
# @descEnd

global:
  ## Current available global image parameters: imageRegistry and imagePullSecrets
  ## Please, note that this will override the image parameters
  # @key global.imageRegistry Global image registry
  imageRegistry: ""
  # E.g.
  # imagePullSecrets:
  #   - myRegistryKeySecretName
  # @key global.imagePullSecrets Global registry secret names as an array
  imagePullSecrets: []

  # @key global.enterprise Enable enterprise mode, adding additional features and configurations
  enterprise: false

  # @key global.appHostDomain Domain associated with Telicent application services
  appHostDomain: "apps.telicent.io"
  # @key global.authHostDomain Domain associated with Telicent authentication services, including OIDC providers
  authHostDomain: "auth.telicent.io"
  # @key global.groupsClaim Key used to retrieve groups from the OIDC provider
  groupsClaim: "groups"
  # @key global.jwksUrl Endpoint exposing multiple public keys represented as JWKs (JSON Web Key Set)
  # NOTE: For Dex the endpoint would be https://{yourDexDomain}/keys
  jwksUrl: "https://{yourAuthdomain}/.well-known/jwks.json"

  # @key global.istioNamespace Namespace in which Istio is deployed
  # NOTE: Istio, by default, is deployed within the 'istio-system' namespace
  istioNamespace: istio-system
  # @key global.istioServiceAccountName Name of the Istio service account
  istioServiceAccountName: istio-ingress
  # @key global.istioGatewayName Name of the Istio Gateway Resource (LB operating at the edge of the mesh)
  istioGatewayName: ingress-gateway

  # @section Kafka Parameters
  kafka:
    # @key global.kafka.bootstrapServers Comma separated list containing Kafka bootstrap servers
    bootstrapServers: "kafka-bootstrap.kafka.svc.cluster.local:9092"
    # @key global.kafka.existingConfigSecretName Name of an existing secret containing Kafka configuration (preferred over individual settings below for security)
    existingConfigSecretName: ""
    # @key global.kafka.username Username for Kafka authentication
    username: "your.kafka.username.here"
    # @key global.kafka.password Password for Kafka authentication
    password: "your.kafka.password.here"
    # @key global.kafka.protocol Protocol used for Kafka communication
    protocol: "SASL_SSL"
    # @key global.kafka.mechanism SASL mechanism used for Kafka authentication
    mechanism: "SCRAM-SHA-512"

  # @key global.existingTruststoreSecretName Name of an existing secret containing the truststore
  existingTruststoreSecretName: ""
  truststore:
    # @key global.truststore.mountPath The mount path for the truststore in the container
    mountPath: /app/config/truststore

# @section Deployment Parameters
# @key replicaCount Number of replicas to deploy
replicaCount: 1

# This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
# @section Image Parameters
image:
  # @key image.registry Container image registry
  registry: quay.io
  # @key image.repository Container image name
  repository: telicent/tc-ies-regions-ontology-adapter
  # @key image.tag Container image tag. If not set, a tag is generated using the appVersion
  tag: ""
  # @key image.pullPolicy Container image pull policy
  pullPolicy: IfNotPresent
  # @key image.pullSecrets Specify registry secret names as an array
  pullSecrets: []

# @section Common Parameters
# @key imagePullSecrets Global Docker registry secret names as an array
imagePullSecrets: []
# @key nameOverride String to partially override fullname (will maintain the release name)
nameOverride: ""
# @key fullnameOverride String to fully override the generated release name
fullnameOverride: ""

# @section Job settings
job:
  # @key job.activeDeadlineSeconds Maximum time in seconds a job can run
  activeDeadlineSeconds: 100
  # @key job.backoffLimit Number of retries before marking this job as failed
  backoffLimit: 3
  # @key job.completions Number of successful completions before marking this job as complete
  completions: 1
  # @key job.parallelism Maximum number of pods that can run in parallel
  parallelism: 1
  # @key job.ttlSecondsAfterFinished Time to live (in seconds) for finished jobs before automatic cleanup
  ttlSecondsAfterFinished: 100

# @section Service Account Parameters
serviceAccount:
  # @key serviceAccount.create Specifies whether a service account should be created
  create: true
  # @key serviceAccount.automount Automatically mount a ServiceAccount's API credentials?
  automount: true
  # @key serviceAccount.annotations Additional custom annotations for the ServiceAccount
  annotations: {}
  # @key serviceAccount.name Name of the ServiceAccount to use. If not set and create is true, a name is generated using the fullname template
  # If not set and create is true, a name is generated using the fullname template
  name: ""

# @section Pod Parameters
# @key podAnnotations Additional custom annotations for pods
# For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
podAnnotations: {}
# @key podLabels Additional custom labels for pods
# For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
podLabels: {}

# @key podSecurityContext Set pods' Security Context
podSecurityContext: {}
  # fsGroup: 2000

# @key securityContext Set containers' Security Context
securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

# @section Resource Parameters
# @key resources Set containers' resource requests and limits
resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

# @section Autoscaling Parameters
autoscaling:
  # @key autoscaling.enabled Enable Horizontal Pod Autoscaler
  enabled: false
  # @key autoscaling.minReplicas Minimum number of replicas
  minReplicas: 1
  # @key autoscaling.maxReplicas Maximum number of replicas
  maxReplicas: 100
  # @key autoscaling.targetCPUUtilizationPercentage Target CPU utilization percentage
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

# @section Volume Parameters
# @key volumes Additional volumes on the output Deployment definition
volumes: []
# - name: foo
#   secret:
#     secretName: mysecret
#     optional: false

# @key volumeMounts Additional volumeMounts on the output Deployment definition
volumeMounts: []
# - name: foo
#   mountPath: "/etc/foo"
#   readOnly: true

# @section Node Selection Parameters
# @key nodeSelector Node labels for pods assignment
nodeSelector: {}

# @key tolerations Tolerations for pods assignment
tolerations: []

# @key affinity Affinity for pods assignment
affinity: {}

# @section Configuration Parameters
# @descStart
# Contains configuration parameters specific to the application
# @descEnd
configuration:
  # @key configuration.targetTopic Kafka topic to publish ontology data to
  targetTopic: "ontology"
  # @key configuration.sourceName Source name or identifier for the data
  sourceName: "ies-ies-regions.generation.iso3166_ontology"
