# Copyright (C) 2025 Telicent Limited
# Telicent Spatial stand-alone chart

# @key enabled Enable Spatial chart
enabled: false

# @section Global Parameters
# @descStart
# Contains global parameters, these parameters are mirrored within the Telicent core umbrella chart
# @descEnd

global:
  ## Current available global image parameters: imageRegistry and imagePullSecrets
  ## Please, note that this will override the image parameters
  # @key global.imageRegistry Global image registry
  imageRegistry: ""
  # E.g.
  # imagePullSecrets:
  #   - myRegistryKeySecretName
  # @key global.imagePullSecrets Global registry secret names as an array
  imagePullSecrets: []

  # @key global.enterprise Enable enterprise mode, adding additional features and configurations
  enterprise: false

  # @key global.appHostDomain Domain associated with Telicent application services
  appHostDomain: ""
  # @key global.apiHostDomain Domain associated with Telicent Api services
  apiHostDomain: ""
  # @key global.authHostDomain Domain associated with Telicent authentication services, including OIDC providers
  authHostDomain: ""
  # @key global.groupsClaim Key used to retrieve groups from the OIDC provider
  groupsClaim: "groups"
  # @key global.jwksUrl Endpoint exposing multiple public keys represented as JWKs (JSON Web Key Set)
  # Note: For Dex the endpoint would be https://{yourDexDomain}/keys
  jwksUrl: "https://{yourAuthdomain}/.well-known/jwks.json"

  # @key global.istioNamespace Namespace in which Istio is deployed
  # Note: By default, Istio namespace is set to 'istio-system'
  istioNamespace: istio-system
  # @key global.istioServiceAccountName Name of the Istio service account
  istioServiceAccountName: istio-ingress
  # @key global.istioGatewayName Name of the Istio Gateway Resource (LB operating at the edge of the mesh)
  istioGatewayName: ingress-gateway
  # @key global.istioVirtualServiceEnabled Enable Istio traffic routing to a named destination service
  istioVirtualServiceEnabled: true

  kafka:
    # @key global.kafka.bootstrapServers Comma separated list containing Kafka bootstrap servers
    bootstrapServers: "kafka-bootstrap.kafka.svc.cluster.local:9092"
    # @key global.kafka.existingConfigSecretName Name of an existing secret containing Kafka configuration (preferred over individual settings below for security)
    existingConfigSecretName: ""
    # @key global.kafka.username Username for Kafka authentication
    username: "your.kafka.username.here"
    # @key global.kafka.password Password for Kafka authentication
    password: "your.kafka.password.here"
    # @key global.kafka.protocol Protocol used for Kafka communication
    protocol: "SASL_SSL"
    # @key global.kafka.mechanism SASL mechanism used for Kafka authentication
    mechanism: "SCRAM-SHA-512"

  truststore:
    # @key global.truststore.existingSecretName Name of an existing secret containing the truststore
    existingSecretName: ""
    # @key global.truststore.mountPath The mount path for the truststore in the container
    mountPath: /app/config/truststore

# @section configuration
# @descStart
# Application specific configuration settings
# @descEnd
configuration:
  # @key configuration.sourceTopic source topic from which to pull data
  sourceTopic: geo

# @section PostgreSQL
# @descStart
# Note: It is recommended to use a Kubernetes secret for sensitive information like passwords
# @descEnd
postgres:
  # @key postgres.uri PostgreSQL connection URL
  uri: ""
  # @key postgres.username PostgreSQL username
  username: ""
  # @key postgres.password PostgreSQL password
  password: ""
  # @key postgres.db PostgreSQL Database name
  db: ""
  # @key postgres.existingSecret Name of an existing secret resource containing the PostgreSQL password. If specified, existing secret must contain data for POSTGRES_PASSWORD, and the value for postgres.password will be ignored
  existingSecret: ""

# @section image This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
image:
  # @key image.registry Auth server image registry
  registry: quay.io
  # @key image.repository Auth server image name
  repository: 098669589541.dkr.ecr.eu-west-2.amazonaws.com/telicent-smart-cache-spatial-api # This sets the pull policy for images.
  # @key image.pullPolicy Auth server image pull policy
  pullPolicy: IfNotPresent
  # @key image.tag Auth server image tag. If not set, a tag is generated using the appVersion
  tag: ""
  # @key image.pullSecrets Specify registry secret names as an array
  pullSecrets: []

# @section Deployment Parameters For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
# @key podAnnotations Add extra annotations to the Deployment object
podAnnotations: {}
# @key extraEnvs List of additional environment variables to set in the pod
extraEnvs: []

podSecurityContext:
  # @key podSecurityContext.runAsUser Set the provisioning pod's Security Context runAsUser User ID
  runAsUser: 185
  # @key podSecurityContext.runAsGroup Set the provisioning pod's Security Context runAsGroup Group ID
  runAsGroup: 185
  # @key podSecurityContext.runAsNonRoot Set the provisioning pod's Security Context runAsNonRoot
  runAsNonRoot: true
  # @key podSecurityContext.fsGroup Set the provisioning pod's Group ID for the mounted volumes' filesystem
  fsGroup: 185
  seccompProfile:
    # @key podSecurityContext.seccompProfile.type Set the provisioning pod's Security Context seccomp profile
    type: RuntimeDefault

containerSecurityContext:
  # @key containerSecurityContext.runAsUser Set containers' Security Context runAsUser User ID
  runAsUser: 185
  # @key containerSecurityContext.runAsGroup Set containers' Security Context runAsGroup Group ID
  runAsGroup: 185
  # @key containerSecurityContext.runAsNonRoot Set container's Security Context runAsNonRoot
  runAsNonRoot: true
  # @key containerSecurityContext.allowPrivilegeEscalation Set container's Security Context allowPrivilegeEscalation
  allowPrivilegeEscalation: false
  capabilities:
    # @key containerSecurityContext.capabilities.drop List of capabilities to be dropped
    drop:
      - ALL
  seccompProfile:
    # @key containerSecurityContext.seccompProfile.type Set container's Security Context seccomp profile
    type: RuntimeDefault

# @section Traffic Exposure Parameters
service:
  # @key service.port Auth server service port
  port: 8080
  # @key service.type Auth server service port
  type: ClusterIP

resources:
  requests:
    # @key resources.requests.cpu Set containers' CPU request
    cpu: "1000m"
    # @key resources.requests.memory Set containers' memory request
    memory: "4000Mi"
  limits:
    # @key resources.limits.cpu Set containers' CPU limit
    cpu: "2000m"
    # @key resources.limits.memory Set containers' memory limit
    memory: "8000Mi"

# # @section
# # @descStart
# # Probes This is to setup the liveness and readiness probes, more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/
# # @descEnd
# livenessProbe:
#   httpGet:
#     # @key livenessProbe.httpGet.path The path to use for the Auth server liveness probe
#     path: /readiness
#     # @key livenessProbe.httpGet.port The port to use for the Auth server liveness probe
#     port: http
# readinessProbe:
#   httpGet:
#     # @key readinessProbe.httpGet.path The path to use for the Auth server liveness probe
#     path: /readiness
#     # @key readinessProbe.httpGet.port The port to use for the Auth server liveness probe
#     port: http

# @section Node Selection
# @key nodeSelector Allows you to schedule pods on a node with a label matching the given key-value pair.
nodeSelector: {}
# @key affinity Allows you to define affinity rules for scheduling pods, see: https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/
affinity: {}
# @key tolerations ALlows you to schedule pods on nodes with specified taints, see: https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/
tolerations: []

#
# @section Service Account Parameters
#
serviceAccount:
  # @key serviceAccount.create Specifies whether a service account should be created
  create: true
  # @key serviceAccount.name Name of the ServiceAccount to use. If not set, a name is generated using the fullname
  name: ""
  # @key serviceAccount.annotations Additional custom annotations for the ServiceAccount
  annotations: {}
  # @key serviceAccount.automount Automatically mount a ServiceAccount's API credentials
  automount: true

#
# @section Host(s) Core Parameters - Contains host information for applications deployed via *telicent-core* chart
#
# @descStart
# *Paperback Writer* interacts with applications deployed via *telicent-core* using their default service/serviceAccount and port.
# If either of those details changes, you can use this section to correctly refer to those applications.
# @descEnd
hostsCore:
  # @key hostsCore.enableAutoCorrect Prefix 'global.releaseNameTelicentCore' value to each host value. Alternatively, the host value will be used as it is, without any modification
  enableAutoCorrect: true
  # @key hostsCore.traefikProxy Traefik Proxy application default host value, as defined by 'service/serviceAccount:port'
  traefikProxy: "traefik-proxy:8080"
  # @key hostsCore.auth Auth application default host value, as defined by 'service/serviceAccount:port'
  auth: "auth:8080"
  # @key hostsCore.graph Graph application host value, as defined by 'service/serviceAccount:port'
  graph: "graph:8080"
