apiVersion: v1
items:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"labels":{"app.kubernetes.io/instance":"release-name","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/name":"access","app.kubernetes.io/version":"1.5.17","helm.sh/chart":"access-0.1.2","telicent.io/resource":"true"},"name":"release-name-access","namespace":"default"}}
    labels:
      app.kubernetes.io/instance: release-name
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: access
      app.kubernetes.io/version: 1.5.17
      helm.sh/chart: access-0.1.2
      telicent.io/resource: "true"
    name: release-name-access
    namespace: default
- apiVersion: v1
  data:
    MONGO_PWD: ""
  kind: Secret
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","data":{"MONGO_PWD":""},"kind":"Secret","metadata":{"annotations":{},"labels":{"app.kubernetes.io/instance":"release-name","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/name":"access","app.kubernetes.io/version":"1.5.17","helm.sh/chart":"access-0.1.2","telicent.io/resource":"true"},"name":"release-name-access-env","namespace":"default"},"type":"Opaque"}
    labels:
      app.kubernetes.io/instance: release-name
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: access
      app.kubernetes.io/version: 1.5.17
      helm.sh/chart: access-0.1.2
      telicent.io/resource: "true"
    name: release-name-access-env
    namespace: default
  type: Opaque
- apiVersion: v1
  data:
    DEBUG: "true"
    DEPLOYED_DOMAIN: https://apps.telicent.io
    MONGO_COLLECTION: access
    MONGO_CONNECTION_STRING_OPTIONS: authMechanism=SCRAM-SHA-1&retryWrites=false
    MONGO_RETRY_REWRITES: "false"
    MONGO_URL: mongodb://example.mongodb.net
    MONGO_USER: root
    OPENID_PROVIDER_URL: https://oidc.example.com
    PORT: "8080"
    SCIM_ENABLED: "true"
  kind: ConfigMap
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","data":{"DEBUG":"true","DEPLOYED_DOMAIN":"https://apps.telicent.io","MONGO_COLLECTION":"access","MONGO_CONNECTION_STRING_OPTIONS":"authMechanism=SCRAM-SHA-1\u0026retryWrites=false","MONGO_RETRY_REWRITES":"false","MONGO_URL":"mongodb://example.mongodb.net","MONGO_USER":"root","OPENID_PROVIDER_URL":"https://oidc.example.com","PORT":"8080","SCIM_ENABLED":"true"},"kind":"ConfigMap","metadata":{"annotations":{},"labels":{"app.kubernetes.io/instance":"release-name","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/name":"access","app.kubernetes.io/version":"1.5.17","helm.sh/chart":"access-0.1.2","telicent.io/resource":"true"},"name":"release-name-access-env","namespace":"default"}}
    labels:
      app.kubernetes.io/instance: release-name
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: access
      app.kubernetes.io/version: 1.5.17
      helm.sh/chart: access-0.1.2
      telicent.io/resource: "true"
    name: release-name-access-env
    namespace: default
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"access","app.kubernetes.io/instance":"release-name","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/name":"access","app.kubernetes.io/version":"1.5.17","helm.sh/chart":"access-0.1.2","telicent.io/resource":"true"},"name":"release-name-access","namespace":"default"},"spec":{"ports":[{"appProtocol":"http","name":"http","port":8080,"protocol":"TCP","targetPort":8080}],"selector":{"app.kubernetes.io/instance":"release-name","app.kubernetes.io/name":"access"},"type":"ClusterIP"}}
    labels:
      app: access
      app.kubernetes.io/instance: release-name
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: access
      app.kubernetes.io/version: 1.5.17
      helm.sh/chart: access-0.1.2
      telicent.io/resource: "true"
    name: release-name-access
    namespace: default
  spec:
    ports:
    - appProtocol: http
      name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app.kubernetes.io/instance: release-name
      app.kubernetes.io/name: access
    type: ClusterIP
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app.kubernetes.io/instance":"release-name","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/name":"access","app.kubernetes.io/version":"1.5.17","helm.sh/chart":"access-0.1.2","telicent.io/resource":"true"},"name":"release-name-access","namespace":"default"},"spec":{"replicas":1,"revisionHistoryLimit":5,"selector":{"matchLabels":{"app.kubernetes.io/instance":"release-name","app.kubernetes.io/name":"access"}},"strategy":{"rollingUpdate":{"maxSurge":1,"maxUnavailable":0},"type":"RollingUpdate"},"template":{"metadata":{"labels":{"app.kubernetes.io/instance":"release-name","app.kubernetes.io/name":"access"}},"spec":{"containers":[{"envFrom":[{"configMapRef":{"name":"release-name-access-env"}},{"secretRef":{"name":"release-name-access-env"}}],"image":"quay.io/telicent/telicent-access-api:1.5.17","imagePullPolicy":"IfNotPresent","name":"access","ports":[{"containerPort":8080,"name":"http","protocol":"TCP"}],"resources":{"limits":{"cpu":"350m","memory":"768Mi"},"requests":{"cpu":"250m","memory":"512Mi"}},"securityContext":{"allowPrivilegeEscalation":false,"capabilities":{"drop":["ALL"]},"runAsGroup":185,"runAsNonRoot":true,"runAsUser":185,"seccompProfile":{"type":"RuntimeDefault"}},"volumeMounts":null}],"securityContext":{"fsGroup":185,"runAsGroup":185,"runAsNonRoot":true,"runAsUser":185,"seccompProfile":{"type":"RuntimeDefault"}},"serviceAccountName":"release-name-access","volumes":null}}}}
    labels:
      app.kubernetes.io/instance: release-name
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: access
      app.kubernetes.io/version: 1.5.17
      helm.sh/chart: access-0.1.2
      telicent.io/resource: "true"
    name: release-name-access
    namespace: default
  spec:
    replicas: 1
    revisionHistoryLimit: 5
    selector:
      matchLabels:
        app.kubernetes.io/instance: release-name
        app.kubernetes.io/name: access
    strategy:
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 0
      type: RollingUpdate
    template:
      metadata:
        labels:
          app.kubernetes.io/instance: release-name
          app.kubernetes.io/name: access
      spec:
        containers:
        - envFrom:
          - configMapRef:
              name: release-name-access-env
          - secretRef:
              name: release-name-access-env
          image: quay.io/telicent/telicent-access-api:1.5.17
          imagePullPolicy: IfNotPresent
          name: access
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
          resources:
            limits:
              cpu: 350m
              memory: 768Mi
            requests:
              cpu: 250m
              memory: 512Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            runAsGroup: 185
            runAsNonRoot: true
            runAsUser: 185
            seccompProfile:
              type: RuntimeDefault
        securityContext:
          fsGroup: 185
          runAsGroup: 185
          runAsNonRoot: true
          runAsUser: 185
          seccompProfile:
            type: RuntimeDefault
        serviceAccountName: release-name-access
- apiVersion: security.istio.io/v1
  kind: AuthorizationPolicy
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"security.istio.io/v1","kind":"AuthorizationPolicy","metadata":{"annotations":{},"labels":{"app.kubernetes.io/instance":"release-name","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/name":"access","app.kubernetes.io/version":"1.5.17","helm.sh/chart":"access-0.1.2","telicent.io/resource":"true"},"name":"release-name-access-ingress","namespace":"default"},"spec":{"action":"ALLOW","rules":[{"from":[{"source":{"principals":["cluster.local/ns/istio-system/sa/istio-ingress"]}}],"to":[{"operation":{"methods":["GET","POST","DELETE","PUT","PATCH"]}}],"when":[{"key":"request.auth.claims[groups]","values":["tc_admin"]}]},{"from":[{"source":{"principals":["cluster.local/ns/istio-system/sa/istio-ingress"]}}],"to":[{"operation":{"methods":["GET"],"paths":["/whoami"]}}],"when":[{"key":"request.auth.claims[groups]","values":["tc_read"]}]}],"selector":{"matchLabels":{"app.kubernetes.io/instance":"release-name","app.kubernetes.io/name":"access"}}}}
    labels:
      app.kubernetes.io/instance: release-name
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: access
      app.kubernetes.io/version: 1.5.17
      helm.sh/chart: access-0.1.2
      telicent.io/resource: "true"
    name: release-name-access-ingress
    namespace: default
  spec:
    action: ALLOW
    rules:
    - from:
      - source:
          principals:
          - cluster.local/ns/istio-system/sa/istio-ingress
      to:
      - operation:
          methods:
          - GET
          - POST
          - DELETE
          - PUT
          - PATCH
      when:
      - key: request.auth.claims[groups]
        values:
        - tc_admin
    - from:
      - source:
          principals:
          - cluster.local/ns/istio-system/sa/istio-ingress
      to:
      - operation:
          methods:
          - GET
          paths:
          - /whoami
      when:
      - key: request.auth.claims[groups]
        values:
        - tc_read
    selector:
      matchLabels:
        app.kubernetes.io/instance: release-name
        app.kubernetes.io/name: access
- apiVersion: security.istio.io/v1
  kind: AuthorizationPolicy
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"security.istio.io/v1","kind":"AuthorizationPolicy","metadata":{"annotations":{},"labels":{"app.kubernetes.io/instance":"release-name","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/name":"access","app.kubernetes.io/version":"1.5.17","helm.sh/chart":"access-0.1.2","telicent.io/resource":"true"},"name":"release-name-access-internal-ingress","namespace":"default"},"spec":{"action":"ALLOW","rules":[{"from":[{"source":{"principals":["cluster.local/ns/default/sa/smart-cache-graph","cluster.local/ns/default/sa/smart-cache-search-api"]}}],"to":[{"operation":{"methods":["GET"]}}]}],"selector":{"matchLabels":{"app.kubernetes.io/instance":"release-name","app.kubernetes.io/name":"access"}}}}
    labels:
      app.kubernetes.io/instance: release-name
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: access
      app.kubernetes.io/version: 1.5.17
      helm.sh/chart: access-0.1.2
      telicent.io/resource: "true"
    name: release-name-access-internal-ingress
    namespace: default
  spec:
    action: ALLOW
    rules:
    - from:
      - source:
          principals:
          - cluster.local/ns/default/sa/smart-cache-graph
          - cluster.local/ns/default/sa/smart-cache-search-api
      to:
      - operation:
          methods:
          - GET
    selector:
      matchLabels:
        app.kubernetes.io/instance: release-name
        app.kubernetes.io/name: access
- apiVersion: networking.istio.io/v1alpha3
  kind: VirtualService
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"networking.istio.io/v1alpha3","kind":"VirtualService","metadata":{"annotations":{},"labels":{"app.kubernetes.io/instance":"release-name","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/name":"access","app.kubernetes.io/version":"1.5.17","helm.sh/chart":"access-0.1.2","telicent.io/resource":"true"},"name":"release-name-access","namespace":"default"},"spec":{"gateways":["istio-system/ingress-gateway"],"hosts":["apps.telicent.io"],"http":[{"match":[{"uri":{"prefix":"/api/access"}}],"rewrite":{"uriRegexRewrite":{"match":"^/api/access(/|$)(.*)","rewrite":"/\\2"}},"route":[{"destination":{"host":"release-name-access","port":{"number":8080}}}]}]}}
    labels:
      app.kubernetes.io/instance: release-name
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: access
      app.kubernetes.io/version: 1.5.17
      helm.sh/chart: access-0.1.2
      telicent.io/resource: "true"
    name: release-name-access
    namespace: default
  spec:
    gateways:
    - istio-system/ingress-gateway
    hosts:
    - apps.telicent.io
    http:
    - match:
      - uri:
          prefix: /api/access
      rewrite:
        uriRegexRewrite:
          match: ^/api/access(/|$)(.*)
          rewrite: /\2
      route:
      - destination:
          host: release-name-access
          port:
            number: 8080
kind: List
metadata: {}
