kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: uksc-odyssey-dev-keycloak
  namespace: uksc-odyssey-dev-sys
  annotations:
    argocd.argoproj.io/sync-options: Delete=false
data:
  KC_BOOTSTRAP_ADMIN_USERNAME: YWRtaW4=
  KC_BOOTSTRAP_ADMIN_PASSWORD: WVIya04zVmRLOFdWY2psMw==
