global:
  enterprise: true
  appHostDomain: "apps.system-release.qa.telicent.live"
  authHostDomain: "auth.system-release.qa.telicent.live"
  jwksUrl: "https://auth.system-release.qa.telicent.live/keys"
  kafka:
    existingConfigSecretName: "kafka-auth-config"
    bootstrapServers: "b-1.systemreleasemskcluste.t4s7ks.c2.kafka.eu-west-2.amazonaws.com:9096,b-2.systemreleasemskcluste.t4s7ks.c2.kafka.eu-west-2.amazonaws.com:9096,b-3.systemreleasemskcluste.t4s7ks.c2.kafka.eu-west-2.amazonaws.com:9096"
  imagePullSecrets:
    - name: "tc-auth-docker-quay-qa"
  jobServiceAccountName: producers
  existingTruststoreSecretName: ""
  istioGatewayName: ingress-gateway

kafkaTopics:
  enabled: false

  topics: []
