apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: {{ include "data-catalog-ui.fullname" . }}
  labels:
  {{ include "data-catalog-ui.labels" . | nindent 4 }}
spec:
  action: ALLOW
  rules:
  - from:
    - source:
        principals:
        - {{ include "data-catalog-ui.ingressPrincipal" . }}
    to:
    - operation:
        methods:
        - GET
  selector:
    matchLabels:
    {{ include "data-catalog-ui.selectorLabels" . | nindent 6 }}
