{{- /*
Copyright (C) 2026 Telicent Limited
*/}}
{{- if and .Values.enabled (not .Values.configMap.existingEnvConfigMap) -}}
apiVersion: v1
kind: ConfigMap

metadata:
  name: {{ include "notifications-projector.envConfigMapName" . }}
  namespace: {{ include "notifications-projector.namespace" . | quote }}
  labels:
    {{- include "notifications-projector.labels" . | nindent 4 }}

data:
  BOOTSTRAP_SERVERS: {{ .Values.global.kafka.bootstrapServers | quote }}
  KAFKA_CONFIG_FILE_PATH: /app/config/kafka-auth/kafka-config.properties
  INPUT_TOPIC: {{ .Values.notificationsProjector.topics.inputTopic | quote }}
  DLQ_TOPIC: {{ .Values.notificationsProjector.topics.dlqTopic | quote }}

  DATABASE_JDBC_URL: {{ .Values.postgres.jdbcUrl | quote }}

  {{- if .Values.validation.enabled }}
  ENABLE_VALIDATION: {{ .Values.validation.enabled | quote }}
  REGISTRY_HOSTNAME: {{ .Values.validation.registry.hostname | quote }}
  REGISTRY_PORT: {{ .Values.validation.registry.port | quote }}
  {{- end }}

  {{- if .Values.metrics.enabled }}
  OTEL_METRICS_EXPORTER: "prometheus"
  OTEL_TRACES_EXPORTER: "none"
  OTEL_LOGS_EXPORTER: "none"
  {{- end }}
{{- end }}
