{{- /*
Copyright (C) 2025 Telicent Limited
*/}}
{{- if not .Values.mongo.existingSecret -}}
apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth

metadata:
  name: {{ include "user-preferences.mongoSecretName" . }}
  namespace: {{ include "user-preferences.namespace" . | quote }}
  labels:
    {{- include "user-preferences.labels" . | nindent 4 }}

data:
  username: {{ .Values.mongo.username | b64enc | quote }}
  password: {{ .Values.mongo.password | b64enc | quote }}
{{- end -}}
