{{- /*
Copyright (C) 2025 Telicent Limited
*/}}

apiVersion: v1
kind: ServiceAccount

metadata:
  name: {{ include "user-preferences.serviceAccountName" . -}}
  labels:
    {{- include "user-preferences.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
