# @section Global Configuration
global:
  # @key global.namespace The namespace in which the should be created.
  namespace: istio-system
  # @key global.tenantName The tenant name to apply to the gateway.
  tenantName: ""
  # @key global.idpHost The IDP hostname to use in the gateway.
  idpHost: ""

# @section Authentication Gateway Configuration
# @key enabled Whether the Authentication Gateway prerequisite should be installed.
enabled: true
# @key nameOverride String to partially override fullname (will maintain the release name).
nameOverride: ""
# @key fullnameOverride String to fully override the generated release name.
fullnameOverride: ""
# @key namespace The namespace in which to deploy OpenSearch. If not set, defaults to the release namespace.
namespace: ""

# @section TLS Configuration
tls:
  # @key tls.existingCredentialName The name of an existing secret containing TLS credentials.
  existingCredentialName: ""
  # @key tls.key The TLS key to apply to a secret. Ignored when `tls.existingCredentialName` is set.
  key: ""
  # @key tls.crt The TLS crt to apply to a secret. Ignored when `tls.existingCredentialName` is set.
  crt: ""

# @section Ingress Configuration
ingressSelectors:
  # @key ingressSelectors.istio The Istio ingress selector label to target.
  istio: ingress
