nameOverride: ""
fullnameOverride: ""
jobs:
  ontology-rdf:
    serviceAccountName: producers
    kafkaAuthSecretName: kafka-auth-config
    image:
      pullPolicy: IfNotPresent
      repository: 098669589541.dkr.ecr.eu-west-2.amazonaws.com/telicent-ontologies-rdf-rdfs-owl-producer
      tag: "0.1.8"
    config:
      - name: BOOTSTRAP_SERVERS
        value: bootstrap-servers.override.required
      - name: TARGET_TOPIC
        value: ontology
      - name: PRODUCER_NAME
        value: ies-ontology-producer
      - name: SOURCE_NAME
        value: ies-ontology
      - name: KAFKA_CONFIG_MODE
        value: basic
    resources: {}
  ontology-ies:
    serviceAccountName: producers
    kafkaAuthSecretName: kafka-auth-config
    image:
      pullPolicy: IfNotPresent
      repository: 098669589541.dkr.ecr.eu-west-2.amazonaws.com/telicent-ies-ontology-producer
      tag: "0.2.0"
    config:
      - name: BOOTSTRAP_SERVERS
        value: bootstrap-servers.override.required
      - name: TARGET_TOPIC
        value: ontology
      - name: PRODUCER_NAME
        value: ies-ontology-producer
      - name: SOURCE_NAME
        value: ies-ontology
      - name: KAFKA_CONFIG_MODE
        value: basic
    resources: {}
  ies-regions:
    serviceAccountName: producers
    kafkaAuthSecretName: kafka-auth-config
    image:
      pullPolicy: IfNotPresent
      repository: 098669589541.dkr.ecr.eu-west-2.amazonaws.com/telicent-ies-regions-producer
      tag: "0.8.1"
    config:
      - name: BOOTSTRAP_SERVERS
        value: bootstrap-servers.override.required
      - name: TARGET_TOPIC
        value: knowledge
      - name: PRODUCER_NAME
        value: ies-regions-producer
      - name: SOURCE_NAME
        value: ies-regions-ttls
      - name: KAFKA_CONFIG_MODE
        value: basic
      - name: ADD_COMMENTS
        value: "True"
    resources: {}
  ontology-ies-regions:
    serviceAccountName: producers
    kafkaAuthSecretName: kafka-auth-config
    image:
      pullPolicy: IfNotPresent
      repository: 098669589541.dkr.ecr.eu-west-2.amazonaws.com/telicent-ies-regions-ontology-adapter
      tag: "0.8.1"
    config:
      - name: BOOTSTRAP_SERVERS
        value: bootstrap-servers.override.required
      - name: TARGET_TOPIC
        value: ontology
      - name: PRODUCER_NAME
        value: ies-regions-ontology-producer
      - name: SOURCE_NAME
        value: ies-ies-regions.generation.iso3166_ontology
      - name: KAFKA_CONFIG_MODE
        value: basic
    resources: {}
affinity: {}
annotations: {}
nodeSelector: {}
tolerations: []
serviceAccount:
  annotations: {}
  name: "producers"
# TODO is this okay out of the range? Presumably each job will need a kafka auth secret, why not share?
existingKafkaConfigSecret:
  name: kafka-auth-config
kafkaConfig: |-
  security.protocol=SASL_SSL
  sasl.mechanism=SCRAM-SHA-512
  sasl.jaas.config=org.apache.kafka.common.security.scram.ScramLoginModule required \
      username="your.kafka.username.here" \
      password="your.kafka.password.here";
