containerSecurityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  runAsGroup: 185
  runAsNonRoot: true
  runAsUser: 185
  seccompProfile:
    type: RuntimeDefault
fullnameOverride: ""

image:
  pullPolicy: Always
  repository: telicent/telicent-access
  # appVersion is used by default when defining an empty string
  tag: ""

nameOverride: ""
podSecurityContext:
  fsGroup: 185
  runAsGroup: 185
  runAsNonRoot: true
  runAsUser: 185
  seccompProfile:
    type: RuntimeDefault
replicas: 1
resources: {}
revisionHistoryLimit: 3
service:
  port: 8080
  type: ClusterIP
serviceAccount:
  annotations: {}
  name: ""

configuration:
  accessUiApiUrl: "https://your.host.here/api/access"
  signOutUrl: "https://your.host.here/logout"
