# configuration is for Telicent specific settings
# This section contains configuration options specific to the Telicent application.
# See: https://docs.telicent.com/en/latest/helm-charts/access-ui.html#configuration // TODO get proper link
# for full documentation
configuration:
  # accessUiApiUrl is the URL for the Access API
  accessUiApiUrl: "https://your.host.here/api/access"
  # signOutUrl is the URL for signing out
  signOutUrl: "https://your.host.here/logout"

# containerSecurityContext sets the container security context
containerSecurityContext:
  # allowPrivilegeEscalation prevents privilege escalation
  allowPrivilegeEscalation: false
  # capabilities sets the capabilities for the container
  capabilities:
    # drop all capabilities
    drop:
      - ALL
  # runAsGroup sets the group ID for the container
  runAsGroup: 185
  # runAsNonRoot ensures the container runs as a non-root user
  runAsNonRoot: true
  # runAsUser sets the user ID for the container
  runAsUser: 185
  # seccompProfile sets the seccomp profile for the container
  seccompProfile:
    # type defines the seccomp profile type
    # RuntimeDefault uses the default runtime seccomp profile
    type: RuntimeDefault

# fullnameOverride sets the full name of the chart
fullnameOverride: ""

# Image configuration
image:
  # imagePullSecrets is a list of secrets to use for pulling the image
  imagePullSecrets: []
  # pullPolicy defines the image pull policy
  pullPolicy: Always
  # repository is the Docker repository for the image
  repository: telicent/telicent-access
  # tag is the image tag to use
  tag: ""

# nameOverride sets a custom name for the chart it differs from fullnameOverride as it is not fully qualified
nameOverride: ""

# Pod security context
podSecurityContext:
  # fsGroup sets the filesystem group ID for the pod
  fsGroup: 185
  # runAsGroup sets the group ID for the pod
  runAsGroup: 185
  # runAsNonRoot ensures the pod runs as a non-root user
  runAsNonRoot: true
  # runAsUser sets the user ID for the pod
  runAsUser: 185
  # seccompProfile sets the seccomp profile for the pod
  seccompProfile:
    type: RuntimeDefault

# replicas sets the replica count
replicas: 1

# resources sets the resource requests and limits for the pod
resources: {}

# revisionHistoryLimit sets the number of old ReplicaSets to retain
revisionHistoryLimit: 3

# service configuration
service:
  # port is the port the service will listen on
  port: 8080
  # type defines the service type
  type: ClusterIP

# serviceAccount configuration
serviceAccount:
  # annotations are additional annotations for the service account
  annotations:
    {}
    # example.annotation/key: "value"
  # name is the name of the service account
  # If not set, the chart will generate a name based on the release name
  name: ""
