{{- /*
Copyright (C) 2025 Telicent Limited
*/}}

apiVersion: security.istio.io/v1
kind: AuthorizationPolicy

metadata:
  name: {{ include "smart-cache-graph.fullname" . }}-ingress
  labels:
  {{- include "smart-cache-graph.labels" . | nindent 4 }}

spec:
  action: ALLOW
  rules:
    - from:
        - source:
            principals:
            - {{ include "smart-cache-graph.ingressPrincipal" . }}
      to:
        - operation:
            methods:
              - GET
              - POST
            paths:
              - /knowledge/sparql
              - /knowledge/sparql/*
              - /knowledge/query
              - /knowledge/query/*
              - /ontology/sparql
              - /ontology/sparql/*
              - /ontology/query
              - /ontology/query/*
              - /catalog/sparql
              - /catalog/sparql/*
              - /catalog/query
              - /catalog/query/*
        - operation:
            methods:
              - POST
            paths:
              - /knowledge/graphql
              - /knowledge/graphql/*
              - /knowledge/shacl
              - /knowledge/shacl/*
      when:
        - key: request.auth.claims[groups]
          values:
            - tc_read
  selector:
    matchLabels:
    {{- include "smart-cache-graph.selectorLabels" . | nindent 6 }}
