apiVersion: v1
kind: ConfigMap
metadata:
    name: {{ include "smart-cache-graph.fullname" . }}
    labels:
        app.kubernetes.io/name: {{ include "smart-cache-graph.name" . }}
        helm.sh/chart: {{ include "smart-cache-graph.chart" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
    ATTRIBUTE_HIERARCHY_URL: {{ .Values.configuration.attributeHierarchyUrl | quote }}
    ENABLE_BACKUPS: "false"
    ENABLE_LABELS_QUERY: "false"
    JAVA_OPTIONS: {{ .Values.configuration.javaOptions | quote }}
    JWKS_URL: {{ .Values.global.jwksUrl | quote }}
    KAFKA_CONFIG_FILE_PATH: /app/config/kafka-auth/kafka-config.properties
    OTEL_METRICS_EXPORTER: {{ .Values.configuration.otelMetricsExporter | quote }}
    OTEL_TRACES_EXPORTER: {{ .Values.configuration.otelTracesExporter | quote }}
    {{- if .Values.global.enterprise}}
    SEARCH_API_URL: {{ include "smart-cache-graph.searchApiUrl" . | quote }}
    {{- end}}
    USER_ATTRIBUTES_URL: {{ .Values.configuration.userAttributesUrl | quote }}