apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "smart-cache-graph.fullname" . }}-server
  labels:
    {{- include "smart-cache-graph.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
    {{- include "smart-cache-graph.selectorLabels" . | nindent 6 }}
  updateStrategy: {}
  serviceName: ""
  template:
    metadata:
      annotations:
        prometheus.io/path: /
        prometheus.io/port: "9464"
        prometheus.io/scrape: "true"
      {{- range $key, $value := .Values.annotations }}
        {{ $key }}: {{ $value | quote }}
      {{- end }}
      labels:
        {{- include "smart-cache-graph.labels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
      - args:
          - --config
          - /fuseki/config/config.ttl
        envFrom:
        - secretRef:
            name: {{ include "smart-cache-graph.envSecretName" . }}
            optional: true
        - configMapRef:
            name: {{ include "smart-cache-graph.fullname" . }}
            optional: true
        image: {{ .Values.image.repository }}:{{ include "smart-cache-graph.version" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        livenessProbe:
          httpGet:
            path: /$/ping
            port: 3030
            scheme: HTTP
          initialDelaySeconds: 120
          periodSeconds: 30
          timeoutSeconds: 2
        name: graph-server
        ports:
        - containerPort: 3030
          name: http
          protocol: TCP
        - containerPort: {{ .Values.metrics.service.port }}
          name: {{ .Values.metrics.service.name | default "metrics" }}
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /$/ping
            port: 3030
            scheme: HTTP
          initialDelaySeconds: 120
          periodSeconds: 30
          timeoutSeconds: 2
        resources: {{- toYaml .Values.resources | nindent 10 }}
        securityContext: {{- toYaml .Values.containerSecurityContext |
          nindent 10 }}
        volumeMounts:
        - mountPath: /fuseki/config
          name: graph-config-volume
        - mountPath: /fuseki/databases
          name: datasets-volume
        - mountPath: /fuseki/backups
          name: backups-volume
        - mountPath: /app/config/kafka-auth/
          name: kafka-auth-config
      {{- if .Values.global.existingTruststoreSecretName }}
        - mountPath: /app/config/truststore/
          name: truststore-volume
      {{- end }}
      securityContext: {{- toYaml .Values.podSecurityContext | nindent 8 }}

      serviceAccountName: {{ include "smart-cache-graph.serviceAccountName" . }}
      volumes:
      - configMap:
          {{- if .Values.existingGraphConfigMapName }}
            name: {{ .Values.existingGraphConfigMapName }}
          {{- else }}
            name: {{ include "smart-cache-graph.serverConfig" . }}
          {{- end }}
        name: graph-config-volume
      - name: kafka-auth-config
        secret:
        {{- if .Values.global.existingKafkaConfigSecretName }}
          secretName: {{ .Values.global.existingKafkaConfigSecretName }}
        {{- else }}
          secretName: {{ include "telicent-core.kafkaAuthConfigSecretName" . }}
        {{- end }}
        # TODO: Secret is created outside of Helm by using Ansible. Would potentially need cert-manager to remove this dependency.

      {{- if .Values.global.existingTruststoreSecretName }}
      - name: truststore-volume
        secret:
          secretName: {{ .Values.global.existingTruststoreSecretName }}
          optional: true
      {{- end }}

  volumeClaimTemplates:
  - metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: {{ include "smart-cache-graph.name" . }}
        telicent.io/resource: "true"
      name: datasets-volume
    spec:
      accessModes:
      - ReadWriteOnce
      resources: 
        requests:
            storage: {{ .Values.persistentVolumeClaims.datasetsVolume.size }}
      storageClassName: {{ .Values.persistentVolumeClaims.datasetsVolume.storageClass }}
  - metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: {{ include "smart-cache-graph.name" . }}
        telicent.io/resource: "true"
      name: backups-volume
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
            storage: {{ .Values.persistentVolumeClaims.backupsVolume.size }}
      storageClassName: {{ .Values.persistentVolumeClaims.backupsVolume.storageClass }}
