# MongoDB configuration
mongo:
  url: "mongodb://example.mongodb.net"
  username: root
  password: "your.mongo.password.here"
  database: access
  connectionStringOptions: "authMechanism=SCRAM-SHA-1&retryWrites=false"
  retryRewrites: "false"
  # existingMongoPasswordSecret: telicent-access-db-password

# Configuration
config:
  # appsUrl is the host the API is being served from
  appsUrl: "https://example.com"
  # debug enables debug logging
  debug: true
  # openidProviderUrl is the URL of the OIDC provider
  openidProviderUrl: "https://oidc.example.com"
  # scimEnabled enables SCIM user management
  scimEnabled: true

# containerSecurityContext sets the container security context
containerSecurityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  runAsGroup: 185
  runAsNonRoot: true
  runAsUser: 185
  seccompProfile:
    type: RuntimeDefault

# existingConfigmap is the name of the existing configmap for configuration
existingConfigmap: "existing-configmap-name"

# existingSecret is the name of the existing secret for configuration
existingSecret: "existing-secret-name"

# existingCacertConfigmap is the name of the existing configmap for extra certificates
existingCacertConfigmap: "existing-cacert-configmap-name"

# fullnameOverride sets the full name of the chart
fullnameOverride: "custom-fullname"

# cacert is the path to the CA certificate file
cacert: "path/to/cacert.pem"

# Image configuration
image:
  # imagePullSecrets is a list of secrets to use for pulling the image
  imagePullSecrets: []
  # pullPolicy defines the image pull policy
  pullPolicy: Always
  # repository is the Docker repository for the image
  repository: telicent/telicent-access-api
  # tag is the image tag to use
  tag: "latest"

# Pod security context
podSecurityContext:
  # fsGroup sets the filesystem group ID for the pod
  fsGroup: 185
  # runAsGroup sets the group ID for the pod
  runAsGroup: 185
  # runAsNonRoot ensures the pod runs as a non-root user
  runAsNonRoot: true
  # runAsUser sets the user ID for the pod
  runAsUser: 185
  # seccompProfile sets the seccomp profile for the pod
  seccompProfile:
    type: RuntimeDefault

# replicas sets the replica count
replicas: 3

# resources sets the resource requests and limits for the pod
resources:
  # requests define the minimum resources required
  requests:
    # cpu is the minimum CPU required unit is milliCPU
    cpu: "500m"
    # memory is the minimum memory required
    memory: "512Mi"
  # limits define the maximum resources allowed
  limits:
    # cpu is the maximum CPU allowed unit is milliCPU
    cpu: "1"
    # memory is the maximum memory allowed
    memory: "1Gi"

# revisionHistoryLimit sets the number of old ReplicaSets to retain
revisionHistoryLimit: 5

# service configuration
service:
  # port is the port the service will listen on
  port: 8080
  # type defines the service type
  type: ClusterIP

# serviceAccount configuration
serviceAccount:
  # annotations are additional annotations for the service account
  annotations:
    {}
    # example.annotation/key: "value"
  # name is the name of the service account
  # If not set, the chart will generate a name based on the release name
  name: ""
