# MongoDB configuration
mongo:
  url: "mongodb://example.mongodb.net"
  username: root
  password: "your.mongo.password.here"
  database: access
  connectionStringOptions: "authMechanism=SCRAM-SHA-1&retryWrites=false"
  retryRewrites: "false"
  # existingMongoPasswordSecret: telicent-access-db-password

# Configuration
config:
  # The host the API is being served from
  appsUrl: "https://example.com"
  # Enable debug logging
  debug: true
  # The URL of the OIDC provider
  openidProviderUrl: "https://oidc.example.com"
  # Enable SCIM user management
  scimEnabled: true

# Container security context
containerSecurityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  runAsGroup: 185
  runAsNonRoot: true
  runAsUser: 185
  seccompProfile:
    type: RuntimeDefault

# Use existing configmap for configuration (config.* will be ignored)
existingConfigmap: "existing-configmap-name"

# Use existing secret for configuration (config.mongodbPassword will be ignored)
existingSecret: "existing-secret-name"

# Use existing configmap for extra certificates
existingCacertConfigmap: "existing-cacert-configmap-name"

# Override the full name of the chart
fullnameOverride: "custom-fullname"

# Configmap containing extra certificates to be trusted
cacert: "path/to/cacert.pem"

# Image configuration
image:
  pullPolicy: Always
  repository: telicent/telicent-access-api
  tag: "latest"

# Pod security context
podSecurityContext:
  fsGroup: 185
  runAsGroup: 185
  runAsNonRoot: true
  runAsUser: 185
  seccompProfile:
    type: RuntimeDefault

# Replica count
replicas: 3

# Resource requests and limits
resources:
  requests:
    cpu: "500m"
    memory: "512Mi"
  limits:
    cpu: "1"
    memory: "1Gi"

# Revision history limit
revisionHistoryLimit: 5

# Service configuration
service:
  port: 8080
  type: ClusterIP

# Service account configuration
serviceAccount:
  annotations:
    example.annotation/key: "value"
  name: "custom-service-account-name"
