# Default values for Telicent Access API Helm Chart

# global configuration
# This section contains global values that are used across the charts inherited from the telicent core umbrella chart, will override these values. These are included to allow this chart to be standalone.
global:
  # appHostDomain is the domain for the Telicent applications
  # This is used to construct URLs for the applications.
  appHostDomain: "apps.telicent.io"
  # authHostDomain is the domain for the Telicent authentication service
  # This is used for the OIDC provider and other authentication-related URLs.
  authHostDomain: "auth.telicent.io"

# configuration is for Telicent specific settings
# This section contains configuration options specific to the Telicent application.
# See: https://docs.telicent.io/en/latest/helm-charts/access-api.html#configuration // TODO get proper link
# for full documentation
configuration:
  # debug enables debug logging
  debug: true
  # openidProviderUrl is the URL of the OIDC provider
  openidProviderUrl: "https://oidc.example.com"
  # scimEnabled enables SCIM user management
  scimEnabled: true

# containerSecurityContext sets the container security context
containerSecurityContext:
  # allowPrivilegeEscalation prevents privilege escalation
  allowPrivilegeEscalation: false
  # capabilities sets the capabilities for the container
  capabilities:
    # drop all capabilities
    drop:
      - ALL
  # runAsGroup sets the group ID for the container
  runAsGroup: 185
  # runAsNonRoot ensures the container runs as a non-root user
  runAsNonRoot: true
  # runAsUser sets the user ID for the container
  runAsUser: 185
  # seccompProfile sets the seccomp profile for the container
  seccompProfile:
    # type defines the seccomp profile type
    # RuntimeDefault uses the default runtime seccomp profile
    type: RuntimeDefault

# existingConfigmap is the name of the existing configmap for configuration
existingConfigmap: ""

# existingCacertConfigmap is the name of the existing configmap for extra certificates
existingCacertConfigmap: ""

# fullnameOverride sets the full name of the chart
fullnameOverride: ""

# cacert is the path to the CA certificate file
cacert: ""

# Image configuration
image:
  # imagePullSecrets is a list of secrets to use for pulling the image
  imagePullSecrets: []
  # pullPolicy defines the image pull policy
  pullPolicy: Always
  # repository is the Docker repository for the image
  repository: telicent/telicent-access-api

  # appVersion is used by default when defining an empty string for tag
  # tag is the image tag to use
  tag: ""

# mongo configuration
mongo:
  # url is the MongoDB connection URL
  url: "mongodb://example.mongodb.net"
  # username is the MongoDB username
  username: root
  # password is the MongoDB password
  password: "your.mongo.password.here"
  # collection is the MongoDB collection to use
  collection: access
  # connectionStringOptions are additional options for the MongoDB connection string
  connectionStringOptions: "authMechanism=SCRAM-SHA-1&retryWrites=false"
  # retryRewrites enables or disables retryable writes
  retryRewrites: "false"
  # existingMongoPasswordSecret is the name of the existing secret containing the MongoDB password
  existingMongoPasswordSecret: ""

# Pod security context
podSecurityContext:
  # fsGroup sets the filesystem group ID for the pod
  fsGroup: 185
  # runAsGroup sets the group ID for the pod
  runAsGroup: 185
  # runAsNonRoot ensures the pod runs as a non-root user
  runAsNonRoot: true
  # runAsUser sets the user ID for the pod
  runAsUser: 185
  # seccompProfile sets the seccomp profile for the pod
  seccompProfile:
    type: RuntimeDefault

# replicas sets the replica count
replicas: 1

# resources sets the resource requests and limits for the pod
resources:
  # requests define the minimum resources required
  requests:
    # cpu is the minimum CPU required unit is milliCPU
    cpu: "500m"
    # memory is the minimum memory required
    memory: "512Mi"
  # limits define the maximum resources allowed
  limits:
    # cpu is the maximum CPU allowed unit is milliCPU
    cpu: "1"
    # memory is the maximum memory allowed
    memory: "1Gi"

# revisionHistoryLimit sets the number of old ReplicaSets to retain
revisionHistoryLimit: 5

# service configuration
service:
  # port is the port the service will listen on
  port: 8080
  # type defines the service type
  type: ClusterIP

# serviceAccount configuration
serviceAccount:
  # annotations are additional annotations for the service account
  annotations:
    {}
    # example.annotation/key: "value"
  # name is the name of the service account
  # If not set, the chart will generate a name based on the release name
  name: ""
