# Configmap containing extra certificates to be trusted
cacert: ""

# Configuration
config:
  # The host the api is being served from
  appsUrl: change.to.url.of.instance
  # Enable debug logging
  debug: false
  # MongoDB configuration
  mongoCollection: access
  mongodbPassword: change.to.mongodb.password
  mongodbUser: change.to.mongodb.username
  mongodbUrl: change.to.mongodb.url
  # The URL of the OIDC provider
  openidProviderUrl: change.to.oidc.provider.url
  # Enable SCIM user management
  scimEnabled: false

# Container security context
containerSecurityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  runAsGroup: 185
  runAsNonRoot: true
  runAsUser: 185
  seccompProfile:
    type: RuntimeDefault

# Use existing configmap for configuration (config.* will be ignored)
existingConfigmap: ""

# Use existing secret for configuration (config.mongodbPassword will be ignored)
# existingSecret: ""

existingCacertConfigmap: ""

fullnameOverride: ""

image:
  pullPolicy: Always
  repository: telicent/telicent-access-api
  tag: "1.5.6"

podSecurityContext:
  fsGroup: 185
  runAsGroup: 185
  runAsNonRoot: true
  runAsUser: 185
  seccompProfile:
    type: RuntimeDefault

replicas: 1

resources: {}

revisionHistoryLimit: 3

service:
  port: 8080
  type: ClusterIP

serviceAccount:
  annotations: {}
  name: ""
