
# Declare routers / services / middlewares
http:
  routers:
    ai-sparql-builder-api:
      rule: {{ printf "Host(`%s`) && PathPrefix(`/ai-sparql-builder-poc/api`)" .Values.global.appHostDomain }}
      service: ai-sparql-builder
      entryPoints:
        - web-app
      middleWares:
        - oauth2
        - path-ai-sparql-builder
        - host-ai-sparql-builder
      priority: 20

    ai-sparql-builder:
      rule: {{ printf "Host(`%s`) && PathPrefix(`/ai-sparql-builder-poc`)" .Values.global.appHostDomain }}
      service: ai-sparql-builder
      entryPoints:
        - web-app
      middleWares:
        - path-ai-sparql-builder
        - host-ai-sparql-builder
      priority: 10

  services:
    ai-sparql-builder:
      loadBalancer:
        servers:
          - url: "{{ printf "http://%s"  (include "traefik-proxy.hostAISparqlBuilder" .) }}"

  middlewares:
    path-ai-sparql-builder:
      replacePathRegex:
        regex: "^/ai-sparql-builder-poc/(.*)"
        replacement: "/$1"

    host-ai-sparql-builder:
      headers:
        customRequestHeaders:
          host: "{{ include "traefik-proxy.hostAISparqlBuilder" . }}"
