
# Declare routers / services / middlewares
http:
  routers:
    data-catalog-ui:
      rule: {{ printf "Host(`%s`) && PathPrefix(`/ai-sparql-builder-poc`)" .Values.global.appHostDomain }}
      service: ai-sparql-builder
      entryPoints:
        - web-app
      middleWares:
        - path-data-catalog-ui
        - host-data-catalog-ui

  services:
    ai-sparql-builder:
      loadBalancer:
        servers:
          - url: "{{ printf "http://%s"  (include "traefik-proxy.hostDataCatalogUi" .) }}"

  middlewares:
    path-data-catalog-ui:
      replacePathRegex:
        regex: "^/ai-sparql-builder(.*)"
        replacement: "/ai-sparql-builder/$1"

    host-data-catalog-ui:
      headers:
        customRequestHeaders:
          host: "{{ include "traefik-proxy.hostDataCatalogUi" . }}"
