# Declare routers / services / middlewares
http:
  routers:    
    search-ui:
      rule: {{ printf "Host(`%s`) && PathPrefix(`/search`)" .Values.global.appHostDomain }}
      service: search-ui
      entryPoints:
        - web-app
      middleWares:
        - path-search-ui
        - host-search-ui

  services:
    search-ui:
      loadBalancer:
        servers:
          - url: {{ printf "http://%s"  (include "traefik-proxy.hostSearchUi" .) }}

  middlewares:
    path-search-ui:
      replacePathRegex:
        regex: "^/search/?(.*)"
        replacement: "/search/$1"

    host-search-ui:
      headers:
        customRequestHeaders:
          host: {{ include "traefik-proxy.hostSearchUi" . }}
