# Declare routers / services / middlewares
{{- if .Values.dashboard.enabled }}
http:
  routers:
    dashboard:
      rule: {{ printf "Host(`%s`) && PathPrefix(`%s`)" ( .Values.dashboard.domain | default .Values.global.appHostDomain ) .Values.dashboard.basepath }}
      service: api@internal
      entryPoints:
        - web-app
{{- end }}
