{{- /*
Copyright (C) 2026 Telicent Limited
*/}}
{{- if .Values.enabled -}}
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy

metadata:
  name: {{ include "notifications.fullname" . }}-ingress
  labels:
  {{- include "notifications.labels" . | nindent 4 }}

spec:
  selector:
    matchLabels:
      {{- include "notifications.selectorLabels" . | nindent 6 }}
  action: ALLOW
  rules:
    - from:
        - source:
            principals:
              - {{ include "notifications.ingressPrincipal" . }}
      to:
        - operation:
            paths:
              - /notifications
              - /notifications/read
              - /notifications/read/*
              - /notifications/unread
              - /notifications/unread/*
            methods: ["GET","POST","PATCH"]
{{- end }}
