# Copyright (C) 2025 Telicent Limited
# Telicent *OAuth2 Proxy* stand-alone chart

#
# @section Global Parameters
#
# @descStart
# Contains global parameters, these parameters are mirrored within the Telicent core umbrella chart
# @descEnd
global:

  # Note: not supported as this is a third party application
  # imageRegistry: ""
  # imagePullSecrets: []

  # @key global.appHostDomain Domain associated with Telicent application/ui services
  appHostDomain: "apps.telicent.io"

  # @key global.authHostDomain Domain associated with Telicent authentication services, including OIDC providers
  authHostDomain: "auth.telicent.io"

  # @key global.istioIngressNamespace Namespace in which the Istio Ingress resource is deployed; overrides 'istio.ingress.namespace'
  istioIngressNamespace: istio-system
  # @key global.istioIngressServiceAccount ServiceAccount associated with Istio ingress deployment; overrides 'istio.ingress.serviceAccount'
  istioIngressServiceAccount: istio-ingress
  # @key global.istioGatewayNamespace Namespace in which the Istio Gateway resource is deployed; overrides 'istio.gateway.namespace'
  istioGatewayNamespace: istio-system
  # @key global.istioGatewayName Name of the Istio Gateway resource; overrides 'istio.gateway.namespace'
  istioGatewayName: ingress-gateway

#
# @section ConfigMap Parameters
#
configMap:
  # @key configMap.existingEnvConfigMap Name of existing configmap containing *Oauth2 Proxy* Environment Configuration
  # Note: When it's set, it will disable configmap creation.
  existingEnvConfigMap: ""

#
# @section OAuth Parameters
#
# @descStart
# Contains OAuth parameters used by the *OAuth2 Proxy* application
# @descEnd
oauth:
  # @key oauth.oidcIssuerUrl The OpenID Connect issuer URL
  oidcIssuerUrl: "your.host/realms/core"
  # @key oauth.redirectUrl OIDC redirect URL override. If not set, 'authHostDomain' + '/oauth2/callback' will be used
  redirectUrl: ""
  # Note: For more information on the below cookie values, please visit: https://oauth2-proxy.github.io/oauth2-proxy/configuration/overview/#cookie-options
  # @key oauth.cookieDomains Domains that the cookie is valid for. If not set, 'appHostDomain' will be used
  cookieDomains: ""
    # @key oauth.cookieWhiteListDomains Allowed domains for redirection after authentication. If not set, 'apphHostDomain' will be used
  cookieWhiteListDomains: ""
  # @key oauth.cookieExpire Expire timeframe for cookie
  cookieExpire: "50m"
  # @key oauth.cookieCsrfExpire Expire timeframe for CSRF cookie
  cookieCsrfExpire: "50m"
  # @key oauth.cookieRefresh Refresh the cookie after this duration
  cookieRefresh: "30m"

#
# @section Identity Provider (IDP) Parameters and Secret
#
# @descStart
# Contains details pertinent to the OIDC Identity Provider to be used by *Oauth2 Proxy*.
# It is recommended to store sensitive information including passwords in a Kubernetes secret and not in Helm values.
# For Quick Start purposes, a secret named `tc-auth-gen-idp-oauth2-proxy` will be created if one is not set.
# @descEnd
idp:
  # @key idp.issuerUrl The OpenID Connect issuer URL
  issuerUrl: ""
  # @key idp.jwksPath The path to use in combination with the issuer URL for JWKS
  jwksPath: "/keys"
  # @key idp.existingSecret Name of an existing secret. The secret must contain 3 keys: 'clientid', 'clientsecret', 'cookiesecret'
  # Note: Left unset, it will create a secret named: tc-auth-gen-idp-oauth2-proxy
  existingSecret: ""
  # @key idp.clientId The OAuth Client ID
  clientId: ""
  # @key idp.clientSecret The OAuth Client Secret
  clientSecret: ""
  # @key idp.cookieSecret The seed string for secure cookies
  cookieSecret: "" 

#
# @section TLS Parameters
#
# Allow for additional CA certificates that should be used when connecting to the provider. If not specified, the default Go trust sources are used instead.
# @descEnd
tls:
  ca:
   # @key tls.ca.existingSecret Name of an existing secret that contains CA certificate(s). The secret must contains 1 key: 'ca.crt' containing the CA certificate(s)
   # Note: When it's set it will disable secret creation.
   existingSecret: ""
   # @key tls.ca.existingConfigMap Name of an existing configmap that contains CA certificate(s). The configmap must contains 1 key: 'ca.crt' containing the CA certificate(s)
   existingConfigMap: ""
   # @key tls.ca.certificate The PEM-encoded certificate(s) of the CA (certificate authority)
   certificate: ""

#
# @section Common Parameters
#
# @key nameOverride String to partially override fullname (will maintain the release name)
nameOverride: ""
# @key fullnameOverride String to fully override the generated release name
fullnameOverride: ""
# @key namespaceOverride String to fully override all deployed resources namespace
namespaceOverride: ""
# @key commonLabels Add labels to all the deployed resources
commonLabels: {}

#
# @section Deployment Parameters
#
# @key replicas Number of *Ouath2 Proxy* replicas to deploy
replicas: 1
# @key revisionHistoryLimit Number of controller revisions to keep
revisionHistoryLimit: 5
# @key annotations Add extra annotations to the deployment object
annotations: {}
# @key podLabels Add extra labels to the *Oauth2 Proxy* pod
podLabels: {}
# @key podAnnotations Add extra annotations to the *Oauth2 Proxy* pod
podAnnotations: {}
# @key extraEnvVars Array with extra environment variables to add to *Oauth2 Proxy* pod
# Example:
# extraEnvVars:
# - name: FOO
#   value: instance
extraEnvVars: []
# @key extraVolumes Optionally specify extra list of additional volumes
extraVolumes: []
# @key extraVolumeMounts Optionally specify extra list of additional volumeMounts
extraVolumeMounts: []
# @key initContainers Add init containers to the pod
initContainers: []
# Example:
# sidecars:
# - name: your-image-name
#   image: your-image
#   ports:
#   - name: portname
#     containerPort: 1234
# @key sidecars Add sidecars to the pod
sidecars: []

image:
  # @key image.registry *Oauth2 Proxy* image registry
  registry: quay.io
  # @key image.repository *Oauth2 Proxy* image name
  repository: oauth2-proxy/oauth2-proxy
  # @key image.tag *Oauth2 Proxy* image tag. If not set, a tag is generated using the appVersion
  tag: ""
  # @key image.pullPolicy *Oauth2 Proxy* image pull policy
  pullPolicy: IfNotPresent
  # @key image.pullSecrets Specify registry secret names as an array
  pullSecrets: []

resources:
  requests:
    # @key resources.requests.cpu Set containers' CPU request
    cpu: "300m"
    # @key resources.requests.memory Set containers' memory request
    memory: "512Mi"
  limits:
    # @key resources.limits.cpu Set containers' CPU limit
    cpu: "500m"
    # @key resources.limits.memory Set containers' memory limit
    memory: "800Mi"

containerSecurityContext:
  # @key containerSecurityContext.runAsUser Set containers' Security Context runAsUser User ID
  runAsUser: 185
  # @key containerSecurityContext.runAsGroup Set containers' Security Context runAsGroup Group ID
  runAsGroup: 185
  # @key containerSecurityContext.runAsNonRoot Set container's Security Context runAsNonRoot
  runAsNonRoot: true
  # @key containerSecurityContext.allowPrivilegeEscalation Set container's Security Context allowPrivilegeEscalation
  allowPrivilegeEscalation: false
  capabilities:
    # @key containerSecurityContext.capabilities.drop List of capabilities to be dropped
    drop:
      - ALL
  seccompProfile:
    # @key containerSecurityContext.seccompProfile.type Set container's Security Context seccomp profile
    type: RuntimeDefault

podSecurityContext:
  # @key podSecurityContext.runAsUser Set the provisioning pod's Security Context runAsUser User ID
  runAsUser: 185
  # @key podSecurityContext.runAsGroup Set the provisioning pod's Security Context runAsGroup Group ID
  runAsGroup: 185
  # @key podSecurityContext.runAsNonRoot Set the provisioning pod's Security Context runAsNonRoot
  runAsNonRoot: true
  # @key podSecurityContext.fsGroup Set the provisioning pod's Group ID for the mounted volumes' filesystem
  fsGroup: 185
  seccompProfile:
    # @key podSecurityContext.seccompProfile.type Set the provisioning pod's Security Context seccomp profile
    type: RuntimeDefault

# @key affinity Affinity for pod assignment
# Ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
affinity: {}
# @key nodeSelector Node labels for pod assignment
# Ref: https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/
nodeSelector: {}
# @key tolerations Tolerations for pod assignment
# Ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
tolerations: []

#
# @section Service Account Parameters
#
serviceAccount:
  # @key serviceAccount.create Specifies whether a service account should be created
  create: true
  # @key serviceAccount.name Name of the ServiceAccount to use. If not set, a name is generated using the fullname
  name: ""
  # @key serviceAccount.annotations Additional custom annotations for the ServiceAccount
  annotations: {}
  # @key serviceAccount.automount Automatically mount a ServiceAccount's API credentials
  automount: true

#
# @section Traffic Exposure Parameters
#
service:
  # @key service.name *Oauth2 Proxy* service name. If not set, a name is generated using the fullname
  name: "oauth2-proxy"
  # @key service.port *Oauth2 Proxy* service port
  port: 4080
  # @key service.type *Oauth2 Proxy* service type
  type: ClusterIP

#
# @section Istio Parameters
#
istio:
  # istio Ingress resource (lookup: 'kubectl get deployment -l istio=ingress -n <ns>').
  ingress:
    # @key istio.ingress.namespace Namespace in which the Istio Ingress resource is deployed
    namespace: istio-system
    # @key istio.ingress.serviceAccount ServiceAccount associated with Istio ingress deployment
    serviceAccount: istio-ingress
  # istio Gateway resource (lookup: 'kubectl get gateway/<name> -n <ns>')
  gateway:
    # @key istio.gateway.namespace Namespace in which the Istio Gateway resource is deployed
    namespace: istio-system
    # @key istio.gateway.name Name of the Istio Gateway resource
    name: ingress-gateway
  virtualService:
    # @key istio.virtualService.enabled Enable Istio traffic into *OAuth2 Proxy*
    enabled: true
    # @key istio.virtualService.host Host associated with *Oauth2 Proxy* If not set, 'global.appHostDomain' will be used
    host: ""
    # @key istio.virtualService.extraHosts Additional hosts (excluding appHostDomain) to be managed by *OAuth2 Proxy*
    extraHosts: []
