{{- /*
Copyright (C) 2026 Telicent Limited
*/}}
{{- if .Values.enabled -}}
apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ include "catalogue-updater.fullname" . }}
  namespace: {{ include "document-pipeline.namespace" . | quote }}
  labels:
    {{- include "catalogue-updater.labels" . | nindent 4 }}
  {{- with .Values.catalogueUpdater.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}

spec:
  replicas: {{ .Values.catalogueUpdater.replicas}}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      {{- include "catalogue-updater.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
      {{- include "catalogue-updater.labels" . | nindent 8 }}
      {{- with .Values.catalogueUpdater.podLabels }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.catalogueUpdater.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    
    spec:
      {{- $metrics := .Values.metrics | default dict }}
      serviceAccountName: {{ include "document-pipeline.serviceAccountName" . }}
      securityContext: {{ .Values.catalogueUpdater.podSecurityContext | default .Values.podSecurityContext | toYaml | nindent 8 }}

      {{- $pullSecret := .Values.global.imagePullSecrets | default .Values.catalogueUpdater.image.pullSecrets }}
      {{- with $pullSecret }}
      imagePullSecrets:
        {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- if .Values.catalogueUpdater.initContainers }}
      initContainers:
      {{- with .Values.catalogueUpdater.initContainers }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}
        image: {{ include "catalogue-updater.image" . }}
        imagePullPolicy: {{ .Values.catalogueUpdater.image.pullPolicy }}
        resources: {{ .Values.catalogueUpdater.resources | default .Values.resources | toYaml | nindent 10 }}
        securityContext: {{ .Values.catalogueUpdater.containerSecurityContext | default .Values.containerSecurityContext | toYaml | nindent 10 }}

        env:
        - name: KAFKA_CONFIG_FILE_PATH
          value: /app/config/kafka-auth/kafka-config.properties
        - name: BOOTSTRAP_SERVERS
          value: {{ .Values.global.kafka.bootstrapServers | quote }}
        - name: INPUT_TOPIC
          value: {{ .Values.catalogueUpdater.topics.inputTopic | quote }}
        - name: OUTPUT_TOPIC
          value: {{ .Values.catalogueUpdater.topics.outputTopic | quote }}
        - name: DEBOUNCE_WINDOW_MS
          value: {{ .Values.catalogueUpdater.topics.debounceWindowMs | quote }}
        - name: FLUSH_INTERVAL_MS
          value: {{ .Values.catalogueUpdater.topics.flushIntervalMs | quote }}
        - name: MAX_BUFFER_SIZE
          value: {{ .Values.catalogueUpdater.topics.maxBufferSize | quote }}
        {{- if $metrics.enabled }}
        - name: OTEL_METRICS_EXPORTER
          value: "prometheus"
        - name: OTEL_TRACES_EXPORTER
          value: "none"
        - name: OTEL_LOGS_EXPORTER
          value: "none"
        {{- end }}
       
        ports:
        - name: http
          protocol: TCP
          containerPort: 10101

        readinessProbe:
          httpGet:
            path: /version-info
            port: 10101
        livenessProbe:
          httpGet:
            path: /healthz
            port: 10101
 
        volumeMounts:
        - mountPath: /app/config/kafka-auth/
          name: kafka-auth-config
       {{- with .Values.catalogueUpdater.extraVolumeMounts }}
          {{- toYaml . | nindent 12 }}
       {{- end }}
      
      {{- with .Values.catalogueUpdater.sidecars }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      - name: kafka-auth-config
        secret:
        {{- if .Values.global.kafka.existingConfigSecretName }}
          secretName: {{ .Values.global.kafka.existingConfigSecretName }}
        {{- else }}
          secretName: {{ include "document-pipeline.fullname" . }}-kafka-config
        {{- end }}
      {{- with .Values.catalogueUpdater.extraVolumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.catalogueUpdater.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.catalogueUpdater.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.catalogueUpdater.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end -}}
