{{- if .Values.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "catalogue-updater.fullname" . }}
  labels:
    {{- include "document-pipeline.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.catalogueUpdater.replicaCount }}
  selector:
    matchLabels:
      {{- include "catalogue-updater.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.catalogueUpdater.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "document-pipeline.labels" . | nindent 8 }}
        {{- include "catalogue-updater.selectorLabels" . | nindent 8 }}
        {{- with .Values.catalogueUpdater.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.catalogueUpdater.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "document-pipeline.serviceAccountName" . }}
      {{- with .Values.catalogueUpdater.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- $pullSecret := .Values.global.imagePullSecrets | default .Values.imagePullSecrets }}
      {{- with $pullSecret }}
      imagePullSecrets:
        {{- toYaml . | nindent 6 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.catalogueUpdater.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.catalogueUpdater.image.repository }}:{{ .Values.catalogueUpdater.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.catalogueUpdater.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.catalogueUpdater.service.port }}
              protocol: TCP
          env:
            - name: BOOTSTRAP_SERVERS
              value: {{ .Values.global.kafkaBootstrapUrls | quote }}
            - name: INPUT_TOPIC
              value: {{ .Values.catalogueUpdater.configuration.inputTopic | quote }}
            - name: OUTPUT_TOPIC
              value: {{ .Values.catalogueUpdater.configuration.outputTopic | quote }}
            - name: DEBOUNCE_WINDOW_MS
              value: {{ .Values.catalogueUpdater.configuration.debounceWindowMs | quote }}
            - name: FLUSH_INTERVAL_MS
              value: {{ .Values.catalogueUpdater.configuration.flushIntervalMs | quote }}
            - name: MAX_BUFFER_SIZE
              value: {{ .Values.catalogueUpdater.configuration.maxBufferSize | quote }}
            - name: KAFKA_CONFIG_FILE_PATH
              value: /app/config/kafka-auth/kafka-config.properties
          livenessProbe:
            httpGet:
              path: /healthz
              port: 10101
          readinessProbe:
            httpGet:
              path: /version-info
              port: 10101
          {{- with .Values.catalogueUpdater.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
          - mountPath: /app/config/kafka-auth/
            name: kafka-auth-config
          {{- with .Values.catalogueUpdater.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
      - name: kafka-auth-config
        secret:
        {{- if .Values.global.existingKafkaConfigSecretName }}
          secretName: {{ .Values.global.existingKafkaConfigSecretName }}
        {{- else }}
          secretName: {{ include "telicent-core.kafkaAuthConfigSecretName" . }}
        {{- end }}
      {{- with .Values.catalogueUpdater.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.catalogueUpdater.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.catalogueUpdater.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.catalogueUpdater.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end -}}