apiVersion: v2
name: telicent-preview
description: |
  Secondary chart containing products that are still under active development,
  and not yet part of CORE. Can be used to try new or preview features early.

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.6.1

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "1.16.0"

dependencies:
  - name: data-catalog-ui
    version: "1.15.5"
    repository: oci://quay.io/telicent/charts
    condition: data-catalog-ui.enabled
  - name: notifications
    version: "^0.1.0"
    repository: file://./charts/notifications
    condition: global.enterprise
  - name: notifications-projector
    version: "^0.1.0"
    repository: file://./charts/notifications-projector
    condition: global.enterprise
  - name: paperback-writer
    version: "^0.1.0"
    repository: file://./charts/paperback-writer
    condition: global.enterprise, paperback-writer.enabled
  - name: user-portal-ui
    version: "1.10.0"
    repository: oci://quay.io/telicent/charts
    condition: user-portal-ui.enabled
  - name: apicurio
    version: "^0.1.0"
    repository: file://./charts/apicurio
    condition: apicurio.enabled
icon: "https://avatars.githubusercontent.com/u/65304240?s=200&v=4"

# The name of the chart's maintainers.
maintainers:
  - name: telicent
    url: https://github.com/Telicent-IO
