{{- /*
Copyright (C) 2026 Telicent Limited
*/}}

apiVersion: v1
kind: Service

metadata:
  name: {{ include "user-portal-ui.fullname" . }}
  namespace: {{ include "user-portal-ui.namespace" . | quote }}
  labels:
    {{- include "user-portal-ui.labels" . | nindent 4 }}

spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "user-portal-ui.selectorLabels" . | nindent 4 }}
  ports:
  - name: http
    appProtocol: http
    protocol: TCP
    targetPort: http
    port: {{ .Values.service.port }}
