{{- if .Values.istioInjectionLabelJobEnabled }} 
{{- /*
Copyright (C) 2026 Telicent Limited
*/}}
apiVersion: batch/v1
kind: Job

metadata:
  name: job-inject-istio-label-namespace
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "telicent-core.labels" . | nindent 4 }}

  annotations:
    "sidecar.istio.io/inject": "false"
    "helm.sh/hook": pre-install
    "helm.sh/hook-delete-policy": hook-succeeded
    "helm.sh/hook-weight": "-7"

spec:
  backoffLimit: 3
  activeDeadlineSeconds: 180 # once reached, all running Pods are terminated with Job status:Failed
  ttlSecondsAfterFinished: 30 # once reached, Job is eligible to be automatically deleted
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        {{- include "telicent-core.labels" . | nindent 8 }}

    spec:
      restartPolicy: Never
      serviceAccountName: {{ include "telicent-core.serviceAccountName" . }}
      containers:
        - name: job-label-namespace
          image: "alpine/kubectl:latest"
          command: [ "/bin/sh", "-c" ]
          args:
            - |
              sleep 20;
              output="$(kubectl label namespace {{ .Release.Namespace }} istio-injection=enabled --overwrite)";
              echo "attempting to add istio label... $output";
              echo "$output" | grep "labeled" || ( echo "error: expected namespace/{{ .Release.Namespace }} (not) labeled" && exit 1 );
{{- end }}