{{- /*
Copyright (C) 2026 Telicent Limited
*/}}

apiVersion: v1
kind: ServiceAccount

metadata:
  name: {{ include "telicent-core.serviceAccountName" . }}
  labels:
    {{- include "telicent-core.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-delete-policy": hook-succeeded
    "helm.sh/hook-weight": "-10"
