apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "search.configMapName" . }}
  labels:
    app.kubernetes.io/name: {{ include "search.name" . }}
    helm.sh/chart: {{ include "search.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  env-config.js: |
    // UIs
    {{ if .Values.configuration.dataCatalogUiDeployed }}
    window.CATALOG_APP_URL = "https://{{ .Values.global.appHostDomain }}/data-catalog";
    {{ end }}
    {{ if .Values.configuration.graphUiDeployed }}
    window.GRAPH_APP_URL = "https://{{ .Values.global.appHostDomain }}/graph";
    {{ end }}
    window.SEARCH_APP_URL = "https://{{ .Values.global.appHostDomain }}/search";
    {{ if .Values.configuration.userPortalUiDeployed }}
    window.USER_PORTAL_URL = "https://{{ .Values.global.appHostDomain }}/user-portal/";
    {{ end}}

    // APIs
    window.ACCESS_URL = "{{ .Values.configuration.accessApiEndpoint }}";
    window.GRAPHQL_API_URL = "https://{{ .Values.global.appHostDomain }}/api/graphql/knowledge";
    window.ONTOLOGY_SERVICE_URL = "https://{{ .Values.global.appHostDomain }}/api/sparql";
    window.SEARCH_API_URL = "https://{{ .Values.global.appHostDomain }}/api/search";
    window.USER_PREF_API_URL = "https://{{ .Values.global.appHostDomain }}/api/user-preferences";

    // Signout
    // window.SIGN_OUT_URL = "https://{{ .Values.global.appHostDomain }}/oauth2/sign_out?rd=/oauth2/authorize";
    window.SIGN_OUT_URL;

    // Additional apps not currently deployed
    window.GEO_APP_URL;
    window.LIVE_APP_URL;
    window.PARALOG_APP_URL;
    // Extra APIs - deprecated?
    window.IMAGE_API_URL;
    window.ENTITY_EXTRACTION_API_URL;

    {{ if .Values.configuration.textAiApiDeployed | default false }}
    window.TEXT_AI_API_URL = "https://{{ .Values.global.appHostDomain }}/api/barry";
    window.featureFlags = {
        FF_AI_TRANSLATE: false,
    };
    {{ end }}

    // `appList` configures the menu that allows users to switch between different apps
    window.appList = [
    {{ if .Values.configuration.userPortalUiDeployed }}
        {
            id: "telicent-user-portal",
            name: "user portal",
            url: window.USER_PORTAL_URL,
            icon: "/search/assets/icons/UserPortalDark.svg",
        },
    {{ end }}
    {{ if .Values.configuration.graphUiDeployed }}
        {
            id: "telicent-graph",
            name: "graph",
            url: window.GRAPH_APP_URL,
            icon: "/search/assets/icons/GraphDark.svg",
        },
    {{ end }}
    {{ if .Values.configuration.dataCatalogUiDeployed }}
        {
            id: "telicent-catalog",
            name: "catalog",
            url: window.CATALOG_APP_URL,
            icon: "/search/assets/icons/CatalogDark.svg",
        },
    {{ end }}
    ];

    window.feAppOptions = {
        // 🚨 WARNING: ENCODE_SEARCH_PARAMS_MODE must be the same in search, graph, and user-portal 🚨
        //ENCODE_SEARCH_PARAMS_MODE: "as uri component", // default if unset
        ENCODE_SEARCH_PARAMS_MODE: 'as base64',
    };
