{{- /*
Copyright (C) 2025 Telicent Limited
*/}}
{{- if not .Values.ui.existingMapConfigSecret }}
apiVersion: v1
kind: Secret
type: Opaque

metadata:
  name: {{ include "search-ui.mapSecretName" . }}
  namespace: {{ include "search-ui.namespace" . | quote }}
  labels:
    {{- include "search-ui.labels" . | nindent 6 }}
data:
  secret-config.js: {{ include "search-ui.mapJs" . | b64enc }}
{{- end }}
