{{- if .Values.enabled -}}
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: 
spec:
  action: ALLOW
  rules:
  - from:
    - source:
        principals:
        - cluster.local/ns/{{ .Release.Namespace }}/sa/{{ include "document-pipeline.serviceAccountName" . }}
    to:
    - operation:
        methods:
        - '*'
  selector:
    matchLabels:
    {{- include "http-ingester.selectorLabels" . | nindent 6 }}
{{- end -}}