{{- if .Values.enabled -}}

apiVersion: security.istio.io/v1
kind: AuthorizationPolicy

metadata:
  name: {{ include "document-pipeline.fullname" . }}-ingress
  labels:
  {{- include "document-pipeline.labels" . | nindent 4 }}

spec:
  selector:
    matchLabels:
    {{- include "http-ingester.selectorLabels" . | nindent 6 }}

  action: ALLOW

  rules:
  - from:
    - source:
        principals:
        - cluster.local/ns/{{ .Release.Namespace }}/sa/{{ include "document-pipeline.serviceAccountName" . }}
    to:
    - operation:
        methods:
        - '*'

{{- end -}}