{{- if and .Values.enabled (not .Values.postgres.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "spatial.postgresSecretName" . }}
  labels:
    {{- include "spatial.labels" . | nindent 4 }}
type: kubernetes.io/basic-auth
data:
  username: {{ .Values.postgres.username }}
  password: {{ .Values.postgres.password }}
{{- end}}

