{{- range $jobname, $jobvalues := .Values.jobs }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $jobname }}
  labels:
    app.kubernetes.io/name: {{ $jobname }}
    telicent.io/resource: "true"
    telicent.io/run-once: "true"
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
        {{- range $key, $value := $.Values.annotations }}
          {{ $key }}: {{ $value | quote }}
        {{- end }}
      labels:
        app.kubernetes.io/name: {{ $jobname }}
        telicent.io/resource: "true"
        telicent.io/run-once: "true"
    spec:
      containers:
      - image: {{ $jobvalues.image.repository }}:{{ $jobvalues.image.tag }}
        imagePullPolicy: {{ $jobvalues.image.pullPolicy }}
        name: {{ $jobname }}
        env: {{- toYaml $jobvalues.config | nindent 10 }}
        resources: {{- toYaml $jobvalues.resources | nindent 10 }}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          runAsGroup: 185
          runAsNonRoot: true
          runAsUser: 185
          seccompProfile:
            type: RuntimeDefault
        volumeMounts:
        - mountPath: /app/config/kafka-auth
          name: kafka-auth-config
      restartPolicy: Never
      securityContext:
        fsGroup: 185
        runAsGroup: 185
        runAsNonRoot: true
        runAsUser: 185
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: {{ $jobvalues.serviceAccountName }}
      volumes:
      
      - name: kafka-auth-config
        secret:
        {{- if $.Values.existingKafkaConfigSecret }}
          secretName: {{ $.Values.existingKafkaConfigSecret.name }}
        {{- else }}
          secretName: {{ include "smart-cache-search.fullname" . }}-kafka-auth-config
        {{- end }}
      {{- with $.Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $.Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $.Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}