{{/*
Copyright (C) 2025-2026 Telicent Limited
*/}}

apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "opensearch-deps.secretName" . }}
  namespace: {{ include "opensearch-deps.namespace" . }}
data:
  internal_users.yml: |
    {{ include "opensearch-deps.secretData" . | b64enc | nindent 4 }}
