{{- /*
Copyright (C) 2026 Telicent Limited
*/}}
{{- if .Values.global.enterprise }}
apiVersion: {{ .Values.global.istioSecurityApiVersion }}
kind: AuthorizationPolicy

metadata:
  name: {{ include "search.fullname" . }}-internal-ingress
  namespace: {{ include "search.namespace" . | quote }}
  labels:
    {{- include "search.labels" . | nindent 4 }}

spec:
  selector:
    matchLabels:
      {{- include "search.selectorLabels" . | nindent 6 }}
  action: ALLOW
  rules:
  - from:
    - source:
        principals:
          {{- include "search.graphPrincipal" . | nindent 8 }}
    to:
    - operation:
        paths:
        - /documents
        - /documents/*
        - /documents/text-lookup
        - /documents/text-lookup/*
        - /facets
        - /facets/*
        - /list
        - /list/*
        - /states
        - /states/*
        - /typeahead
        - /typeahead/*
        - /indices
        - /aggregation-strategies
        - /aggregation-strategies/*
        - /healthz
        - /healthz/*
        - /version-info
        - /version-info/*
        methods: ["GET", "POST"]
{{- end }}
