{{- /*
Copyright (C) 2025 Telicent Limited
*/}}

{{- if not .Values.existingGraphUIConfigName }}
apiVersion: v1
kind: ConfigMap

metadata:
  name: {{ include "graph.configMapName" . }}
  labels:
    {{- include "graph.labels" . | nindent 4 }}

data:
  env-config.js: |
    // UIs
    {{ if .Values.configuration.dataCatalogUiDeployed }}
    window.CATALOG_APP_URL = "https://{{ .Values.global.appHostDomain }}/data-catalog";
    {{ end }}
    {{ if .Values.configuration.graphUiDeployed }}
    window.GRAPH_APP_URL = "https://{{ .Values.global.appHostDomain }}/graph";
    {{ end }}
    window.SEARCH_APP_URL = "https://{{ .Values.global.appHostDomain }}/search";
    {{ if .Values.configuration.userPortalUiDeployed }}
    window.USER_PORTAL_URL = "https://{{ .Values.global.appHostDomain }}/user-portal/";
    {{ end }}

    // APIs
    window.ACCESS_URL = "https://{{ .Values.global.appHostDomain }}/api/access";
    window.GRAPHQL_URL = "https://{{ .Values.global.appHostDomain }}/api/graphql/knowledge";
    window.SPARQL_URL = 'https://{{ .Values.global.appHostDomain }}/api/sparql/knowledge/sparql';
    window.ONTOLOGY_SERVICE_URL = "https://{{ .Values.global.appHostDomain }}/api/sparql";
    window.SEARCH_API_URL = "https://{{ .Values.global.appHostDomain }}/api/search";
    window.USER_PREF_API_URL = "https://{{ .Values.global.appHostDomain }}/api/user-preferences";

    // Signout
    // window.SIGN_OUT_URL = "https://{{ .Values.global.appHostDomain }}/oauth2/sign_out?rd=/oauth2/authorize";
    window.SIGN_OUT_URL;

    // Additional apps not currently deployed
    window.GEO_APP_URL;
    window.LIVE_APP_URL;
    window.PARALOG_APP_URL;
    // Extra APIs - deprecated?
    window.IMAGE_API_URL;
    window.ENTITY_EXTRACTION_API_URL;

    // `appList` configures the menu that allows users to switch between different apps
    window.appList = [
    {{ if .Values.configuration.userPortalUiDeployed }}
        {
            id: "telicent-user-portal",
            name: "user portal",
            url: window.USER_PORTAL_URL,
            icon: "/search/assets/icons/UserPortalDark.svg",
        },
    {{ end }}
    {{ if .Values.configuration.graphUiDeployed }}
        {
            id: "telicent-graph",
            name: "graph",
            url: window.GRAPH_APP_URL,
            icon: "/search/assets/icons/GraphDark.svg",
        },
    {{ end }}
    {{ if .Values.configuration.dataCatalogUiDeployed }}
        {
            id: "telicent-catalog",
            name: "catalog",
            url: window.CATALOG_APP_URL,
            icon: "/search/assets/icons/CatalogDark.svg",
        },
    {{ end }}
    ];

    window.feAppOptions = {
        // 🚨 WARNING: ENCODE_SEARCH_PARAMS_MODE must be the same in search, graph, and user-portal 🚨
        //ENCODE_SEARCH_PARAMS_MODE: "as uri component", // default if unset
        ENCODE_SEARCH_PARAMS_MODE: 'as base64',
    };

{{- end }}