{{- /*
Copyright (C) 2025 Telicent Limited
*/}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "graph.fullname" . }}
  labels:
    {{- include "graph.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
    {{- include "graph.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- range $key, $value := .Values.annotations }}
          {{ $key }}: {{ $value | quote }}
        {{- end }}
      labels:
        {{- include "graph.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "graph.serviceAccountName" . }}
      securityContext: {{- toYaml .Values.podSecurityContext | nindent 8 }}
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
      - name: graph-ui
        image: {{ .Values.image.repository }}:{{ include "graph.version" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources: {{- toYaml .Values.resources | nindent 10 }}
        securityContext: {{- toYaml .Values.containerSecurityContext | nindent 10 }}

        ports:
        - name: http
          containerPort: 8080
          protocol: TCP

        readinessProbe:
          httpGet:
            path: /graph/health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 2
        livenessProbe:
          httpGet:
            path: /graph/health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 2   

        volumeMounts:
        - mountPath: /usr/local/nginx/html/env-config.js
          name: app-config-volume
          subPath: env-config.js
        - name: secret-config-js-volume
          mountPath: /usr/local/nginx/html/secret-config.js
          subPath: secret-config.js
   
      volumes:
      - configMap:
          {{- if .Values.existingGraphUIConfigName }}
          name: {{ .Values.existingGraphUIConfigName }}
          {{- else }}
          name: {{ include "graph.configMapName" . }}
          {{- end }}
        name: app-config-volume
      {{- if .Values.configuration.existingMapConfigSecretName }}
      - secret:
          secretName: {{ .Values.configuration.existingMapConfigSecretName }}
        name: secret-config-js-volume
      {{- else }}
      - secret:
          secretName: {{ include "graph.fullname" . }}-secret-config-js
        name: secret-config-js-volume
      {{- end }}
      
       {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}  
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}     
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}