{{- /*
Copyright (C) 2025 Telicent Limited
*/}}

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "graph-ui.fullname" . }}
  labels:
  {{- include "graph-ui.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.serviceAccount.annotations | nindent 4 }}
