{{- /*
Copyright (C) 2025 Telicent Limited
*/}}

apiVersion: v1
kind: ConfigMap

metadata:
  name: {{ include "access-ui.configMapName" . }}
  namespace: {{ include "access-ui.namespace" . | quote }}
  labels:
    {{- include "access-ui.labels" . | nindent 4 }}
   
data:
  env-config.js: |
    window.ACCESS_API_URL = "https://{{ .Values.global.apiHostDomain }}/access";
    window.SIGN_OUT_URL = "{{ .Values.configuration.signOutUrl }}";
