{{- /*
Copyright (C) 2025 Telicent Limited
*/}}

apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ include "access-ui.fullname" . }}
  labels:
  {{- include "access-ui.labels" . | nindent 4 }}

spec:
  replicas: {{ .Values.replicas }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  
  selector:
    matchLabels:
    {{- include "access-ui.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
      {{- include "access-ui.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "access-ui.serviceAccountName" . }}
      securityContext: {{- toYaml .Values.podSecurityContext | nindent 8 }}

      {{- $pullSecret := .Values.global.imagePullSecrets | default .Values.image.pullSecrets }}
      {{- with $pullSecret }}
      imagePullSecrets:
        {{- toYaml . | nindent 6 }}
      {{- end }}
      containers:
      - name: access-ui
        image: {{ include "access-ui.image" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources: {{- toYaml .Values.resources | nindent 10 }}
        securityContext: {{- toYaml .Values.containerSecurityContext | nindent 10 }}
           
        ports:
        - name: http
          containerPort: {{ .Values.service.port }}
          protocol: TCP
      
        readinessProbe:
          httpGet:
            path: /access/health
            port: {{ .Values.service.port }}
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 2
        livenessProbe:
          httpGet:
            path: /access/health
            port: {{ .Values.service.port }}
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 2

        volumeMounts:
        - mountPath: /usr/local/nginx/html/env-config.js
          name: app-config-volume
          subPath: env-config.js
      
      volumes:
      - configMap:
          name: {{ include "access-ui.configMapName" . }}
        name: app-config-volume
