apiVersion: v1
kind: Service
metadata:
  name: {{ include "smart-cache-graph.serviceName" .}}
  labels:
    {{- include "smart-cache-graph.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "smart-cache-graph.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 3030
    - name: metrics
      protocol: TCP
      port: {{ .Values.metrics.service.port }}
      targetPort: 9464
