{{- /*
Copyright (C) 2025 Telicent Limited
*/}}
apiVersion: batch/v1
kind: Job

metadata:
  name: job-inject-istio-label-namespace
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "telicent-core.labels" . | nindent 4 }}

  annotations:
    "helm.sh/hook": post-install  # only run after the required resources have been created
    "helm.sh/hook-delete-policy": before-hook-creation

spec:
  backoffLimit: 3
  activeDeadlineSeconds: 180 # once reached, all running Pods are terminated with Job status:Failed
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        {{- include "telicent-core.labels" . | nindent 8 }}

    spec:
      restartPolicy: Never
      serviceAccountName: {{ include "telicent-core.serviceAccountName" . }}
      containers:
        - name: job-label-namespace
          image: "bitnami/kubectl:latest"
          command: [ "/bin/sh", "-c" ]
          args:
            - |
              sleep 30;
              output="$(kubectl label namespace {{ .Release.Namespace }} istio-injection=enabled --overwrite)";
              echo "attempting to add istio label... $output";
              echo "$output" | grep "labeled" || ( echo "error: expected namespace/{{ .Release.Namespace }} (not) labeled" && exit 1 );
