{{- if not .Values.global.existingKafkaConfigSecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "telicent-core.kafkaAuthConfigSecretName" . }}
  labels:
  {{- include "telicent-core.labels" . | nindent 4 }}
type: Opaque
data:
    kafka-config.properties: {{ .Values.global.kafkaConfig | b64enc }}
{{- end }}