{{- if not .Values.global.existingKafkaConfigSecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "telicent-core.kafkaAuthConfigSecretName" . }}
  labels:
  {{- include "telicent-core.labels" . | nindent 4 }}
type: Opaque
stringData:
    kafka-config.properties: |-
      security.protocol={{ .Values.global.kafkaConfigProtocol | quote }}
      sasl.mechanism={{ .Values.global.kafkaConfigMechanism | quote }}
      sasl.jaas.config=sasl.jaas.config=org.apache.kafka.common.security.scram.ScramLoginModule required \
        username={{ .Values.global.kafkaConfigUsername | quote }} \
        password={{ .Values.global.kafkaConfigPassword | quote }};

    kafka-config.toml: |-
      bootstrap.servers={{ .BOOTSTRAPSERVERS | toString }}
      security.protocol={{ .Values.global.kafkaConfigProtocol | quote }}
      sasl.mechanism={{ .Values.global.kafkaConfigMechanism | quote }}
      sasl.username={{ .Values.global.kafkaConfigUsername | quote }}
      sasl.password={{ .Values.global.kafkaConfigPassword | quote }}

    application.properties: |-
      camel.component.kafka.security-protocol={{ .Values.global.kafkaConfigProtocol | quote }}
      camel.component.kafka.sasl-mechanism={{ .Values.global.kafkaConfigMechanism | quote }}
      camel.component.kafka.sasl-jaas-config=org.apache.kafka.common.security.scram.ScramLoginModule required \
        username="{{ .Values.global.kafkaConfigUsername | quote }}" \
        password="{{ .Values.global.kafkaConfigPassword | quote }}";
{{- end }}