{{- /*
Copyright (C) 2025 Telicent Limited
*/}}

{{- if not .Values.global.kafka.existingConfigSecretName }}
apiVersion: v1
kind: Secret

metadata:
  name: {{ include "telicent-core.kafkaAuthConfigSecretName" . }}
  labels:
  {{- include "telicent-core.labels" . | nindent 4 }}
type: Opaque

data:
  kafka-config.properties: {{- (include "telicent-core.kafka-config-properties" . ) | b64enc | toYaml | indent 1 }}
  kafka-config.toml: {{- (include "telicent-core.kafka-config-toml" . ) | b64enc | indent 1 }}
  application.properties: {{- (include "telicent-core.application-properties" . ) | b64enc | toYaml | indent 1 }}
{{- end }}
---
{{- /*
Copyright (C) 2025 Telicent Limited
*/}}

{{- if and (not .Values.global.kafka.existingConfigSecretName) (.Values.kafkaTopics.enabled)}}
apiVersion: v1
kind: Secret

metadata:
  name: {{ include "telicent-core.kafkaAuthConfigSecretName" . }}
  labels:
  {{- include "telicent-core.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    "sidecar.istio.io/inject": "false"
type: Opaque

data:
  kafka-config.properties: {{- (include "telicent-core.kafka-config-properties" . ) | b64enc | toYaml | indent 1 }}
  kafka-config.toml: {{- (include "telicent-core.kafka-config-toml" . ) | b64enc | indent 1 }}
  application.properties: {{- (include "telicent-core.application-properties" . ) | b64enc | toYaml | indent 1 }}
{{- end }}


{{/*
Copyright (C) 2025 Telicent Limited
*/}}
{{- define "telicent-core.kafka-config-properties" -}}
      security.protocol={{ .Values.global.kafka.protocol }}
      sasl.mechanism={{ .Values.global.kafka.mechanism }}
      {{- if eq .Values.global.kafka.mechanism "SCRAM-SHA-512" }}
      sasl.jaas.config=org.apache.kafka.common.security.scram.ScramLoginModule required \
      {{- else if eq .Values.global.kafka.mechanism "PLAIN" }}
      sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required \
      {{- end }}
        username={{ .Values.global.kafka.username | quote }} \
        password={{ .Values.global.kafka.password | quote }};
{{- end  -}}

{{- define "telicent-core.kafka-config-toml" -}}
bootstrap.servers={{ .Values.global.kafka.bootstrapServers }}
security.protocol={{ .Values.global.kafka.protocol }}
sasl.mechanism={{ .Values.global.kafka.mechanism }}
sasl.username={{ .Values.global.kafka.username | replace "\"" "" }}
sasl.password={{ .Values.global.kafka.password | replace "\"" "" }}
{{- end  -}}

{{- define "telicent-core.application-properties" -}}
      camel.component.kafka.security-protocol={{ .Values.global.kafka.protocol }}
      camel.component.kafka.sasl-mechanism={{ .Values.global.kafka.mechanism }}
      {{- if eq .Values.global.kafka.mechanism "SCRAM-SHA-512" }}
      camel.component.kafka.sasl-jaas-config=org.apache.kafka.common.security.scram.ScramLoginModule required \
      {{- else if eq .Values.global.kafka.mechanism "PLAIN" }}
      camel.component.kafka.sasl-jaas-config=org.apache.kafka.common.security.plain.PlainLoginModule required \
      {{- end }}
        username={{ .Values.global.kafka.username | quote }} \
        password={{ .Values.global.kafka.password | quote }};
{{- end  -}}
