{{- /*
Copyright (C) 2025 Telicent Limited
*/}}

{{- if not .Values.global.existingKafkaConfigSecretName }}
apiVersion: v1
kind: Secret

metadata:
  name: {{ include "telicent-core.kafkaAuthConfigSecretName" . }}
  labels:
  {{- include "telicent-core.labels" . | nindent 4 }}
type: Opaque

data:
  kafka-config.properties: {{- (include "telicent-core.kafka-config-properties" . ) | b64enc | toYaml | indent 1 }}
  kafka-config.toml: {{- (include "telicent-core.kafka-config-toml" . ) | b64enc | indent 1 }}
  application.properties: {{- (include "telicent-core.application-properties" . ) | b64enc | toYaml | indent 1 }}
{{- end }}