apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "access-api.fullname" . }}
  labels:
  {{- include "access-api.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
    {{- include "access-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
      {{- include "access-api.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: {{ include "access-api.envConfigmapName" . }}
        - secretRef:
            name: {{ include "access-api.envSecretName" . }}
        {{- if .Values.cacertExistingConfigmap }}
        env:
        - name: NODE_EXTRA_CA_CERTS
          value: "/certs/ca.crt"
        {{ end }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: access-api
        ports:
        - containerPort: {{ .Values.service.port }}
          name: http
          protocol: TCP
        resources: {{- toYaml .Values.resources | nindent 10 }}
        securityContext: {{- toYaml .Values.containerSecurityContext
          | nindent 10 }}
        {{- if .Values.cacertExistingConfigmap }}
        volumeMounts:
        - name: cert-volume
          mountPath: /certs
        {{- end }}
      {{- if .Values.cacertExistingConfigmap }}
      volumes:
      - name: cert-volume
        configMap:
          name: {{ .Values.cacertExistingConfigmap }}
      {{- end }}
      securityContext: {{- toYaml .Values.podSecurityContext | nindent 8 }}
      serviceAccountName: {{ include "access-api.serviceAccountName" . }}
