apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "smart-cache-search.fullname" . }}-projector
  labels:
    {{- include "smart-cache-search.projectorLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.projector.replicas }}
  revisionHistoryLimit: {{ .Values.projector.revisionHistoryLimit }}
  selector:
    matchLabels:
    {{- include "smart-cache-search.projectorSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        prometheus.io/path: /
        prometheus.io/port: "9464"
        prometheus.io/scrape: "true"
      {{- range $key, $value := .Values.projector.annotations }}
        {{ $key }}: {{ $value | quote }}
      {{- end }}
      labels:
        {{- include "smart-cache-search.projectorLabels" . | nindent 8 }}
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets }}
      {{- end }}
      containers:
      - name: search-projector
        env:
        - name: BOOTSTRAP_SERVERS
          value: {{ .Values.projector.configuration.bootstrapServers | quote }}
        - name: DLQ_TOPIC
          value: {{ .Values.projector.configuration.dlqTopic | quote }}
        - name: ELASTIC_HOST
          value: {{ .Values.projector.configuration.elasticHost | quote }}
        - name: ELASTIC_INDEX
          value: {{ .Values.projector.configuration.elasticIndex | quote }}
        - name: ELASTIC_PORT
          value: {{ .Values.projector.configuration.elasticPort | quote }}
        - name: INDEX_BATCH_SIZE
          value: {{ .Values.projector.configuration.indexBatchSize | quote }}
        - name: JAVA_OPTIONS
          value: {{ .Values.projector.configuration.javaOptions | quote }}
        - name: KAFKA_CONFIG_FILE_PATH
          value: /app/config/kafka-auth/kafka-config.properties
        - name: OPENSEARCH_COMPATIBILITY
          value: {{ .Values.projector.configuration.opensearchCompatibility | quote }}
        - name: OTEL_METRICS_EXPORTER
          value: {{ .Values.projector.configuration.otelMetricsExporter | quote }}
        - name: OTEL_TRACES_EXPORTER
          value: {{ .Values.projector.configuration.otelTracesExporter | quote }}
        - name: TOPIC
          value: {{ .Values.projector.configuration.topic | quote }}
        {{- if .Values.projector.existingEnvironmentSecret }}
        envFrom:
        - secretRef:
            name: {{ .Values.projector.existingEnvironmentSecret | quote }}
            optional: true
        {{- end }}
        image: {{ .Values.projector.image.repository }}:{{ .Values.projector.image.tag | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.projector.image.pullPolicy }}
        livenessProbe:
          httpGet:
            path: /version-info
            port: 10101
            scheme: HTTP
          initialDelaySeconds: 45
          periodSeconds: 60
          timeoutSeconds: 5
        ports:
        - containerPort: 9464
          name: metrics
          protocol: TCP
        - containerPort: 10101
          name: health-probes
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /healthz
            port: 10101
            scheme: HTTP
          initialDelaySeconds: 45
          periodSeconds: 60
          timeoutSeconds: 10
        resources: {{- toYaml .Values.projector.resources | nindent 10 }}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
                - ALL
          runAsGroup: 185
          runAsNonRoot: true
          runAsUser: 185
          seccompProfile:
              type: RuntimeDefault
        volumeMounts:
        - mountPath: /app/config/kafka-auth/
          name: kafka-auth-config
        {{- if .Values.cacertExistingSecret }}
        - mountPath: {{ .Values.cacertContainerLocation }}
          name: java-truststore
          subPath: truststore.jks
        {{- end }}
      securityContext:
        fsGroup: 185
        runAsGroup: 185
        runAsNonRoot: true
        runAsUser: 185
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: {{ include "smart-cache-search.serviceAccountName" . }}-projector
      volumes:
      - name: kafka-auth-config
        secret:
          secretName: {{ include "smart-cache-search.kafkaAuthSecretName" . }}
      {{- if .Values.cacertExistingSecret }}
      - name: java-truststore
        secret:
          secretName: {{ .Values.cacertExistingSecret }}
      {{- end }}