apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "smart-cache-search.fullname" . }}-api
  labels:
    {{- include "smart-cache-search.apiLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.api.replicas }}
  revisionHistoryLimit: {{ .Values.api.revisionHistoryLimit }}
  selector:
    matchLabels:
    {{- include "smart-cache-search.apiSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        prometheus.io/path: /
        prometheus.io/port: "9464"
        prometheus.io/scrape: "true"
      {{- range $key, $value := .Values.api.annotations }}
        {{ $key }}: {{ $value | quote }}
      {{- end }}
      labels:
        {{- include "smart-cache-search.apiLabels" . | nindent 8 }}
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets }}
      {{- end }}
      containers:
      - name: search-api
        envFrom:
        - configMapRef:
            name: {{ include "smart-cache-search.fullname" . }}-api
        env:
        {{- with .Values.projector.extraEnvs }}
        {{- range . }}
        - name: {{ .name }}
          value: {{ .value | quote }}
        {{- end }}
        {{- end }}
        {{- if .Values.api.existingEnvironmentSecret }}
        envFrom:
        - secretRef:
            name: {{ .Values.api.existingEnvironmentSecret.name | quote }}
            optional: true
        {{- end }}
        image: {{ .Values.api.image.repository }}:{{ .Values.api.image.tag | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.api.image.pullPolicy }}
        livenessProbe:
          httpGet:
            path: /version-info
            port: 8181
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 60
          timeoutSeconds: 5
        ports:
        - containerPort: 8181
          name: http
          protocol: TCP
        - containerPort: 9464
          name: metrics
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8181
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 60
          timeoutSeconds: 10
        resources: {{- toYaml .Values.api.resources | nindent 10 }}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
                - ALL
          runAsGroup: 185
          runAsNonRoot: true
          runAsUser: 185
          seccompProfile:
              type: RuntimeDefault
        volumeMounts:
        {{- if .Values.existingCacertSecret }}
        - mountPath: /opt/jre-21/lib/security/cacerts
          name: java-truststore
          subPath: truststore.jks
        {{- end }}
      securityContext: 
        fsGroup: 185
        runAsGroup: 185
        runAsNonRoot: true
        runAsUser: 185
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: {{ include "smart-cache-search.serviceAccountName" . }}-api
      volumes:
      {{- if .Values.existingCacertSecret }}
      - name: java-truststore
        secret:
          secretName: {{ .Values.existingCacertSecret.name }}
      {{- end }}
