{{- if not .Values.api.existingEnvironmentSecret }}
apiVersion: v1
kind: Secret
metadata:
    name: {{ include "smart-cache-search.fullname" . }}-api
    labels:
    {{- include "smart-cache-search.apiLabels" . | nindent 4 }}
type: Opaque
data:
    ELASTIC_PASSWORD: ""
    ELASTIC_USER: ""
    TRUSTSTORE_PASS: ""
{{- end }}