{{- if not .Values.projector.existingEnvironmentSecret }}
apiVersion: v1
kind: Secret
metadata:
    name: {{ include "smart-cache-search.fullname" . }}-projector
    labels:
    {{- include "smart-cache-search.projectorLabels" . | nindent 4 }}
type: Opaque
data:
    ELASTIC_PASSWORD: ""
    ELASTIC_USER: ""
    TRUSTSTORE_PASS: ""
{{- end }}