apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: {{ include "data-catalog.fullname" . }}
  labels:
  {{ include "data-catalog.labels" . | nindent 4 }}
spec:
  action: ALLOW
  rules:
  - from:
    - source:
        principals:
        - {{ include "data-catalog.ingressPrincipal" . }}
    to:
    - operation:
        methods:
        - GET
  selector:
    matchLabels:
      {{ include "data-catalog.selectorLabels" . }}
