global:
  appHostDomain: "apps.telicent.io"
  authHostDomain: "auth.telicent.io"
  jwksUrl: "https://auth.telicent.io/realms/core/protocol/openid-connect/certs"

configuration:
  appHostUrl: "apps.telicent.io"
  accessApiEndpoint: "https://access-api.telicent.io"
  userPortalUiDeployed: true
  graphUiDeployed: true
  dataCatalogUiDeployed: true

map:
  searchUiMaptilerToken: "your.maptiler.token.here"
  # searchUiMapboxStyleSpecUrl: "https://your.mapbox.style.spec.url.here"
  # searchUiArcgisToken: "your.arcgis.token.here"
  # existingMapConfigSecretName: "your-existing-map-config-secret-name"

affinity: {}
annotations: {}
containerSecurityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  runAsGroup: 185
  runAsNonRoot: true
  runAsUser: 185
  seccompProfile:
    type: RuntimeDefault
fullnameOverride: ""

image:
  pullPolicy: IfNotPresent
  repository: 098669589541.dkr.ecr.eu-west-2.amazonaws.com/telicent-graph
  # appVersion is used by default when defining an empty string
  tag: ""

nameOverride: ""
nodeSelector: {}
podSecurityContext:
  fsGroup: 185
  runAsGroup: 185
  runAsNonRoot: true
  runAsUser: 185
  seccompProfile:
    type: RuntimeDefault
replicas: 1
resources: {}
revisionHistoryLimit: 3
service:
  port: 8080
  type: ClusterIP
serviceAccount:
  annotations: {}
  name: ""
tolerations: []
