apiVersion: v1
data:
  pipeline: {{ include "telicent-demo.kafkaPipelinePassword" . }}
  smart-cache: {{ include "telicent-demo.kafkaSmartCachePassword" .  }}
kind: Secret
metadata:
  name: kafka-passwords
type: Opaque