apiVersion: v1
kind: Secret
metadata:
  name: mongo-access-password
  labels:
  {{- include "mongodb.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ include "telicent-demo.mongoUserPreferencesPassword" . }}
---
apiVersion: v1
kind: Secret
metadata:
  name: mongo-admin-password
  labels:
  {{- include "mongodb.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ include "telicent-demo.mongoAdminPassword" . }}
---
apiVersion: v1
kind: Secret
metadata:
  name: mongo-user-preferences-password
  labels:
  {{- include "mongodb.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ include "telicent-demo.mongoUserPreferencesPassword" . }}
