global:
  tenantName: change-me
  appsHost: apps.127.0.0.1.nip.io
  idpHost: idp.127.0.0.1.nip.io
  authHost: auth.127.0.0.1.nip.io
  apiHost: api.127.0.0.1.nip.io

gateway-apps:
  enabled: true
  tlsCredentialName: ""
  tls:
    key: ""
    crt: ""

  fullnameOverride: ""
  ingressSelectors:
    istio: ingress

  jwksUri: ""
  jwtIssuer: ""

  nameOverride: ""

gateway-authn:
  enabled: true
  tlsCredentialName: ""
  tls:
    key: ""
    crt: ""

  fullnameOverride: ""
  ingressSelectors:
    istio: ingress

  nameOverride: ""
