{{- /*
Copyright (C) 2025 Telicent Limited
*/}}

apiVersion: security.istio.io/v1
kind: AuthorizationPolicy

metadata:
  name: {{ include "access.fullname" . }}-ingress
  namespace: {{ include "access.namespace" . | quote }}
  labels:
    {{- include "access.labels" . | nindent 4 }}

spec:
  selector:
    matchLabels:
      {{- include "access.selectorLabels" . | nindent 6 }}
  action: ALLOW
  rules:
  - from:
    - source:
        principals:
          {{- include "access.ingressPrincipal" .  | nindent 8 }}
    to:
    - operation:
        methods: ["GET", "POST", "PUT", "PATCH", "DELETE", "HEAD", "OPTIONS"]
