apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "spatial.name" . }}-config
  labels:
    {{- include "spatial.labels" . | nindent 4 }}
data:
  BOOTSTRAP_SERVERS: {{ .Values.global.kafkaBootstrapUrls }}
  SOURCE_TOPIC: {{ .Values.configuration.sourceTopic}}
  AUTO_ENABLE_DLQ: "True"
  GEO_CLEAN_POSTGRESQL_SC: geo_clean
  GEO_CLEAN_POSTGRESQL_PORT: "5432"
  GEO_CLEAN_POSTGRESQL_HOST: {{.Values.postgres.uri }}
  GEO_CLEAN_POSTGRESQL_SC: {{ .Values.postgres.db }}
  GEO_CLEAN_POSTGRESQL_USER: {{ .Values.postgres.username }}
