{{- if not .Values.postgres.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "spatial.postgresSecretName" . }}
  labels:
    {{- include "spatial.labels" . | nindent 4 }}
data:
  POSTGRES_PASSWORD: {{ .Values.postgres.password }}

{{- end}}

