# Copyright (C) 2026 Telicent Limited

apiVersion: v2
name: telicent-core
description: |
  Telicent CORE Platform, for all essential services and applications for our
  secure data integration and knowledge graph platform.

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 1.3.3

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "1.16.0"

#  The chart's dependencies. These are other charts that this chart depends on
# The dependencies will be fetched and installed when the chart is installed.
dependencies:
  - name: admin-ui
    version: "1.6.0"
    repository: oci://quay.io/telicent/charts
    condition: global.enterprise
  - name: auth
    version: "0.2.9"
    repository: oci://quay.io/telicent/charts
  - name: document-pipeline
    version: "^0.2.3"
    repository: file://./charts/document-pipeline
    condition: global.enterprise
  - name: graph
    version: "1.0.9"
    repository: oci://quay.io/telicent/charts
  - name: graph-ui
    version: "1.38.1"
    repository: oci://quay.io/telicent/charts
    condition: global.enterprise
  - name: query-ui
    version: 1.6.0
    repository: oci://quay.io/telicent/charts
  - name: search
    version: "2.2.0"
    repository: oci://quay.io/telicent/charts
    condition: global.enterprise
  - name: search-projector
    version: "2.2.0"
    repository: oci://quay.io/telicent/charts
    condition: global.enterprise
  - name: search-ui
    version: "4.21.0"
    repository: oci://quay.io/telicent/charts
    condition: global.enterprise
  - name: traefik-proxy
    version: "^0.1.0"
    repository: file://./charts/traefik-proxy
  - name: user-preferences
    version: "^0.2.0"
    repository: file://./charts/user-preferences
    condition: global.enterprise

icon: "https://avatars.githubusercontent.com/u/65304240?s=200&v=4"

# The name of the chart's maintainers.
maintainers:
  - name: telicent
    url: https://github.com/Telicent-IO
