# Copyright (C) 2025 Telicent Limited
# Telicent Core umbrella chart

# @section Global Parameters
# @descStart
# Contains global parameters, these parameters are mirrored across all Telicent Core sub charts, these values will be authoritative.
# @descEnd
global:
  ## Current available global image parameters: imageRegistry and imagePullSecrets
  ## Please, note that this will override the image parameters
  # @key global.imageRegistry Global image registry
  imageRegistry: ""
  # E.g.
  # imagePullSecrets:
  #   - myRegistryKeySecretName
  # @key global.imagePullSecrets Global registry secret names as an array
  imagePullSecrets: []

  # @key global.enterprise Enable enterprise mode, adding additional features and configurations
  enterprise: false

  # @key global.appHostDomain Domain associated with Telicent application services
  appHostDomain: "apps.telicent.io"
  # @key global.authHostDomain Domain associated with Telicent authentication services, including OIDC providers
  authHostDomain: "auth.telicent.io"
  # @key global.jwksUrl Endpoint exposing multiple public keys represented as JWKs (JSON Web Key Set)
  # NOTE: For Dex the endpoint would be https://{yourDexDomain}/keys
  jwksUrl: "https://{yourAuthdomain}/.well-known/jwks.json"

  # @key global.istioNamespace Namespace in which Istio is deployed
  # NOTE: Istio, by default, is deployed within the 'istio-system' namespace
  istioNamespace: istio-system
  # @key global.istioServiceAccountName Name of the Istio service account
  istioServiceAccountName: istio-ingress
  # @key global.istioGatewayName Name of the Istio Gateway Resource (LB operating at the edge of the mesh)
  istioGatewayName: ingress-gateway


  # @key global.kafkaBootstrapUrls Comma separated list containing Kafka bootstrap URLs
  kafkaBootstrapUrls: "kafka-bootstrap.kafka.svc.cluster.local:9092"
  # @key global.existingKafkaConfigSecretName Name of an existing secret containing Kafka configuration
  existingKafkaConfigSecretName: ""

  # @key global.kafkaConfigUsername Username for Kafka authentication
  kafkaConfigUsername: "your.kafka.username.here"
  # @key global.kafkaConfigPassword Password for Kafka authentication
  kafkaConfigPassword: "your.kafka.password.here"
  # @key global.kafkaConfigProtocol Protocol used for Kafka communication
  kafkaConfigProtocol: "SASL_SSL"
  # @key global.kafkaConfigMechanism SASL mechanism used for Kafka authentication
  kafkaConfigMechanism: "SCRAM-SHA-512"


  # @key global.existingTruststoreSecretName Name of an existing secret containing the truststore
  existingTruststoreSecretName: ""
  truststore:
    # @key global.truststore.mountPath The mount path for the truststore in the container
    mountPath: /app/config/truststore

# @key jobServiceAccountName Service account used for running jobs in Kubernetes.
jobServiceAccountName: producers

# @section Service Account Parameters
serviceAccount:
  # @key serviceAccount.name Name of the ServiceAccount to use. If not set, a name is generated using the fullname
  name: ""
  #@key serviceAccount.annotations Additional custom annotations for the ServiceAccount
  annotations: { }