enterprise: false
global:
  # existingKafkaConfigSecretName: ""
  kafkaConfig: |-
    security.protocol=SASL_SSL
    sasl.mechanism=SCRAM-SHA-512
    sasl.jaas.config=org.apache.kafka.common.security.scram.ScramLoginModule required \
        username="your.kafka.username.here" \
        password="your.kafka.password.here";
