{{- /*
Copyright (C) 2025 Telicent Limited
*/}}

{{- if .Values.global.enterprise }}

apiVersion: security.istio.io/v1
kind: AuthorizationPolicy

metadata:
  labels:
    {{- include "user-preferences-api.labels" . | nindent 4 }}
  name: {{ include "user-preferences-api.fullname" . }}-ingress

spec:
  action: ALLOW
  rules:
  - from:
    - source:
        principals:
        - {{ include "user-preferences-api.ingressPrincipal" . }}

    to:
    - operation:
        methods:
        - GET
        - POST
        - DELETE
        - HEAD
        - OPTIONS
        - PUT
        - PATCH
    when:
    - key: request.auth.claims[groups]
      values:
      - tc_read
  selector:
    matchLabels:
    {{- include "user-preferences-api.selectorLabels" . | nindent 6 }}
{{- end }}