{{- /*
Copyright (C) 2025 Telicent Limited
*/}}

{{- if not .Values.mongo.existingMongoPasswordSecret }}
apiVersion: v1
kind: Secret

metadata:
  name: {{ include "user-preferences-api.secret" . }}
type: Opaque

data:
  password: {{ .Values.mongo.password | b64enc | quote }}
{{- end }}