{{- /*
Copyright (C) 2025 Telicent Limited
*/}}

apiVersion: v1
kind: ServiceAccount

metadata:
  name: {{ include "user-preferences-api.serviceAccountName" . }}
  labels:
    {{- include "user-preferences-api.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
