apiVersion: v2
name: telicent-data
description: |
  Supplementary chart containing adapters and mappers for specific datasets and
  ontologies.

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.3.6

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "1.16.0"

icon: "https://avatars.githubusercontent.com/u/65304240?s=200&v=4"

# The name of the chart's maintainers.
maintainers:
  - name: telicent
    url: https://github.com/Telicent-IO

dependencies:
  - name: ies-ontology-producer
    version: ^0.2.0
    repository: "file://./charts/ies-ontology-producer"
  - name: ies-regions-ontology-adapter
    version: ^0.1.0
    repository: "file://./charts/ies-regions-ontology-adapter"
  - name: ies-regions-producer
    version: ^0.1.0
    repository: "file://./charts/ies-regions-producer"
  - name: ontologies-rdf-rdfs-owl-producer
    version: ^0.1.0
    repository: "file://./charts/ontologies-rdf-rdfs-owl-producer"
  - name: producer-acled-ontology
    version: ^0.1.0
    repository: "file://./charts/producer-acled-ontology"
    condition: global.enterprise
  - name: telicent-json-validation-mapper
    version: ^0.1.0
    repository: "file://./charts/telicent-json-validation-mapper"
    condition: global.enterprise
  - name: canonicals-event-geo-mapper
    version: ^0.1.0
    repository: "file://./charts/canonicals-event-geo-mapper"
    condition: global.enterprise
  - name: canonicals-event-knowledge-mapper
    version: ^0.1.0
    repository: "file://./charts/canonicals-event-knowledge-mapper"
    condition: global.enterprise
  - name: acled-locations-mapper
    version: ^0.1.0
    repository: "file://./charts/acled-locations-mapper"
    condition: global.enterprise
  - name: acled-participants-mapper
    version: ^0.1.0
    repository: "file://./charts/acled-participants-mapper"
    condition: global.enterprise
  - name: acled-validation-mapper
    version: ^0.1.0
    repository: "file://./charts/acled-validation-mapper"
    condition: global.enterprise
  - name: canonicals-event-document-mapper
    version: ^0.1.0
    repository: "file://./charts/canonicals-event-document-mapper"
    condition: global.enterprise
  - name: canonicals-ontology
    version: ^0.1.0
    repository: "file://./charts/canonicals-ontology"
    condition: global.enterprise
