{{- /*
Copyright (C) 2025 Telicent Limited
*/}}
{{- if and (.Values.enabled) (not .Values.existingConfigMapName) -}}
apiVersion: v1
kind: ConfigMap

metadata:
  name: {{ include "data-preparation.configMapName" . }}
  namespace: {{ include "data-preparation.namespace" . | quote }}
  labels:
    {{- include "data-preparation.labels" . | nindent 4 }}

data:
  CLIENT_PROPERTIES: /app/config/startup/client.properties

  {{- end }}
