{{- /*
Copyright (C) 2025 Telicent Limited
*/}}
{{- if .Values.enabled -}}
{{- $root := . -}}
{{- range $instanceName, $instanceConfig := .Values.instances }}
---
apiVersion: v1
kind: ConfigMap

metadata:
  name: {{ include "data-preparation.fullname" $root }}-{{ $instanceName }}
  namespace: {{ include "data-preparation.namespace" $root | quote }}
  labels:
    {{- include "data-preparation.instanceLabels" (dict "root" $root "instanceName" $instanceName) | nindent 4 }}

data:
  application.properties: |
    {{- include "data-preparation.application-properties" (dict "instance" $instanceConfig "global" $root.Values.global) | nindent 4 }}
{{- end }}
{{- end }}
