affinity: {}
annotations: {}
containerSecurityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  runAsGroup: 185
  runAsNonRoot: true
  runAsUser: 185
  seccompProfile:
    type: RuntimeDefault
fullnameOverride: ""
image:
  pullPolicy: IfNotPresent
  repository: docker.io/telicent/telicent-query
  tag: "1.2.1"
nameOverride: ""
nodeSelector: {}
podSecurityContext:
  fsGroup: 185
  runAsGroup: 185
  runAsNonRoot: true
  runAsUser: 185
  seccompProfile:
    type: RuntimeDefault
replicas: 1
resources: {}
revisionHistoryLimit: 3
service:
  port: 8080
  type: ClusterIP
serviceAccount:
  annotations: {}
  name: ""
tolerations: []

configuration:
  appHostUrl: "apps.telicent.com"
  accessApiEndpoint: "https://access-api.tc-core.svc.cluster.local"
  userPortalUiDeployed: true
  graphUiDeployed: true
  dataCatalogUiDeployed: true
  graphqlApiEndpoint: your.graphql.host.here
  sparqlApiEndpoint: your.sparql.host.here
