configuration:
  appHostDomain: "apps.telicent.io"

fullnameOverride: ""

image:
  repository: docker.io/telicent/telicent-query
  pullPolicy: IfNotPresent
  # appVersion is used by default when defining an empty string
  tag: ""

nameOverride: ""

deployment:
  replicas: 1
  resources: {}
  revisionHistoryLimit: 3

service:
  port: 8080
  type: ClusterIP

serviceAccount:
  annotations: {}
  name: ""
