configuration:
  appHostDomain: "apps.telicent.com"

fullnameOverride: ""

image:
  repository: docker.io/telicent/telicent-query
  pullPolicy: IfNotPresent
  # appVersion is used by default

nameOverride: ""

deployment:
  replicas: 1
  resources: {}
  revisionHistoryLimit: 3

service:
  port: 8080
  type: ClusterIP

serviceAccount:
  annotations: {}
  name: ""
