{{- if not .Values.authnTlsCredentialName -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gateways.authnTlsCredentialName" . }}
  labels:
    {{- include "gateways.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.authnTls.crt | b64enc }}
  tls.key: {{ .Values.authnTls.key | b64enc }}
{{- end }}
