entryPoints:
  web-app:
    address: ":8080/tcp"
    http:
      middlewares:
        - "headers-security@file"
  web-api:
    address: ":8081/tcp"
    http:
      middlewares:
        - cors-api@file
        - "headers-security@file"
        # disable when using oauth2-proxy, to avoid 401 error
        # - "oauth2@file"

  ping:
    address: ":9000/tcp"

global:
  checkNewVersion: false
  sendAnonymousUsage: false

ping:
  entryPoint: ping

providers:
  file:
    directory: "/app/config/routes"
    watch: false

{{- if .Values.logs.access.enabled }}
accessLog:
  format: common
{{- end }}

{{- if .Values.dashboard.enabled }}
api:
  dashboard: true
  basepath: {{ .Values.dashboard.basepath | quote }}
{{- end }}

log:
  level: {{ .Values.logs.general.level | upper }}
