{{- $_ := required " engine.applicationId' must be set" .Values.engine.applicationId }}

{{- $_ := required " .engine.kafka.inputTopic' must be set" .Values.engine.kafka.inputTopic }}
{{- $_ := required " .engine.kafka.outputTopic' must be set" .Values.engine.kafka.outputTopic }}
{{- $_ := required " .engine.kafka.dlqTopic' must be set" .Values.engine.kafka.dlqTopic }}

{{- if .Values.engine.filter.enableIDH }}
  {{- $_ := required "enabling IDH filtering requires 'engine.filter.client.version' to be set" .Values.engine.filter.client.version }}
  {{- $_ := required "enabling IDH filtering requires 'engine.filter.client.classification' to be set" .Values.engine.filter.client.classification }}
{{- end }}

{{- if .Values.engine.transformer.distributionId.enabled }}
  {{- $_ := required ".engine.transformer.distributionId.id to be set" .Values.engine.transformer.distributionId.id}}
{{- end }}
