apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: {{ include "paperback-writer.fullname" .}}
spec:
  action: ALLOW
  rules:
  - from:
    - source:
        principals:
        - {{ include "paperback-writer.ingressPrincipal" .}}
    to:
    - operation:
        methods:
        - POST
        - DELETE
        - GET
        paths:
        - /annotation
        - /annotation/*
        - /document-link
        - /document-link/*
        - /object-property
        - /object-property/*
        - /availability
        - /availability/*
        - /dcat/*
        - /dcterms/*
        - /vcard/*
        - /prov/*
        - /telicent/*
        - /ontology/*
    when:
    - key: request.auth.claims[{{ .Values.global.groupsClaim }}]
      values:
      - tc_write
  selector:
    matchLabels:
    {{ include "paperback-writer.selectorLabels" . | nindent 6 }}
