
{{- /*
Copyright (C) 2025 Telicent Limited
*/}}
{{- if and (.Values.enabled) (not .Values.existingCacertConfigmapName) -}}
apiVersion: v1
kind: ConfigMap

metadata:
  name: {{ include "paperback-writer.fullname" . }}-cacert
  namespace: {{ include "paperback-writer.namespace" . | quote }}

  labels:
    {{- include "paperback-writer.labels" . | nindent 4 }}

data:
  ca.crt: {{- .Values.cacert | toYaml | indent 1 }}
{{- end -}}
