{{- /*
Copyright (C) 2026 Telicent Limited
*/}}
{{- if and (.Values.enabled) (not .Values.existingConfigMapName) -}}
apiVersion: v1
kind: ConfigMap

metadata:
  name: {{ include "paperback-writer.envConfigMapName" . }}
  namespace: {{ include "paperback-writer.namespace" . | quote }}
  labels:
    {{- include "paperback-writer.labels" . | nindent 4 }}

data:
  SPARQL_DEFAULT_LABEL: {{ .Values.sparql.defaultLabel | default "!" |  quote }}
  # point to internal graph service
  SPARQL_URL:  {{ printf "http://%s" (include "paperback-writer.hostGraph" . )  | quote }}

  JWT_HEADER: "Authorization"
  JWT_USER_ID_ATTR: "preferred_name"
  JWT_ISSUER: {{ printf "https://%s" .Values.global.authHostDomain | quote }}
  # point to the internal auth service only!
  AUTH_SERVER_ALLOW_HTTP: "true"
  AUTH_SERVER_BASE_URL: {{ printf "http://%s" (include "paperback-writer.hostAuth" . )  | quote }}

  {{- end }}
