{{- if and (not .Values.existingSecretName) (.Values.enabled) (.Values.configuration.sparqlUser) (.Values.configuration.sparqlPwd) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "paperback-writer.fullname" . }}-secret
  labels:
    {{- include "paperback-writer.labels" . | nindent 4 }}
data:
  SPARQL_USER: {{ .Values.configuration.sparqlUser | quote }}
  SPARQL_PWD: {{ .Values.configuration.sparqlPwd | quote }}
{{- end }}
