{{- if .Values.enabled -}}

apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: {{ include "paperback-writer.fullname" . }}
spec:
  gateways:
  - {{ .Values.global.istioNamespace }}/{{ .Values.global.istioGatewayName }}
  hosts:
  - {{ .Values.global.appHostDomain }}
  http:
  - match:
    - uri:
        exact: /api/paperback
    redirect:
      uri: /api/paperback/
  - match:
    - uri:
        prefix: /api/paperback/
    rewrite:
      uri: /
    route:
    - destination:
        host: {{ include "paperback-writer.fullname" . }}
        port:
          number: 8000
{{- end -}}