{{- if not .Values.existingKafkaConfigSecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "telicent-pipelines.kafkaAuthConfigSecretName" . }}
  labels:
  {{- include "telicent-pipelines.labels" . | nindent 4 }}
type: Opaque
data:
  kafka-config.properties: {{- (include "telicent-pipelines.kafka-config-properties" . ) | b64enc | toYaml | indent 1 }}
  kafka-config.toml: {{- (include "telicent-pipelines.kafka-config-toml" . ) | b64enc | indent 1 }}
  application.properties: {{- (include "telicent-pipelines.application-properties" . ) | b64enc | toYaml | indent 1 }}
{{- end }}
