{{/*
Copyright (C) 2025-2026 Telicent Limited
*/}}

{{- if not .Values.existingUserPwdSecretName -}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "kafka.userPwdSecretName" . }}
  namespace: {{ include "kafka.namespace" . }}
  labels:
    {{- include "kafka.labels" . | nindent 4 }}
data:
  pipeline: {{ .Values.pipelinePassword | b64enc | quote }}
  smart-cache: {{ .Values.smartCachePassword | b64enc | quote }}
  external: {{ .Values.externalPassword | b64enc | quote }}
{{- end -}}
