# Copyright (C) 2025 Telicent Limited
# Telicent Auth stand-alone chart

# @section Global Parameters
# @descStart
# Contains global parameters, these parameters are mirrored within the Telicent core umbrella chart
# @descEnd

global:
  ## Current available global image parameters: imageRegistry and imagePullSecrets
  ## Please, note that this will override the image parameters
  # @key global.imageRegistry Global image registry
  imageRegistry: ""
  # E.g.
  # imagePullSecrets:
  #   - myRegistryKeySecretName
  # @key global.imagePullSecrets Global registry secret names as an array
  imagePullSecrets: []

  # @key global.enterprise Enable enterprise mode, adding additional features and configurations
  enterprise: false

  # @key global.appHostDomain Domain associated with Telicent application services
  appHostDomain: "apps.telicent.io"
  # @key global.authHostDomain Domain associated with Telicent authentication services, including OIDC providers
  authHostDomain: "auth.telicent.io"
  # @key global.groupsClaim Key used to retrieve groups from the OIDC provider
  groupsClaim: "groups"

  # @key global.istioNamespace Namespace in which Istio is deployed
  # Note: By default, Istio namespace is set to 'istio-system'
  istioNamespace: istio-system
  # @key global.istioServiceAccountName Name of the Istio service account
  istioServiceAccountName: istio-ingress
  # @key global.istioGatewayName Name of the Istio Gateway Resource (LB operating at the edge of the mesh)
  istioGatewayName: ingress-gateway
  # @key global.istioVirtualServiceEnabled Enable Istio traffic routing to a named destination service
  istioVirtualServiceEnabled: true

# -----------------------------------------------------------------------------
# @section Auth Parameters
# -----------------------------------------------------------------------------

# @section Configuration Parameters
# @descStart
# Contains configuration parameters specific to the Auth application
# @descEnd
configuration:
  # @key configuration.tokenIssuerUrl JWT token issuer URL
  tokenIssuerUrl: "{baseUrl}"
  # @key configuration.superUserIdentifier Super user identification if blank all users will be super users
  superUserIdentifier: ""
  # @key configuration.cookieParentDomain Cookie domain scope
  cookieParentDomain: .telicent.localhost
  # @key configuration.cookieSecure Enable secure cookies
  cookieSecure: true

# @section Clients
# @descStart
# List of registered clients
# @descEnd
clients:
  # @key clients.public A list of public client objects
  public: []
    # - client_id: spa-client
    #   redirect_uris:
    #     - http://spa.telicent.localhost/callback.html
    #   post_logout_redirect_uris:
    #     - http://spa.telicent.localhost/
  # @key clients.confidential A list of confidential client objects
  confidential: []
    # - client_id: client-1
    #   client_name: 'Secret Client'
    #   client_secret: password-1
    #   client_authentication_method: client_secret_post
    #   scope: write
  # @key clients.existingConfigMap Name of an existing config map resource containing all required public and confidential clients. If specified, the values for clients.public and clients.confidential will be ignored
  existingConfigMap: ""

# @section External IDP
# @descStart
# Note: It is recommended to use a Kubernetes secret for sensitive information like passwords
# @descEnd
externalIdp:
  # @key externalIdp.url External identity provider URL
  url: ""
  # @key externalIdp.clientName Identity provider display name
  clientName: Enterprise
  # @key externalIdp.clientId OAuth2 client ID
  clientId: ""
  # @key externalIdp.clientSecret OAuth2 client secret
  clientSecret: ""
  # @key externalIdp.existingSecret Name of an existing secret resource containing the OAuth2 client ID and secret. If specified, existing secret must contain data for EXTERNAL_IDP_CLIENT_ID and EXTERNAL_IDP_CLIENT_SECRET, and values for externalIdp.clientId and externalIdp.clientSecret will be ignored
  existingSecret: ""

# @section ForwardAuth
# @descStart
# Note: It is recommended to use a Kubernetes secret for sensitive information like passwords
# @descEnd
forwardAuth:
  # @key forwardAuth.secretValue ForwardAuth security secret
  secretValue: ""
  # @key forwardAuth.existingSecret Name of an existing secret resource containing the ForwardAuth secret value. If specified, existing secret must contain data for POSTGRES_PASSWORD, and the value for postgres.password will be ignored
  existingSecret: ""

# @section PostgreSQL
# @descStart
# Note: It is recommended to use a Kubernetes secret for sensitive information like passwords
# @descEnd
postgres:
  # @key postgres.uri PostgreSQL connection URL
  uri: ""
  # @key postgres.username PostgreSQL username
  username: ""
  # @key postgres.password PostgreSQL password
  password: ""
  # @key postgres.existingSecret Name of an existing secret resource containing the PostgreSQL password. If specified, existing secret must contain data for POSTGRES_PASSWORD, and the value for postgres.password will be ignored
  existingSecret: ""

# @section Common Parameters
# @key fullnameOverride String to fully override the generated release name
fullnameOverride: ""
# @key nameOverride String to partially override fullname (will maintain the release name)
nameOverride: ""

# @section image This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
image:
  # @key image.registry Auth server image registry
  registry: quay.io
  # @key image.repository Auth server image name
  repository: telicent/telicent-auth-server
  # @key image.pullPolicy Auth server image pull policy
  pullPolicy: IfNotPresent
  # @key image.tag Auth server image tag. If not set, a tag is generated using the appVersion
  tag: ""
  # @key image.pullSecrets Specify registry secret names as an array
  pullSecrets: []

# @section Service Account Parameters This section builds out the service account more information can be found here: https://kubernetes.io/docs/concepts/security/service-accounts/
serviceAccount:
  # @key serviceAccount.name Name of the created ServiceAccount. If not set, a name is generated using the fullname template
  name: ""
  # @key serviceAccount.annotations Additional custom annotations for the ServiceAccount
  annotations: {}

# @section Deployment Parameters For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
# @key podAnnotations Add extra annotations to the Deployment object
podAnnotations: {}
# @key extraEnvs List of additional environment variables to set in the pod
extraEnvs: []

podSecurityContext:
  # @key podSecurityContext.runAsUser Set the provisioning pod's Security Context runAsUser User ID
  runAsUser: 185
  # @key podSecurityContext.runAsGroup Set the provisioning pod's Security Context runAsGroup Group ID
  runAsGroup: 185
  # @key podSecurityContext.runAsNonRoot Set the provisioning pod's Security Context runAsNonRoot
  runAsNonRoot: true
  # @key podSecurityContext.fsGroup Set the provisioning pod's Group ID for the mounted volumes' filesystem
  fsGroup: 185
  seccompProfile:
    # @key podSecurityContext.seccompProfile.type Set the provisioning pod's Security Context seccomp profile
    type: RuntimeDefault

containerSecurityContext:
  # @key containerSecurityContext.runAsUser Set containers' Security Context runAsUser User ID
  runAsUser: 185
  # @key containerSecurityContext.runAsGroup Set containers' Security Context runAsGroup Group ID
  runAsGroup: 185
  # @key containerSecurityContext.runAsNonRoot Set container's Security Context runAsNonRoot
  runAsNonRoot: true
  # @key containerSecurityContext.allowPrivilegeEscalation Set container's Security Context allowPrivilegeEscalation
  allowPrivilegeEscalation: false
  capabilities:
    # @key containerSecurityContext.capabilities.drop List of capabilities to be dropped
    drop:
      - ALL
  seccompProfile:
    # @key containerSecurityContext.seccompProfile.type Set container's Security Context seccomp profile
    type: RuntimeDefault

# @section Traffic Exposure Parameters
service:
  # @key service.port Auth server service port
  port: 9000
  # @key service.type Auth server service port
  type: ClusterIP

resources:
  requests:
    # @key resources.requests.cpu Set containers' CPU request
    cpu: "500m"
    # @key resources.requests.memory Set containers' memory request
    memory: "2000Mi"
  limits:
    # @key resources.limits.cpu Set containers' CPU limit
    cpu: "2000m"
    # @key resources.limits.memory Set containers' memory limit
    memory: "4000Mi"

# @section Probes This is to setup the liveness and readiness probes, more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/
livenessProbe:
  httpGet:
    # @key livenessProbe.httpGet.path The path to use for the Auth server liveness probe
    path: /actuator/health
    # @key livenessProbe.httpGet.port The port to use for the Auth server liveness probe
    port: http
readinessProbe:
  httpGet:
    # @key readinessProbe.httpGet.path The path to use for the Auth server liveness probe
    path: /actuator/health
    # @key readinessProbe.httpGet.port The port to use for the Auth server liveness probe
    port: http

# @section Node Selection
# @key nodeSelector Allows you to schedule pods on a node with a label matching the given key-value pair.
nodeSelector: {}
# @key affinity Allows you to define affinity rules for scheduling pods, see: https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/
affinity: {}
# @key tolerations ALlows you to schedule pods on nodes with specified taints, see: https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/
tolerations: []

istio:
  ingress:
    # @key istio.ingress.principal Principal used for ingress traffic to this application by the Istio AuthorizationPolicy. If not set, a principal is generated using 'global.istioNamespace' and 'global.istioServiceAccountName'
    principal: ""
