# Copyright (C) 2025 Telicent Limited
# Telicent *Search* stand-alone chart

#
# @section Global Parameters
#
# @descStart
# Contains global parameters; these parameters are mirrored within the Telicent core umbrella chart
# Note: Only global parameters used within this chart will be listed below
# @descEnd
global:
  ## Current available global image parameters: imageRegistry and imagePullSecrets
  ## Please, note that this will override the image parameters
  # @key global.imageRegistry Global image registry
  imageRegistry: ""
  # E.g.
  # imagePullSecrets:
  #   - myRegistryKeySecretName
  # @key global.imagePullSecrets Global registry secret names as an array
  imagePullSecrets: []

  # @key global.enterprise Enable enterprise mode, adding additional features and configurations
  enterprise: false

  # @key global.appHostDomain Domain associated with Telicent application/ui services. This value cannot be changed after it is set
  appHostDomain: ""
  # @key global.apiHostDomain Domain associated with Telicent Api services. This value cannot be changed after it is set
  apiHostDomain: ""
  # @key global.authHostDomain Domain associated with Telicent authentication services, including OIDC providers. This value cannot be changed after it is set
  authHostDomain: ""

  truststore:
    # @key global.truststore.existingSecret Name of an existing secret containing the truststore
    existingSecret: ""
    # @key global.truststore.mountPath The mount path for the truststore in the container
    mountPath: /app/config/truststore

#
# @section Application Parameters - Java
#
# @descStart
# Contains Java configuration parameters to be used by the *Search* application
# @descEnd
java:
  # @key java.jvmOptions JVM options for the application
  jvmOptions: "-XX:MaxRAMPercentage=80.0"

#
# @section Application Parameters - Elastic/OpenSearch and Secret
#
# @descStart
# The following contains connection details to an Elastic/OpenSearch service, on which the application relies.
# It is recommended to store sensitive information including passwords in a Kubernetes secret and not in Helm values.
# For Quick Start purposes, a secret named `tc-auth-usr-elastic-search` will be created if one is not set.
# @descEnd
elastic:
  # @key elastic.host Elastic/OpenSearch host
  # Note: This should be the URL of your Elastic/OpenSearch service, including protocol (https or http)
  host: https://your.opensearch.host
  # @key elastic.port Elastic/OpenSearch port number
  port: "443"
  # @key elastic.opensearchCompatibility Enable OpenSearch compatibility
  opensearchCompatibility: true
  # @key elastic.index Elastic/OpenSearch index to be used
  index: search,doc-content
  # @key elastic.searchFieldOptions Field options for search
  # This is a comma-separated list of fields to be used for search, with optional weights
  searchFieldOptions: "primaryName^2,*"
  # @key elastic.indexBatchSize Number of documents to index in a single batch operation
  indexBatchSize: "100"

  # @key elastic.existingSecret Name of an existing secret. The secret must contain 2 keys: 'username', 'password'
  # Note: Left unset, it will create a secret named: tc-auth-usr-elastic-search
  existingSecret: ""
  # @key elastic.username OpenSearch/Elastic username
  # Note: For additional security, the username is read from the secret, as defined by 'existingSecret' and not from this value!
  username: ""
  # @key elastic.password OpenSearch/Elastic user password
  password: ""

#
# @section ConfigMap Parameters
#
# @descStart
# Contains configuration parameters specific to the *Search* application
# @descEnd
configMap:
  # @key configMap.existingEnvConfigMap Name of existing configmap containing *Search* Environment Configuration
  # Note: When it's set it will disable configmap creation.
  existingEnvConfigMap: ""

#
# @section Common Parameters
#
# @key nameOverride String to partially override fullname (will maintain the release name)
nameOverride: ""
# @key fullnameOverride String to fully override the generated release name
fullnameOverride: ""
# @key namespaceOverride String to fully override all deployed resources namespace
namespaceOverride: ""
# @key commonLabels Add labels to all the deployed resources
commonLabels: {}

#
# @section Deployment Parameters
#
# @key replicas Number of *Search* replicas to deploy
replicas: 1
# @key revisionHistoryLimit Number of controller revisions to keep
revisionHistoryLimit: 5

# @key annotations Add extra annotations to the deployment object
annotations: {}
# @key podLabels Add extra labels to the *Search* pod
podLabels: {}
# @key podAnnotations Add extra annotations to the *Search* pod
podAnnotations: {}
# @key extraEnvVars Array with extra environment variables to add to *Search* pod
# Example:
# extraEnvVars:
# - name: FOO
#   value: instance
extraEnvVars: []
# @key extraVolumes Additional containers to be added to the *Search* pod
extraVolumes: []
# @key extraVolumeMounts Optionally specify extra list of additional volumeMounts
extraVolumeMounts: []
# @key initContainers Add init containers to the pod
initContainers: []
# Example:
# sidecars:
# - name: your-image-name
#   image: your-image
#   ports:
#   - name: portname
#     containerPort: 1234
# @key sidecars Add sidecars to the pod
sidecars: []

#
# @section Deployment Image Parameters
#
image:
  # @key image.registry *Search* image registry
  registry: quay.io
  # @key image.repository *Search* image name
  repository: telicent/search-api-server
  # @key image.tag *Search* image tag. If not set, a tag is generated using the appVersion
  tag: ""
  # @key image.pullPolicy *Search* image pull policy
  pullPolicy: IfNotPresent
  # @key image.pullSecrets Specify registry secret names as an array
  pullSecrets: []

resources:
  requests:
    # @key resources.requests.cpu Set containers' CPU request
    cpu: "1000m"
    # @key resources.requests.memory Set containers' memory request
    memory: "4000Mi"
  limits:
    # @key resources.limits.cpu Set containers' CPU limit
    cpu: "2000m"
    # @key resources.limits.memory Set containers' memory limit
    memory: "8000Mi"

#
# @section Deployment Security Context Parameters - Default Security Context
#
podSecurityContext:
  # @key podSecurityContext.runAsUser Set the provisioning pod's Security Context runAsUser User ID
  runAsUser: 185
  # @key podSecurityContext.runAsGroup Set the provisioning pod's Security Context runAsGroup Group ID
  runAsGroup: 185
  # @key podSecurityContext.runAsNonRoot Set the provisioning pod's Security Context runAsNonRoot
  runAsNonRoot: true
  # @key podSecurityContext.fsGroup Set the provisioning pod's Group ID for the mounted volumes' filesystem
  fsGroup: 185
  seccompProfile:
    # @key podSecurityContext.seccompProfile.type Set the provisioning pod's Security Context seccomp profile
    type: RuntimeDefault
containerSecurityContext:
  # @key containerSecurityContext.runAsUser Set containers' Security Context runAsUser User ID
  runAsUser: 185
  # @key containerSecurityContext.runAsGroup Set containers' Security Context runAsGroup Group ID
  runAsGroup: 185
  # @key containerSecurityContext.runAsNonRoot Set container's Security Context runAsNonRoot
  runAsNonRoot: true
  # @key containerSecurityContext.allowPrivilegeEscalation Set container's Security Context allowPrivilegeEscalation
  allowPrivilegeEscalation: false
  capabilities:
    # @key containerSecurityContext.capabilities.drop List of capabilities to be dropped
    drop:
      - ALL
  seccompProfile:
    # @key containerSecurityContext.seccompProfile.type Set container's Security Context seccomp profile
    type: RuntimeDefault

#
# @section Deployment Affinity Parameters
#
# @key affinity Affinity for pod assignment
# Ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
affinity: {}
# @key nodeSelector Node labels for pod assignment
# Ref: https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/
nodeSelector: {}
# @key tolerations Tolerations for pod assignment
# Ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
tolerations: []

#
# @section Service Account Parameters
#
serviceAccount:
  # @key serviceAccount.create Specifies whether a service account should be created
  create: true
  # @key serviceAccount.name Name of the ServiceAccount to use. If not set, a name is generated using the fullname
  name: ""
  # @key serviceAccount.annotations Additional custom annotations for the ServiceAccount
  annotations: {}
  # @key serviceAccount.automount Automatically mount a ServiceAccount's API credentials
  automount: true

#
# @section Traffic Exposure Parameters
#
service:
  # @key service.name *Search* service name. If not set, a name is generated using the fullname
  name: ""
  # @key service.port *Search* service port
  port: 8080
  # @key service.type *Search* service port
  type: ClusterIP

#
# @section Metrics (Prometheus) Exposure Parameters
#
metrics:
  # @key metrics.enabled Enable Prometheus metrics
  enabled: true
  service:
    # @key metrics.service.name Name for the Prometheus service
    name: metrics
    # @key metrics.service.port Port for the Prometheus service
    port: 9464

#
# @section Host(s) Parameters - Contains host information for applications deployed via *telicent-core* chart.
#
# @descStart
# *Search* interacts directly with other Telicent Applications using their default service/serviceAccount and port.
# If either of those details changes, you can use this section to correctly refer to those apps.
# @descEnd
hosts:
  # @key hosts.enableAutoCorrect Allow for the release name to be automatically pre-fixed to each host value when required (default behavior when installing through the parent chart). Alternatively, the host value will be used as it is, without any modification
  enableAutoCorrect: true
  # @key hosts.auth Auth application default host value, as defined by 'service/serviceAccount:port'
  auth: "auth:8080"
  # @key hosts.traefikProxy Traefik Proxy application default host value, as defined by 'service/serviceAccount:port'
  traefikProxy: "traefik-proxy:8080"
  # @key hosts.graph Graph application default host value, as defined by 'service/serviceAccount:port'
  graph: "graph:8080"
