apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "traefik-reverse-proxy.fullname" . }}-static
  labels:
    {{- include "traefik-reverse-proxy.labels" . | nindent 4 }}
data:
  traefik.yml: |
    api:
      dashboard: {{ .Values.traefik.config.api.dashboard }}
      insecure: {{ .Values.traefik.config.api.insecure }}
    
    entryPoints:
      {{- toYaml .Values.traefik.config.entryPoints | nindent 6 }}
    
    providers:
      {{- toYaml .Values.traefik.config.providers | nindent 6 }}
    
    log:
      {{- toYaml .Values.traefik.config.log | nindent 6 }}
    
    {{- if .Values.traefik.config.accessLog }}
    accessLog:
      {{- toYaml .Values.traefik.config.accessLog | nindent 6 }}
    {{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "traefik-reverse-proxy.fullname" . }}-dynamic
  labels:
    {{- include "traefik-reverse-proxy.labels" . | nindent 4 }}
data:
  dynamic.yml: |
    http:
      routers:
        - name: "search"
          rule: "Host(`{{ .Values.global.appHostDomain }}`) || PathPrefix(`/search`)"
          service: "app2-service"
          port: 8080
          namespace: "{{ include .Release.Namespace . }}"
          middlewares:
            - "auth"
            - "strip-prefix"
        {{- range .Values.traefik.routes }}
        {{ .name }}:
          rule: "{{ .rule }}"
          service: {{ .name }}-service
          {{- if .middlewares }}
          middlewares:
            {{- range .middlewares }}
            - {{ . }}
            {{- end }}
          {{- end }}
        {{- end }}
      
      services:
        {{- range .Values.traefik.routes }}
        {{ .name }}-service:
          loadBalancer:
            servers:
              - url: "http://{{ .service }}.{{ .namespace }}.svc.cluster.local:{{ .port }}"
        {{- end }}
      
      middlewares:
        strip-prefix:
          stripPrefix:
            prefixes:
              - "/app2"
        rate-limit:
          rateLimit:
            burst: 100
            average: 50
        # traefik-oidc-auth:
        #   plugin:
        #     traefik-oidc-auth:
        #       Provider:
        #         ClientId: <YourClientId>
        #         ClientSecret: <YourClientSecret>
        #         Url: 
        #       Scopes:
        #         - openid
        #         - profile
        #         - email
        {{- range $name, $config := .Values.traefik.middlewares }}
        {{ $name }}:
          {{- toYaml $config | nindent 10 }}
        {{- end }}