apiVersion: v1
kind: Service
metadata:
  name: {{ include "traefik-reverse-proxy.fullname" . }}
  labels:
    {{- include "traefik-reverse-proxy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.traefik.service.type }}
  ports:
    - port: {{ .Values.traefik.service.port }}
      targetPort: {{ .Values.traefik.service.targetPort }}
      protocol: TCP
      name: web
  selector:
    {{- include "traefik-reverse-proxy.selectorLabels" . | nindent 4 }}