{{- range $mapperName, $mapper := .Values.mappers }}
{{- if $mapper.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "telicent-data.fullname" $ }}-{{ $mapperName }}
  labels:
    {{- include "telicent-data.labels" $ | nindent 4 }}
    app.kubernetes.io/component: mapper
    app.kubernetes.io/mapper: {{ $mapperName }}
  {{- with $mapper.podAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ $mapper.replicas | default 1 }}
  selector:
    matchLabels:
      {{- include "telicent-data.selectorLabels" $ | nindent 6 }}
      app.kubernetes.io/component: mapper
      app.kubernetes.io/mapper: {{ $mapperName }}
  template:
    metadata:
      annotations:
      {{- with $mapper.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "telicent-data.selectorLabels" $ | nindent 8 }}
        app.kubernetes.io/component: mapper
        app.kubernetes.io/mapper: {{ $mapperName }}
        {{- with $mapper.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- $pullSecret := $.Values.global.imagePullSecrets | default $mapper.image.pullSecrets }}
      {{- with $pullSecret }}
      imagePullSecrets:
        {{- toYaml . | nindent 6 }}
      {{- end }}
      serviceAccountName: {{ include "telicent-data.serviceAccountName" $ }}
      {{- with $mapper.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $mapper.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $mapper.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $mapper.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ $mapperName }}
        {{- with $mapper.securityContext }}
        securityContext:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- $imageContext := dict "Values" $.Values "Chart" $.Chart "image" $mapper.image }}
        image: {{ include "telicent-data.image" $imageContext }}
        imagePullPolicy: {{ $mapper.image.pullPolicy }}
        {{- if $mapper.command }}
        command:
          {{- toYaml $mapper.command | nindent 10 }}
        {{- end }}
        {{- if $mapper.args }}
        args:
          {{- toYaml $mapper.args | nindent 10 }}
        {{- end }}
        env:
        - name: BOOTSTRAP_SERVERS
          value: {{ $.Values.global.kafka.bootstrapServers | quote }}
        - name: KAFKA_CONFIG_FILE_PATH
          value: /app/config/kafka-auth/kafka-config.toml
        - name: KAFKA_CONFIG_MODE
          value: {{ (index $mapper "configuration" "kafkaConfigMode") | default "toml" | quote }}
        - name: MAPPER_NAME
          value: {{ $mapperName | quote }}
        - name: DEFAULT_DATA_NAMESPACE
          value: {{ $mapper.configuration.dataNamespace | default "default" | quote }}
        {{- if $mapper.env }}
        {{- range $key, $value := $mapper.env }}
        - name: {{ $key }}
          value: {{ $value | quote }}
        {{- end }}
        {{- end }}
        {{- if $mapper.envFrom }}
        envFrom:
          {{- toYaml $mapper.envFrom | nindent 10 }}
        {{- end }}
        ports:
        - name: http
          containerPort: {{ $mapper.service.port | default 80 }}
          protocol: TCP
        {{- with $mapper.livenessProbe }}
        livenessProbe:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with $mapper.readinessProbe }}
        readinessProbe:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        volumeMounts:
        - mountPath: /app/config/kafka-auth/
          name: kafka-auth-config
        {{- with $mapper.volumeMounts }}
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with $mapper.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      volumes:
      - name: kafka-auth-config
        secret:
        {{- if $.Values.global.kafka.existingConfigSecretName }}
          secretName: {{ $.Values.global.kafka.existingConfigSecretName }}
        {{- else }}
          secretName: {{ include "telicent-data.kafkaAuthConfigSecretName" $ }}
        {{- end }}
      {{- with $mapper.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
{{- end }}


