{{- if .Values.serviceAccount.create -}}
{{- /*
Copyright (C) 2025 Telicent Limited
*/}}
apiVersion: v1
kind: ServiceAccount

metadata:
  name: {{ .Values.serviceAccount.name }}
  labels:
    {{- include "telicent-data.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.serviceAccount.annotations | nindent 4 }}
{{- end -}}