{{/*
Copyright (C) 2025-2026 Telicent Limited
*/}}

apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: {{ include "gateway-apps.fullname" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
  {{- include "gateway-apps.labels" . | nindent 4 }}
spec:
  action: ALLOW
  rules:
  - to:
    - operation:
        hosts:
        - {{ .Values.global.appsHost }}
        - {{ .Values.global.appsHost }}:*
        - {{ .Values.global.apiHost }}
        - {{ .Values.global.apiHost }}:*
        - {{ .Values.global.authHost }}
        - {{ .Values.global.authHost }}:*
        {{- range .Values.global.additionalHosts }}
        - {{ . }}
        - {{ . }}:*
        {{- end }}
        paths:
        - /*
        - /
  selector:
    matchLabels:
      {{- .Values.ingressSelectors | toYaml | nindent 6 }}
