# Declare routers / services / middlewares
http:
  routers:
    access:
      rule: {{ printf "Host(`%s`) && PathPrefix(`/access`)" .Values.global.apiHostDomain }}
      service: access
      entryPoints:
        - web-api
      middleWares:
        - path-access
        - host-access

  services:
    access:
      loadBalancer:
        servers:
          - url: http://{{ .Values.hosts.access | default (printf "%s.%s:8080" (include "traefik-proxy.routesService" (list . "access")) .Release.Namespace) }}

  middlewares:
    path-access:
      replacePathRegex:
        regex: "^/api/access/(.*)"
        replacement: "/$1"
    host-access:
      headers:
        customRequestHeaders:
          host: {{ .Values.hosts.access | default (printf "%s.%s:8080" (include "traefik-proxy.routesService" (list . "access")) .Release.Namespace) }}
