# Declare routers / services / middlewares
http:
  routers:
    auth-forward:
      rule: {{ printf "Host(`%s`) && PathPrefix(`/auth/forward`)" .Values.global.authHostDomain }}
      priority: 9
      service: auth
      entryPoints:
        - web-auth
      middleWares:
        - host-auth

    auth-user-info:
      rule: {{ printf "Host(`%s`) && PathPrefix(`/userinfo`)" .Values.global.authHostDomain }}
      priority: 8
      service: auth
      entryPoints:
        - web-auth
      middleWares:
        - host-auth
        - oauth2

    auth-admin:
      rule: {{ printf "Host(`%s`) && PathRegexp(`^/(sessions|groups|roles|permissions|users|clients)`)" .Values.global.authHostDomain }}
      priority: 7
      service: auth
      entryPoints:
        - web-auth
      middleWares:
        - host-auth
        - oauth2

    auth-oidc:
      rule: {{ printf "Host(`%s`) && PathPrefix(`/.well-known`)" .Values.global.authHostDomain }}
      priority: 6
      service: auth
      entryPoints:
        - web-auth
      middleWares:
        - host-auth

    auth-oauth2:
      rule: {{ printf "Host(`%s`) && PathRegexp(`^/(session|oauth2|login|logout|favicon\\.svg|account-inactive|access-denied|error)`)" .Values.global.authHostDomain }}
      priority: 5
      service: auth
      entryPoints:
        - web-auth
      middleWares:
        - host-auth

  services:
    auth:
      loadBalancer:
        servers:
          - url: {{ printf "http://%s"  (include "traefik-proxy.hostAuth" .) }}

  middlewares:
    host-auth:
      headers:
        customRequestHeaders:
          host: {{ include "traefik-proxy.hostAuth" . }}
