# Declare routers / services / middlewares
http:
  routers:

    auth-api:
      rule: {{ printf "Host(`%s`) && PathPrefix(`/api/auth`)" .Values.global.appHostDomain }}
      service: auth
      entryPoints:
        - web
      middleWares:
        - oauth2
        - path-auth-api
        - host-auth

    auth-oauth2:
      rule: {{ printf "Host(`%s`) && PathPrefix(`/oauth2`)" .Values.global.appHostDomain } }
      service: auth
      entryPoints:
        - web
      middleWares:
        - path-auth-oauth2
        - host-auth

  services:
    auth:
      loadBalancer:
        servers:
          - url: http://{{ .Values.hosts.auth | default (printf "%s.%s:9000" (include "traefik-proxy.routesService" (list . "auth")) .Release.Namespace) }}

  middlewares:
    path-auth-api:
      replacePathRegex:
        regex: "^/api/auth/(.*)"
        replacement: "/api/auth/$1"

    path-auth-oauth2:
      replacePathRegex:
        regex: "^/oauth2(.*)"
        replacement: "/oauth2/$1"

    host-auth:
      headers:
        customRequestHeaders:
          host: {{ .Values.hosts.auth | default (printf "%s.%s:9000" (include "traefik-proxy.routesService" (list . "auth")) .Release.Namespace) }}

