# Declare routers / services / middlewares
http:
  routers:
    auth-forward:
      rule: {{ printf "Host(`%s`) && PathPrefix(`/auth/forward`)" .Values.global.authHostDomain }}
      service: auth
      entryPoints:
        - web-app
      middleWares:
        - host-auth
    auth-user-info:
      rule: {{ printf "Host(`%s`) && PathPrefix(`/userinfo`)" .Values.global.authHostDomain }}
      service: auth
      entryPoints:
        - web-api
      middleWares:
        - host-auth
    auth-oauth2:
      rule: {{ printf "Host(`%s`) && PathRegexp(`^/(oauth2|session|login|logout)`)" .Values.global.authHostDomain }}
      service: auth
      entryPoints:
        - web-app
      middleWares:
        - host-auth
    auth-oidc:
      rule: {{ printf "Host(`%s`) && PathPrefix(`\\.well-known`)" .Values.global.authHostDomain }}
      service: auth
      entryPoints:
        - web-app
      middleWares:
        - host-auth

  services:
    auth:
      loadBalancer:
        servers:
          - url: http://{{ .Values.hosts.auth | default (printf "%s.%s:9000" (include "traefik-proxy.routesService" (list . "auth")) .Release.Namespace) }}

  middlewares:
    host-auth:
      headers:
        customRequestHeaders:
          host: {{ .Values.hosts.auth | default (printf "%s.%s:9000" (include "traefik-proxy.routesService" (list . "auth")) .Release.Namespace) }}
