# Declare routers / services / middlewares
http:
  routers:
    graph-sparql:
      rule: {{ printf "Host(`%s`) && PathPrefix(`/sparql`)" .Values.global.apiHostDomain }}
      service: graph
      entryPoints:
        - web-api
      middleWares:
        - path-graph-sparql
        - host-graph
    graph-graphql:
      rule: {{ printf "Host(`%s`) && PathPrefix(`/graphql`)" .Values.global.apiHostDomain }}
      service: graph
      entryPoints:
        - web-api
      middleWares:
        - path-graph-graphql
        - host-graph
  services:
    graph:
      loadBalancer:
        servers:
          - url: http://{{ .Values.hosts.graph | default (printf "%s.%s:8080" (include "traefik-proxy.routesService" (list . "graph")) .Release.Namespace) }}

  middlewares:
    path-graph-sparql:
      replacePathRegex:
        regex: "^/sparql/(.*)"
        replacement: "/$1"
    path-graph-graphql:
      replacePathRegex:
        regex: "^/graphql/(.*)"
        replacement: "/$1"
    host-graph:
      headers:
        customRequestHeaders:
           host: {{ .Values.hosts.graph | default (printf "%s.%s:8080" (include "traefik-proxy.routesService" (list . "graph")) .Release.Namespace) }}
