# Declare routers / services / middlewares
http:
  routers:
    graph-ui:
      rule: {{ printf "Host(`%s`) && PathPrefix(`/graph`)" .Values.global.appHostDomain }}
      service: graph-ui
      entryPoints:
        - web-app
      middleWares:
        - path-graph-ui
        - host-graph-ui

  services:
    graph-ui:
      loadBalancer:
        servers:
          - url: {{ printf "http://%s"  (include "traefik-proxy.hostGraphUi" .) }}

  middlewares:
    path-graph-ui:
      replacePathRegex:
        regex: "^/graph(.*)"
        replacement: "/graph/$1"
    host-graph-ui:
      headers:
        customRequestHeaders:
          host: {{ include "traefik-proxy.hostGraphUi" . }}
