# Declare routers / services / middlewares
http:
  routers:
    oauth2-proxy:
      rule: {{ printf "Host(`%s`) && PathPrefix(`/oauth2`)" .Values.global.appHostDomain }}
      service: oauth2-proxy
      entryPoints:
        - web-app
      middleWares:
        - host-oauth2-proxy

  services:
    oauth2-proxy:
      loadBalancer:
        servers:
          - url: http://{{ .Values.hosts.oauth2Proxy | default (printf "%s.%s:4080" (include "traefik-proxy.routesService" (list . "oauth2-proxy")) .Release.Namespace) }}

  middlewares:
    host-oauth2-proxy:
      headers:
        customRequestHeaders:
          host: {{ .Values.hosts.oauth2Proxy | default (printf "%s.%s:4080" (include "traefik-proxy.routesService" (list . "oauth2-proxy")) .Release.Namespace) }}
