# Declare routers / services / middlewares
http:
  routers:    
    root-redirect:
      rule: {{ printf "Host(`%s`)" .Values.global.appHostDomain }}
      service: noop@internal
      entryPoints:
        - web-app
      middleWares:
        - search-ui-redirect

  middlewares:
    search-ui-redirect:
      redirectRegex:
        regex: "^https?://([^/]+)/?$"
        replacement: "https://$1/search"

    path-slash-redirect:
      redirectRegex:
        regex: "^(https?://[^/]+/[a-z0-9_-]+)$"
        replacement: "${1}/"
        permanent: true
