# Declare routers / services / middlewares
http:
  routers:
    search:
      rule: {{ printf "Host(`%s`) && PathPrefix(`/search`)" .Values.global.apiHostDomain }}
      service: search
      entryPoints:
        - web-api
      middleWares:
        - path-search
        - host-search

  services:
    search:
      loadBalancer:
        servers:
          - url: {{ printf "http://%s"  (include "traefik-proxy.hostSearch" .) }}

  middlewares:
    path-search:
      replacePathRegex:
        regex: "^/search/(.*)"
        replacement: "/$1"

    host-search:
      headers:
        customRequestHeaders:
          host: {{ include "traefik-proxy.hostSearch" . }}
