# Declare routers / services / middlewares
http:
  routers:
    search:
      rule: {{ printf "Host(`%s`) && PathPrefix(`/search`)" .Values.global.apiHostDomain }}
      service: search
      entryPoints:
        - web-api
      middleWares:
        - path-search
        - host-search
        - oauth2-verify

  services:
    search:
      loadBalancer:
        servers:
          - url: http://{{ .Values.hosts.search | default (printf "%s.%s:8181" (include "traefik-proxy.routesService" (list . "search")) .Release.Namespace) }}

  middlewares:
    path-search:
      replacePathRegex:
        regex: "^/search/(.*)"
        replacement: "/$1"

    host-search:
      headers:
        customRequestHeaders:
          host: {{ .Values.hosts.search | default (printf "%s.%s:8181" (include "traefik-proxy.routesService" (list . "search")) .Release.Namespace) }}
