# Declare routers / services / middlewares
http:
  routers:
    user-preferences:
      rule: {{ printf "Host(`%s`) && PathPrefix(`/user-preferences`)" .Values.global.apiHostDomain }}
      service: user-preferences
      entryPoints:
        - web-api
      middleWares:
        - host-user-preferences

  services:
    user-preferences:
      loadBalancer:
        servers:
          - url: http://{{ .Values.hosts.userPreferences | default (printf "%s.%s:11111" (include "traefik-proxy.routesService" (list . "user-preferences")) .Release.Namespace) }}

  middlewares:
    path-user-preferences:
      replacePathRegex:
        regex: "^/api/user-preferences/(.*)"
        replacement: "/$1"

    host-user-preferences:
      headers:
        customRequestHeaders:
          host: {{ .Values.hosts.userPeferences | default (printf "%s.%s:11111" (include "traefik-proxy.routesService" (list . "user-preferences")) .Release.Namespace) }}
