{{- /*
Copyright (C) 2025 Telicent Limited
*/}}

apiVersion: security.istio.io/v1
kind: AuthorizationPolicy

metadata:
  name: {{ include "oauth2-proxy.name" . }}-ingress-external
  labels:
    {{ include "oauth2-proxy.labels" . | nindent 4 }}

spec:
  action: ALLOW
  rules:
    - from:
        - source:
            principals:
              - {{ include "oauth2-proxy.ingressPrincipal" . }}
      to:
        - operation:
            methods:
              - GET
  selector:
    matchLabels:
    {{ include "oauth2-proxy.externalSelectorLabels" . | nindent 6 }}
