{{- if not .Values.existingCacertConfigmapName -}}
{{- if .Values.configuration.cacert -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "oauth2-proxy.cacertConfigmapName" . }}
  labels:
    {{- include "oauth2-proxy.labels" . | nindent 4 }}
data:
  ca.crt: {{- .Values.configuration.cacert | toYaml | indent 1 }}
{{- end -}}
{{- end -}}
