{{- /*
Copyright (C) 2025 Telicent Limited
*/}}

apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ include "oauth2-proxy.fullname" . }}
  namespace: {{ include "oauth2-proxy.namespace" . | quote }}
  labels:
    {{- include "oauth2-proxy.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations: 
    {{- toYaml . | nindent 4 }}
  {{- end }}

spec:
  replicas: {{ .Values.replicas }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      {{- include "oauth2-proxy.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
      {{- include "oauth2-proxy.labels" . | nindent 8 }}
      {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      annotations:
        checksum/configEnv: {{ include (print $.Template.BasePath "/configmap-env.yaml") . | sha256sum }}
        checksum/secretOauth: {{ include (print $.Template.BasePath "/secret-idp.yaml") . | sha256sum }}
        checksum/secretCa: {{ include (print $.Template.BasePath "/secret-ca.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}

    spec:
      serviceAccountName: {{ include "oauth2-proxy.serviceAccountName" . }}
      securityContext: {{- toYaml .Values.podSecurityContext | nindent 8 }}

      {{- $pullSecret := .Values.global.imagePullSecrets | default .Values.image.pullSecrets }}
      {{- with $pullSecret }}
      imagePullSecrets:
        {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- if .Values.initContainers }}
      initContainers:
      {{- with .Values.initContainers }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}
      containers:
      - name: oauth2-proxy
        image: {{ include "oauth2-proxy.image" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources: {{- toYaml .Values.resources | nindent 10 }}
        securityContext: {{- toYaml .Values.containerSecurityContext | nindent 10 }}

        env:
        - name: OAUTH2_PROXY_CLIENT_ID
          valueFrom:
            secretKeyRef:
              key: clientid
              name: {{ include "oauth2-proxy.idpSecretName" . }}
        - name: OAUTH2_PROXY_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              key: clientsecret
              name: {{ include "oauth2-proxy.idpSecretName" . }}
        - name: OAUTH2_PROXY_COOKIE_SECRET
          valueFrom:
            secretKeyRef:
              key: cookiesecret
              name: {{ include "oauth2-proxy.idpSecretName" . }}
        {{- if or (not (include "oauth2-proxy.caSecretName" . | empty )) .Values.tls.ca.existingConfigMap }}
        - name: OAUTH2_PROXY_PROVIDER_CA_FILES
          value: "/app/config/ca/ca.crt"
        - name: OAUTH2_PROXY_USE_SYSTEM_TRUST_STORE
          value: "true"
        {{- end }}
        {{- range .Values.extraEnvVars }}
        - name: {{ .name }}
          value: {{ .value }}
        {{- end }}
        envFrom:
        - configMapRef:
            name: {{ include "oauth2-proxy.envConfigMapName" . }}

        ports:
        - name: http
          containerPort: {{ .Values.service.port }}
          protocol: TCP

        readinessProbe:
          httpGet:
            path: /ready
            port: http
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 3
        livenessProbe:
          httpGet:
            path: /ping
            port: http
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 3

        {{- if or (not (include "oauth2-proxy.caSecretName" . | empty)) .Values.tls.ca.existingConfigMap }}
        volumeMounts:
        - name: ca-volume
          mountPath: /app/config/ca
        {{- end }}

      {{- with .Values.sidecars }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if or (not (include "oauth2-proxy.caSecretName" . | empty)) .Values.tls.ca.existingConfigMap }}
      volumes:
      - name: ca-volume
        {{- if not (include "oauth2-proxy.caSecretName" . | empty) }}
        secret:
          secretName: {{ include "oauth2-proxy.caSecretName" .  }}
          items:
            - key: ca.crt
              path: ca.crt
        {{- else }}
        configMap:
          name: {{ .Values.tls.ca.existingConfigMap }}
        {{- end }}
      {{- end }}

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
