{{- if not .Values.existingEnvSecret -}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "oauth2-proxy.envSecretName" . }}
  labels:
    {{- include "oauth2-proxy.labels" . | nindent 4 }}
data:
  OAUTH2_PROXY_CLIENT_SECRET: {{ .Values.configuration.clientSecret | b64enc | quote }}
  OAUTH2_PROXY_COOKIE_SECRET: {{ .Values.configuration.cookieSecret | default (randAscii 20) | b64enc | quote  }}
{{- end -}}
