{{- /*
Copyright (C) 2025 Telicent Limited
*/}}

{{- if not .Values.idp.existingSecret -}}
apiVersion: v1
kind: Secret
type: Opaque

metadata:
  name: {{ include "oauth2-proxy.idpSecretName" . }}
  namespace: {{ include "oauth2-proxy.namespace" . | quote }}
  labels:
    {{- include "oauth2-proxy.labels" . | nindent 4 }}

data:
  clientid: {{ .Values.idp.clientId | b64enc | quote }}
  clientsecret: {{ .Values.idp.clientSecret | b64enc | quote }}
  cookiesecret: {{ .Values.idp.cookieSecret | b64enc | quote }}

{{- end -}}
