{{- /*
Copyright (C) 2025 Telicent Limited
*/}}

{{- if .Values.tls.ca.certificate -}}
apiVersion: v1
kind: Secret
type: Opaque

metadata:
  name: {{ include "oauth2-proxy.caSecretName" . }}
  namespace: {{ include "oauth2-prox.namespace" . | quote }}
  labels:
    {{- include "oauth2-proxy.labels" . | nindent 4 }}

data:
  ca.crt: {{ .Values.tls.ca.certificate | b64enc | quote }}

{{- end -}}
