{{- /*
Copyright (C) 2025 Telicent Limited
*/}}

{{- if not .Values.oauthClientSecret.existingSecret -}}
apiVersion: v1
kind: Secret
type: Opaque

metadata:
  name: {{ include "oauth2-proxy.oauthSecretName" . }}
  namespace: {{ include "oauth2-prox.namespace" . | quote }}
  labels:
    {{- include "oauth2-proxy.labels" . | nindent 4 }}

data:
  clientid: {{ .Values.oauthClientSecret.clientId | b64enc | quote }}
  clientsecret: {{ .Values.oauthClientSecret.clientSecret | b64enc | quote }}
  cookiesecret: {{ .Values.oauthClientSecret.cookieSecret | b64enc | quote }}

{{- end -}}
