---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: {{ include "gateway-apps.fullname" . }}
  labels:
  {{- include "gateway-apps.labels" . | nindent 4 }}
spec:
  action: CUSTOM
  provider:
    name: {{ include "gateway-apps.customAuthzProviderName" . }}
  rules:
  - to:
    - operation:
        hosts:
        - {{ .Values.global.appsHost }}
        - {{ .Values.global.appsHost }}:*
        notPaths:
        - /oauth2/*
        - /oauth2
        paths:
        - /*
        - /
  selector:
    matchLabels:
      {{- .Values.ingressSelectors | toYaml | nindent 6 }}
