{{- /*
Copyright (C) 2026 Telicent Limited
*/}}
{{- if not .Values.elastic.existingSecret }}
apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
  name: {{ include "search-projector.elasticSecretName" . }}
  namespace: {{ include "search-projector.namespace" . | quote }}
  labels:
    {{- include "search-projector.labels" . | nindent 4 }}

data:
  username: {{ .Values.elastic.username | b64enc | quote }}
  password: {{ .Values.elastic.password | b64enc | quote }}
{{- end }}
