{{- /*
Copyright (C) 2026 Telicent Limited
*/}}
{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount

metadata:
  name: {{ include "search-projector.serviceAccountName" . }}
  namespace: {{ include "search-projector.namespace" . | quote }}
  labels:
    {{- include "search-projector.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}

automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}
