#
# PostgreSQL Storage - Configuration
#

# JDBC connection URL
storage.jdbc.url={{ .Values.postgres.jdbcUrl }}

# Database username
storage.jdbc.username=${POSTGRES_USERNAME}

# Database password
storage.jdbc.password=${POSTGRES_PASSWORD}
