{{- /*
Copyright (C) 2025 Telicent Limited
*/}}

{{- if and .Values.global.enterprise .Values.global.istioVirtualServiceEnabled }}
apiVersion: networking.istio.io/v1
kind: VirtualService

metadata:
  name: {{ include "search-ui.fullname" . }}-redirect
  labels:
  {{- include "search-ui.labels" . | nindent 4 }}

spec:
  gateways:
  - {{ .Values.global.istioNamespace }}/{{ .Values.global.istioGatewayName }}
  hosts:
  - {{ .Values.global.appHostDomain }}
  http:
    # Redirect https://hostname to https://hostname/search
    - match:
      - uri:
          exact: "/"
      redirect:
        uri: /search/

{{- end }}
