{{- /*
Copyright (C) 2025 Telicent Limited
*/}}
{{- if and .Values.global.enterprise .Values.global.istioVirtualServiceEnabled }}
apiVersion: networking.istio.io/v1
kind: VirtualService

metadata:
  name: {{ include "search-ui.fullname" . }}
  namespace: {{ include "search-ui.namespace" . | quote }}
  labels:
    {{- include "search-ui.labels" . | nindent 4 }}

spec:
  gateways:
  - {{ .Values.global.istioNamespace }}/{{ .Values.global.istioGatewayName }}
  hosts:
  - {{ .Values.global.appHostDomain }}
  http:
  - match:
    - uri:
        exact: "/search"
    redirect:
      uri: /search/
  - match:
    - uri:
        prefix: /search/
    route:
    - destination:
        host: {{ include "search-ui.serviceName" . }}
        port:
          number: {{ .Values.service.port }}
{{- end }}
