{{- range $topic := .Values.topics -}}
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: {{ $topic.name }}
  labels:
    {{- include "kafka.labels" $ | nindent 4 }}
    strimzi.io/cluster: {{ include "kafka.fullname" $ }}
spec:
  partitions: {{ $topic.partitions }}
  replicas: {{ $topic.replicas }}
  config:
    retention.ms: {{ $topic.retentionMs }}
    retention.bytes: {{ $topic.retentionBytes }}
{{ end }}
