{{- if not .Values.existingEnvConfigmap -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "oauth2-proxy.envConfigmapName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "oauth2-proxy.labels" . | nindent 4 }}
data:
  OAUTH2_PROXY_API_ROUTES: /api/.*$
  OAUTH2_PROXY_APPROVAL_PROMPT: none
  OAUTH2_PROXY_COOKIE_DOMAIN: {{ .Values.cookieDomain | quote }}
  OAUTH2_PROXY_COOKIE_EXPIRE: {{ .Values.cookieExpire | quote }}
  OAUTH2_PROXY_COOKIE_NAME: __Secure-session
  OAUTH2_PROXY_COOKIE_PATH: /
  OAUTH2_PROXY_COOKIE_REFRESH: {{ .Values.cookieRefresh | quote }}
  OAUTH2_PROXY_COOKIE_SAMESITE: lax
  OAUTH2_PROXY_COOKIE_SECURE: "true"
  OAUTH2_PROXY_EMAIL_DOMAINS: "*"
  OAUTH2_PROXY_HTTP_ADDRESS: 0.0.0.0:4080
  OAUTH2_PROXY_OIDC_ISSUER_URL: {{ .Values.oidcIssuerUrl | quote }}
  OAUTH2_PROXY_PROVIDER: oidc
  OAUTH2_PROXY_REDIRECT_URL: {{ .Values.oidcRedirectUrl | quote }}
  OAUTH2_PROXY_REVERSE_PROXY: "true"
  OAUTH2_PROXY_SCOPE: openid email offline_access profile
  OAUTH2_PROXY_SILENCE_PING_LOGGING: "true"
  OAUTH2_PROXY_SKIP_PROVIDER_BUTTON: "true"
  OAUTH2_PROXY_UPSTREAMS: static://200
  OAUTH2_PROXY_CLIENT_ID: {{ .Values.clientId | quote }}
{{- if .Values.internal }}
  OAUTH2_PROXY_PASS_ACCESS_TOKEN: "true"
  OAUTH2_PROXY_PASS_AUTHORIZATION_HEADER: "true"
  OAUTH2_PROXY_SET_AUTHORIZATION_HEADER: "true"
  OAUTH2_PROXY_SET_XAUTHREQUEST: "true"
{{- end -}}
{{- end -}}
