apiVersion: v1
kind: Service
metadata:
  name: {{ include "oauth2-proxy.serviceName" . }}
  labels:
  {{- include "oauth2-proxy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "oauth2-proxy.selectorLabels" . | nindent 4 }}
  ports:
  - name: http
    port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: {{ .Values.service.port }}
