{{- /*
Copyright (C) Telicent Limited
*/}}
{{- if not .Values.global.kafka.existingConfigSecretName }}
apiVersion: v1
kind: Secret

metadata:
  name: {{ include "grpc-server.fullname" . }}-kafka-config
  namespace: {{ include "grpc-server.namespace" . | quote }}
  labels:
    {{- include "grpc-server.labels" . | nindent 4 }}
type: Opaque

data:
  kafka-config.properties: {{- (include "grpc-server.kafka-config-properties" . ) | b64enc | toYaml | indent 1 }}
{{- end }}
---
{{- /*
Copyright (C) Telicent Limited
*/}}

{{- if not .Values.global.kafka.existingConfigSecretName }}
apiVersion: v1
kind: Secret

metadata:
  name: {{ include "grpc-server.fullname" . }}-kafka-config
  labels:
  {{- include "grpc-server.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    "sidecar.istio.io/inject": "false"
type: Opaque

data:
  kafka-config.properties: {{- (include "grpc-server.kafka-config-properties" . ) | b64enc | toYaml | indent 1 }}
\{{- end }}

{{/*
Copyright (C) Telicent Limited
*/}}
{{- define "grpc-server.kafka-config-properties" -}}
      security.protocol={{ .Values.global.kafka.protocol }}
      sasl.mechanism={{ .Values.global.kafka.mechanism }}
      {{- if eq .Values.global.kafka.mechanism "SCRAM-SHA-512" }}
      sasl.jaas.config=org.apache.kafka.common.security.scram.ScramLoginModule required \
      {{- else if eq .Values.global.kafka.mechanism "PLAIN" }}
      sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required \
      {{- end }}
        username={{ .Values.global.kafka.username | quote }} \
        password={{ .Values.global.kafka.password | quote }};
{{- end  -}}

