{{- /*
Copyright (C) 2026 Telicent Limited
*/}}
{{- if not .Values.postgres.existingSecret }}
apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth

metadata:
  name: {{ include "grpc-server.postgresSecretName" . }}
  namespace: {{ include "grpc-server.namespace" . | quote }}
  labels:
    {{- include "grpc-server.labels" . | nindent 4 }}

data:
  username: {{ .Values.postgres.username | b64enc | quote }}
  password: {{ .Values.postgres.password | b64enc | quote }}

{{- end -}}
