{{- /*
Copyright (C) 2025 Telicent Limited
*/}}
{{- if .Values.enabled -}}
apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ include "content-tagger.fullname" . }}
  namespace: {{ include "document-pipeline.namespace" . | quote }}
  labels:
    {{- include "content-tagger.labels" . | nindent 4 }}
  {{- with .Values.contentTagger.annotations }}
  annotations: 
    {{- toYaml . | nindent 4 }}
  {{- end }} 

spec:
  replicas: {{ .Values.contentTagger.replicas }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      {{- include "content-tagger.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.contentTagger.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "content-tagger.labels" . | nindent 8 }}
        {{- with .Values.contentTagger.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    
    spec:
      serviceAccountName: {{ include "document-pipeline.serviceAccountName" . }}
      securityContext: {{ .Values.contentTagger.podSecurityContext | default .Values.podSecurityContext | toYaml | nindent 8 }}

      {{- $pullSecret := .Values.global.imagePullSecrets | default .Values.contentTagger.image.pullSecrets }}
      {{- with $pullSecret }}
      imagePullSecrets:
        {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- if .Values.contentTagger.initContainers }}
      initContainers:
      {{- with .Values.contentTagger.initContainers }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}
        image: {{ include "content-tagger.image" . }}
        imagePullPolicy: {{ .Values.contentTagger.image.pullPolicy }}
        resources: {{ .Values.contentTagger.resources | default .Values.resources | toYaml | nindent 10 }}
        securityContext: {{ .Values.contentTagger.containerSecurityContext | default .Values.containerSecurityContext | toYaml | nindent 10 }}

        env:
        - name: KAFKA_CONFIG_FILE_PATH
          value: /app/config/kafka-auth/kafka-config.toml
        - name: BOOTSTRAP_SERVERS
          value: {{ .Values.global.kafka.bootstrapServers | quote }}
        - name: KAFKA_CONFIG_MODE
          value: {{ .Values.contentTagger.topics.kafkaConfigMode | quote }}
        - name: LOGGING_LEVEL
          value: {{ .Values.contentTagger.topics.loggingLevel | quote }}
        - name: SOURCE_TOPIC
          value: {{ .Values.contentTagger.topics.inputTopic | quote }}
        - name: TARGET_TOPIC
          value: {{ .Values.contentTagger.topics.outputTopic | quote }}
        - name: RDF_TAGGER_DATA_URI_STUB
          value: {{ .Values.contentTagger.topics.rdfTaggerDataUriStub | quote }}
        - name: DCT_URI
          value: {{ .Values.contentTagger.topics.dctUri | quote }}
        - name: IES_URI
          value: {{ .Values.contentTagger.topics.iesUri | quote }}
        - name: TONT_URI
          value: {{ .Values.contentTagger.topics.tontUri | quote }}
        - name: iso3166_URI
          value: {{ .Values.contentTagger.topics.iso3166Uri | quote }}
        {{- range .Values.contentTagger.extraEnvVars }}
        - name: {{ .name | quote  }}
          value: {{ .value | quote }}
        {{- end }}   

        volumeMounts:
        - name: kafka-auth-config
          mountPath: /app/config/kafka-auth/
        {{- with .Values.contentTagger.extraVolumeMounts }}
          {{- toYaml . | nindent 12 }}
        {{- end }}
      
      {{- with .Values.contentTagger.sidecars }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes: 
      - name: kafka-auth-config
        secret:
        {{- if .Values.global.kafka.existingConfigSecretName }}
          secretName: {{ .Values.global.kafka.existingConfigSecretName }}
        {{- else }}
          secretName: {{ include "document-pipeline.fullname" . }}-kafka-config
        {{- end }}
      {{- with .Values.contentTagger.extraVolumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.contentTagger.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.contentTagger.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.contentTagger.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end -}}
