{{/*
Copyright (C) 2025-2026 Telicent Limited
*/}}

{{- if not .Values.keycloak.existingSecret -}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "keycloak-realm.envSecretName" . }}
  labels:
    {{- include "keycloak-realm.labels" . | nindent 4 }}
  {{- if .Values.job.useHelmHooks }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": before-hook-creation
  {{- end }}
data:
  {{ .Values.keycloak.usernameKey }}: {{ .Values.keycloak.adminUsername | b64enc | quote }}
  {{ .Values.keycloak.passwordKey }}: {{ .Values.keycloak.adminPassword | b64enc | quote }}
{{- end -}}
