{{- /*
Copyright (C) 2025 Telicent Limited
*/}}

apiVersion: v1
kind: ConfigMap

metadata:
    name: {{ include "smart-cache-search.fullname" . }}-api
    labels:
        app.kubernetes.io/name: {{ include "smart-cache-search.name" . }}
        helm.sh/chart: {{ include "smart-cache-search.chart" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}

data:
    # Environment variables for the projector container
    # These values are used to configure the search projector service
    # Ensure that these values are set correctly in your values.yaml file
    ATTRIBUTE_HIERARCHY_URL: {{ .Values.api.configuration.attributeHierarchyUrl | quote }}
    ELASTIC_HOST: {{ .Values.api.configuration.elasticHost | quote }}
    ELASTIC_INDEX: {{ .Values.api.configuration.elasticIndexNames | quote }}
    ELASTIC_PORT: {{ .Values.api.configuration.elasticPort | quote }}
    ES_CLUSTER_PORT: {{ .Values.api.configuration.elasticClusterPort | quote }}
    FIELD_OPTIONS: {{ .Values.api.configuration.searchFieldOptions | quote }}
    JAVA_OPTIONS: {{ .Values.api.configuration.javaOptions | quote }}
    JWKS_URL: {{ .Values.global.jwksUrl | quote }}
    OPENSEARCH_COMPATIBILITY: {{ .Values.api.configuration.opensearchCompatibility | quote }}
    OTEL_METRICS_EXPORTER: {{ .Values.api.configuration.otelMetricsExporter | quote }}
    OTEL_TRACES_EXPORTER: {{ .Values.api.configuration.otelTracesExporter | quote }}
    USER_ATTRIBUTES_URL: {{ .Values.api.configuration.userAttributesUrl | quote }}
{{- with .Values.extraEnvs }}
{{- toYaml . | nindent 2 }}
{{- end }}
