{{- if not .Values.api.existingEnvironmentSecret }}
apiVersion: v1
kind: Secret
metadata:
    name: {{ include "smart-cache-search.fullname" . }}-api
    labels:
        {{- include "smart-cache-search.apiLabels" . | nindent 6 }}
type: Opaque
data:
    ELASTIC_PASSWORD: {{ .Values.api.elasticSecrets.elasticPassword | b64enc | quote }}
    ELASTIC_USER: {{ .Values.api.elasticSecrets.elasticUser | b64enc | quote }}
    TRUSTSTORE_PASS: {{ .Values.api.elasticSecrets.truststorePass | b64enc | quote }}
{{- end }}