# Copyright (C) 2025 Telicent Limited
# Telicent Smart Cache Graph stand-alone chart

# @section Global Parameters
# @descStart
# Contains global parameters, these parameters are mirrored within the Telicent core umbrella chart
# @descEnd
## Please, note that this will override the image parameters
## Current available global image parameters: imageRegistry and imagePullSecrets

#
global:
  # @key global.imageRegistry Global image registry
  imageRegistry: ""
  # E.g.
  # imagePullSecrets:
  #   - myRegistryKeySecretName
  #
  # @key global.imagePullSecrets Global registry secret names as an array
  imagePullSecrets: [ ]
  # @key global.appHostDomain Domain name associated with the application
  appHostDomain: "apps.telicent.io"
  # @key global.authHostDomain Domain to be used for interacting with Telicent authentication services, including OIDC providers
  authHostDomain: "auth.telicent.io"
  # @key global.istioServiceAccountName The name of the Istio service account to use for the Smart Cache Graph
  istioServiceAccountName: istio-ingress
  # @key global.istioNamespace The namespace where Istio is installed
  istioNamespace: istio-system
  # @key global.existingTruststoreSecretName The name of an existing secret containing the truststore
  existingTruststoreSecretName: ""
  # This is used to mount the truststore in the container, default is /app/config/truststore
  truststore:
    # @key global.truststore.mountPath The mount path for the truststore in the container
    mountPath: /app/config/truststore

# @section Configuration Parameters
# @descStart
# Contains configuration parameters specific to the Smart Cache Graph application
# @descEnd
configuration:
  # @key configuration.userAttributesUrl URL for the user details endpoint
  userAttributesUrl: http://access-api.tc-system.svc.cluster.local:8080/users/lookup/{user}
  # @key configuration.attributeHierarchyUrl URL for the user hierarchy endpoint
  attributeHierarchyUrl: http://access-api.tc-system.svc.cluster.local:8080/hierarchies/lookup/{name}
  # @key configuration.javaOptions JVM options for the application
  javaOptions: -Xmx5120m -Xms2048m -Djavax.net.ssl.trustStore=/app/config/truststore/truststore.jks
  # @key configuration.otelMetricsExporter OpenTelemetry metrics exporter
  # Options: prometheus, otlp, none
  otelMetricsExporter: prometheus
  # @key configuration.otelTracesExporter OpenTelemetry traces exporter
  # Options: otlp, none
  otelTracesExporter: none

# @section Common Parameters
#@key fullnameOverride String to fully override the generated release name
fullnameOverride: ""
# @key nameOverride sets a custom name for the chart it differs from fullnameOverride as it is not fully qualified
nameOverride: ""

# @section Smart Cache Graph Statefulset Parameters
# @key replicas Number of Smart Cache Graph replicas to deploy
replicas: 1
# @key revisionHistoryLimit Number of controller revisions to keep
revisionHistoryLimit: 5
# @key annotations Add extra annotations to the Statefulset object
annotations: { }

image:
  # @key image.registry [default: REGISTRY_NAME] Smart Cache Graph image registry
  registry: docker.io
  # @key image.repository [default: REPOSITORY_NAME/smart-cache-graph] Smart Cache Graph image name
  repository: telicent/smart-cache-graph
  # @key image.tag Smart Cache Graph image tag. If not set, a tag is generated using the appVersion
  tag: ""
  # @key image.pullPolicy Smart Cache Graph image pull policy
  pullPolicy: IfNotPresent
  # @key image.pullSecrets Specify registry secret names as an array
  pullSecrets: [ ]

resources:
  requests:
    # @key resources.requests.cpu Set containers' CPU request
    cpu: "500m"
    # @key resources.requests.memory Set containers' memory request
    memory: "8000Mi"
  limits:
    # @key resources.limits.cpu Set containers' CPU limit
    cpu: "1500m"
    # @key resources.limits.memory Set containers' memory limit
    memory: "12000Mi"

containerSecurityContext:
  # @key containerSecurityContext.runAsUser Set containers' Security Context runAsUser User ID
  runAsUser: 185
  # @key containerSecurityContext.runAsGroup Set containers' Security Context runAsGroup Group ID
  runAsGroup: 185
  # @key containerSecurityContext.runAsNonRoot Set container's Security Context runAsNonRoot
  runAsNonRoot: true
  # @key containerSecurityContext.allowPrivilegeEscalation Set container's Security Context allowPrivilegeEscalation
  allowPrivilegeEscalation: false
  capabilities:
    #@key containerSecurityContext.capabilities.drop List of capabilities to be dropped
    drop:
      - ALL
  seccompProfile:
    # @key containerSecurityContext.seccompProfile.type Set container's Security Context seccomp profile
    type: RuntimeDefault

podSecurityContext:
  # @key podSecurityContext.runAsUser Set the provisioning pod's Security Context runAsUser User ID
  runAsUser: 185
  # @key podSecurityContext.runAsGroup Set the provisioning pod's Security Context runAsGroup Group ID
  runAsGroup: 185
  # @key podSecurityContext.runAsNonRoot Set the provisioning pod's Security Context runAsNonRoot
  runAsNonRoot: true
  # @key podSecurityContext.fsGroup Set the provisioning pod's Group ID for the mounted volumes' filesystem
  fsGroup: 185
  seccompProfile:
    # @key podSecurityContext.seccompProfile.type Set the provisioning pod's Security Context seccomp profile
    type: RuntimeDefault

# @section Persistent Volume Claim Parameters
persistentVolumeClaims:
  backupsVolume:
    # @key persistentVolumeClaims.backupsVolume.size PVC Storage Request for Backup volume
    size: 100Gi
    # @key persistentVolumeClaims.backupsVolume.storageClass PVC Storage Class for the Backup data volume
    storageClass: gp3-enc
  datasetsVolume:
    # @key persistentVolumeClaims.datasetsVolume.size PVC Storage Request for Graph volume
    size: 25Gi
    # @key persistentVolumeClaims.datasetsVolume.storageClass iPVC Storage Class for the Graph data volume
    storageClass: gp3-enc

# @section Metrics Parameters
metrics:
  service:
    # @key metrics.service.port is the port for the Prometheus service
    port: 9464
    # @key metrics.service.name is the name for the Prometheus service
    name: metrics

# @section Traffic Exposure Parameters
service:
  # @key service.port is the port the service will listen on
  port: 3030
  # @key service.type defines the service type
  type: ClusterIP

ingress:
  # @key ingress.principal Principal to use for ingress traffic. If not set, defaults to the Istio service account in the istio-system
  principal: ""

# @section Service Account Parameters
serviceAccount:
  # @key serviceAccount.name Name of the created ServiceAccount. If not set, a name is generated using the fullname template
  name: ""
  #@key serviceAccount.annotations Additional custom annotations for the ServiceAccount
  annotations: { }


