apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: {{ include "keycloak.fullname" . }}
  labels:
  {{- include "keycloak.labels" . | nindent 4 }}
spec:
  action: ALLOW
  rules:
  - from:
    - source:
        principals:
        - '*'
    to:
    - operation:
        methods:
        - GET
        paths:
        - /
        - /*
  - from:
    - source:
        principals:
        - {{ include "keycloak.ingressPrincipal" . }}
    to:
    - operation:
        methods:
        - '*'
  selector:
    matchLabels:
      {{- include "keycloak.selectorLabels" . | nindent 6 }}
