apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "keycloak.serviceAccountName" . }}
  labels:
  {{- include "keycloak.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.serviceAccount.annotations | nindent 4 }}
