{{- /*
Copyright (C) 2025 Telicent Limited
*/}}
{{- if and (.Values.enabled) (not .Values.existingConfigMapName) -}}
apiVersion: v1
kind: ConfigMap

metadata:
  name: {{ include "grpc-server.configMapName" . }}
  namespace: {{ include "grpc-server.namespace" . | quote }}
  labels:
    {{- include "grpc-server.labels" . | nindent 4 }}

data:

  {{- end }}
