{{- /*
Copyright (C) Telicent Limited
*/}}
{{- if and (.Values.enabled) (not .Values.existingConfigMapName) -}}
apiVersion: v1
kind: ConfigMap

metadata:
  name: {{ include "grpc-server.configMapName" . }}
  namespace: {{ include "grpc-server.namespace" . | quote }}
  labels:
    {{- include "grpc-server.labels" . | nindent 4 }}

data:
  SERVER_PROPERTIES: /app/config/server.properties
  LOG_LEVEL_ROOT: {{ .Values.logs.root.level | quote  }}
  LOG_LEVEL_APP: {{ .Values.logs.app.level | quote  }}
  LOG_LEVEL_KAFKA: {{ .Values.logs.kafka.level | quote  }}
  {{- end }}
