{{- /*
Copyright (C) 2025 Telicent Limited
*/}}

apiVersion: v1
kind: ConfigMap

metadata:
  name: {{ include "grpc-server.storageConfigMapName" . }}
  namespace: {{ include "grpc-server.namespace" . | quote }}
  labels:
    {{- include "grpc-server.labels" . | nindent 4 }}

data:
  storage.properties: |-
  {{- tpl ($.Files.Get "configs/storage.properties") . | nindent 4 }}

