{{- if .Values.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "spatial-projector.fullname" . }}
  labels:
    {{- include "spatial-projector.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 9000
      protocol: TCP
      name: http
  selector:
    {{- include "spatial-projector.selectorLabels" . | nindent 4 }}
{{- end }}
