{{- /*
Copyright (C) 2025 Telicent Limited
*/}}

apiVersion: security.istio.io/v1
kind: AuthorizationPolicy

metadata:
  name: {{ include "auth.fullname" . }}-internal-ingress
  namespace: {{ include "auth.namespace" . | quote }}
  labels:
    {{- include "auth.labels" . | nindent 4 }}

spec:
  selector:
    matchLabels:
      {{- include "auth.selectorLabels" . | nindent 6 }}
  action: ALLOW
  rules:
  - from:
    - source:
        principals:
         {{- include "auth.graphPrincipal" . | nindent 8 }}
         {{- include "auth.userPreferencesPrincipal" . | nindent 8 }}
         {{- include "auth.searchPrincipal" . | nindent 8 }}
         {{- include "auth.paperbackWriterPrincipal" . | nindent 8 }}
    to:
    - operation:
        methods: ["GET", "POST", "PUT", "DELETE"]
