{{- /*
Copyright (C) 2025 Telicent Limited
*/}}

apiVersion: security.istio.io/v1
kind: PeerAuthentication

metadata:
  name: {{ include "auth.name" . }}-strict
  namespace: {{ include "auth.namespace" . | quote }}
  labels:
    {{- include "auth.labels" . | nindent 4 }}

spec:
  mtls:
    mode: STRICT
