{{- /*
Copyright (C) 2025 Telicent Limited
*/}}

apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ include "search.fullname" . }}
  labels:
    {{- include "search.labels" . | nindent 4 }}

spec:
  replicas: {{ .Values.replicas }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
    {{- include "search.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        prometheus.io/path: /
        prometheus.io/port: "9464"
        prometheus.io/scrape: "true"
        checksum/config: {{ include (print $.Template.BasePath "/configmap-env.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "search.labels" . | nindent 8 }}

    spec:
      serviceAccountName: {{ include "search.serviceAccountName" . }}
      securityContext: {{- toYaml .Values.podSecurityContext | nindent 8 }}
      
      {{- $pullSecret := .Values.global.imagePullSecrets | default .Values.image.pullSecrets }}
      {{- with $pullSecret }}
      imagePullSecrets:
        {{- toYaml . | nindent 6 }}
      {{- end }}
      containers:
      - name: search
        image: {{ include "search.image" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources: {{- toYaml .Values.resources | nindent 10 }}
        securityContext: {{- toYaml .Values.containerSecurityContext | nindent 10 }}
        
        env:
        - name: ELASTIC_USER
          valueFrom:
            secretKeyRef:
              key: username
              name: {{ include "search.elasticSecretName" . }}
        - name: ELASTIC_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: {{ include "search.elasticSecretName" . }}
        
        {{- range .Values.extraEnvVars }}
        - name: {{ .name }}
          value: {{ .value }}
        {{- end }}
        envFrom:
        - configMapRef:
            name: {{ include "search.envConfigMapName" . }}
       
        ports:
        - name: http
          containerPort: 8181
          protocol: TCP
        - name: metrics
          containerPort: 9464
          protocol: TCP

        readinessProbe:
          httpGet:
            path: /healthz
            port: 8181
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 60
          timeoutSeconds: 10
        livenessProbe:
          httpGet:
            path: /version-info
            port: 8181
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 60
          timeoutSeconds: 5

        {{- if .Values.global.truststore.existingSecretName }}
        volumeMounts:
        - mountPath: {{ .Values.global.truststore.mountPath | default "/app/config/truststore" }}
          name: java-truststore
        {{- end }}
      {{- with .Values.extraContainers }}
        {{- toYaml . | nindent 6 }}
      {{- end }}
     
      {{- if .Values.global.truststore.existingSecretName }}
      volumes:
      - name: java-truststore
        secret:
          secretName: {{ .Values.global.truststore.existingSecretName }}
      {{- end }}
