{{- /*
Copyright (C) 2025 Telicent Limited
*/}}

{{- if not .Values.elasticSecret.existingSecret }}
apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth

metadata:
  name: {{ include "search.elasticSecretName" . }}
  labels:
    {{- include "search.labels" . | nindent 4 }}

data:
  username: {{ .Values.elasticSecret.username | b64enc | quote }}
  password: {{ .Values.elasticSecret.password | b64enc | quote }}
{{- end }}
