{{- /*
Copyright (C) 2025 Telicent Limited
*/}}

apiVersion: v1
kind: Service

metadata:
  name: {{ include "search.serviceName" .}}
  labels:
    {{- include "search.labels" . | nindent 4 }}

spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "search.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      appProtocol: http
      targetPort: http
      protocol: TCP
      port: {{ .Values.service.port }}

    {{- if .Values.metrics.enabled }}
    - name: {{ .Values.metrics.service.name | default "metrics" }}
      appProtocol: http
      targetPort: metrics
      protocol: TCP
      port: {{ .Values.metrics.service.port }}
    {{- end }}
