# Declare routers / services / middlewares
http:
  routers:
    cors-auth-options:
      rule: {{ printf "Host(`%s`) && Method(`OPTIONS`)" .Values.global.authHostDomain }}
      service: noop@internal
      priority: 999
      entryPoints:
        - web-auth
      middleWares:
        - cors
