{{- /*
Copyright (C) 2025 Telicent Limited
*/}}

apiVersion: security.istio.io/v1
kind: AuthorizationPolicy

metadata:
  name: {{ include "oauth2-proxy.fullname" . }}-ingress
  namespace: {{ include "oauth2-proxy.namespace" . | quote }}
  labels:
    {{ include "oauth2-proxy.labels" . | nindent 4 }}

spec:
  selector:
    matchLabels:
      {{- include "oauth2-proxy.selectorLabels" . | nindent 6  }}
  action: ALLOW
  rules:
  - from:
    - source:
        principals:
          {{- include "oauth2-proxy.ingressPrincipal" . | nindent 8 }}
    to:
    - operation:
        methods: ["*"]
