{{- /*
Copyright (C) 2025 Telicent Limited
*/}}

{{- if .Values.istio.virtualService.enabled }}
apiVersion: networking.istio.io/v1
kind: VirtualService

metadata:
  name: {{ include "oauth2-proxy.fullname" . }}
  namespace: {{ include "oauth2-proxy.namespace" . | quote }}
  labels:
    {{- include "oauth2-proxy.labels" . | nindent 4 }}

spec:
  gateways:
  - {{ include "istio.gatewayNamespace" . }}/{{ include "istio.gatewayName" . }}
  hosts:
  - {{ .Values.istio.virtualService.host | default .Values.global.appHostDomain }}
  http:
  - match:
    - uri:
        prefix: /oauth2
    route:
    - destination:
        host: {{ include "oauth2-proxy.serviceName" . }}
        port:
          number: {{ .Values.service.port }}

{{- end }}
