apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "mongodb.fullname" . }}
  labels:
  {{- include "mongodb.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "mongodb.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: mongodb-database
