{{- /*
Copyright (C) 2025 Telicent Limited
*/}}
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy

metadata:
  name: {{ include "spatial.fullname" . }}-ingress
  labels:
  {{- include "spatial.labels" . | nindent 4 }}

spec:
  action: ALLOW
  rules:
    - from:
        - source:
            principals:
            - {{ include "spatial.ingressPrincipal" . }}
  selector:
    matchLabels:
    {{- include "spatial.selectorLabels" . | nindent 6 }}
