{{- /*
Copyright (C) 2025 Telicent Limited
*/}}

{{- if .Values.global.istioVirtualServiceEnabled }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService

metadata:
  name: {{ include "spatial-projector.fullname" . }}
  labels:
    {{- include "spatial-projector.labels" . | nindent 4 }}

spec:
  gateways:
  - {{ .Values.global.istioNamespace }}/{{ .Values.global.istioGatewayName }}
  hosts:
  - {{ .Values.global.appHostDomain }}
  http:
  - match:
    - uri:
        prefix: /api/spatial-projector
    route:
    - destination:
        host: {{ include "spatial-projector.fullname" . }}
        port:
          number: {{ .Values.service.port }}
{{- end }}
