apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "system-mesh.fullname" . }}-oauth2-proxy
  labels:
  {{- include "system-mesh.labels" . | nindent 4 }}
spec:
  gateways:
  - {{ .Values.appsGateway }}
  hosts:
  - {{ .Values.appsHost }}
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: {{ .Values.oauth2proxy.external.serviceName }}
        port:
          number: {{ .Values.oauth2proxy.external.port }}
