name: Lint and Test Charts

on: pull_request

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v4.2.0
        with:
          version: v3.17.0

      - uses: actions/setup-python@v5.3.0
        with:
          python-version: "3.13"
          check-latest: true

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.7.0

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed)
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Run chart-testing (lint)
        if: steps.list-changed.outputs.changed == 'true'
        run: |
          helm repo add  telicent-core-charts 'https://charts.telicent.io'
          helm dependency update ./charts/telicent-core
          helm dependency update ./charts/telicent-preview
          helm dependency update ./charts/telicent-data
          ct lint --config .github/ct.yaml

  values-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Make metadataUpdater executable
        run: chmod +x .dev/metadataUpdater.sh

      - name: Make readme-generator-for-helm executable
        run: chmod +x .dev/readme-generator-for-helm

      - name: Run metadata updater
        run: .dev/metadataUpdater.sh

      - name: Check for uncommitted changes
        run: |
          if git diff --exit-code; then
            echo "✓ All documentation is up to date"
          else
            echo "✗ README files and schemas are out of sync with values.yaml"
            echo "Please run '.dev/metadataUpdater. sh' locally and commit the changes"
            git diff
            exit 1
          fi
