###############################################################################
# Note release-please-config.json should reflect the same number of packages as
# /configure/charts
###############################################################################
name: Create PRs for helm chart releases
on:
  workflow_dispatch:
  push:
    branches:
      - "main"

permissions:
  contents: write
  # Release please dependency
  pull-requests: write
  # Release please dependency? (attempts to fix: "You do not have permission to create labels on this repository" - PR write should be enough!)
  issues: write
  # AWS OIDC Dependency
  id-token: write

jobs:
  create-release-pr-or-tag-release:
    runs-on: ubuntu-latest
    outputs:
      releases_created: ${{ steps.release.outputs.releases_created }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: googleapis/release-please-action@v4.3.0
        id: release
        with:
          config-file: .github/release-please-config.json
          manifest-file: .github/release-please-manifest.json

  publish:
    if: needs.create-release-pr-or-tag-release.outputs.releases_created == 'true'
    name: Publish Charts
    needs: create-release-pr-or-tag-release
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v4.3.0

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.7.0

      - name: Package changed charts
        run: |
          helm repo add telicent-core-charts 'https://charts.telicent.io'
          helm dependency update ./charts/telicent-core
          for chart in $(find ./charts -maxdepth 1 -mindepth 1 -type d); do echo "packaging chart - $chart" && helm package -u -d .cr-release-packages $chart; done

      - name: checkout pages branch
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: gh-pages
          path: deploy

      - name: index charts
        run: helm repo index .cr-release-packages --merge deploy/index.yaml

      - name: Copy packages to deployment directory
        run: |
          mkdir -p deploy/packages
          cp README.md deploy/
          cp .cr-release-packages/*.tgz deploy/
          cp .cr-release-packages/index.yaml deploy/

      - name: Set up Git
        working-directory: deploy
        run: |
          git config --global user.name "$GITHUB_ACTOR"
          git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Commit and push changes
        working-directory: deploy
        run: |
          git add -A
          git commit -m "Update Helm charts: $(ct list-changed --config .github/ct.yaml | tr , '\n')"
          git branch -a
          git push origin gh-pages
