{{- /*
Copyright (C) 2025 Telicent Limited
*/}}

{{- if and .Values.global.enterprise .Values.global.istioVirtualServiceEnabled }}
apiVersion: networking.istio.io/v1
kind: VirtualService

metadata:
  name: {{ include "admin-ui.fullname" . }}
  labels:
    {{- include "admin-ui.labels" . | nindent 4 }}

spec:
  gateways:
    - {{ .Values.global.istioNamespace }}/{{ .Values.global.istioGatewayName }}
  hosts:
    - {{ .Values.global.appHostDomain }}
  http:
    - match:
        - uri:
            exact: /admin
      redirect:
        uri: /admin/
    - match:
        - uri:
            prefix: /admin
      route:
        - destination:
            host: {{ include "admin-ui.serviceName" . }}
            port:
              number: {{ .Values.service.port }}
{{- end }}